### ISSUE TITLE
CSphere image thumbnail link change (from https://thumbnails.calisphere.org --> https://calisphere.org) - UCI Artists Book portal updates

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#1023]
Transferred from this Trello card: https://trello.com/c/vP1NDKnR/410-csphere-image-thumbnail-link-change-from-https-thumbnailscalisphereorg-https-calisphereorg-uci-artists-book-portal-updates

***

Updated July 2, 2024:
Calisphere thumbnail URLs now have the collection ID: 
- https://calisphere.org/crop/100x100/26147/19662ad7863ffbdda69de5dbfdb3817b
- https://calisphere.org/crop/250x250/26147/19662ad7863ffbdda69de5dbfdb3817b

Updated Nov 23, 2024:
Amy fixed the thumbnail issue for these thumbnail links! The thumbnails now work: [Artists' Books Discovery Tool](https://www.lib.uci.edu/sites/all/plodab/index.php)
Though we still may want to have the conversation about URLs.

Card description Aug 2022:
I'm unsure if this is a CSphere issue (or if we need to ask UCI to update links), but the image thumbnails on this UCI tool no longer work: https://www.lib.uci.edu/sites/all/plodab/index.php -- this links to the particular tool, and you kinda need to click through to an object pop-up to see that the image thumbnails are not working.

The image thumbnail points to: https://thumbnails.calisphere.org/clip/250x250/19662ad7863ffbdda69de5dbfdb3817b
This version of the link seems to work: https://calisphere.org/clip/250x250/19662ad7863ffbdda69de5dbfdb3817b (remove thumbnails)

Also, here's the CSphere object record: https://calisphere.org/item/ark:/87280/t0f769gk/
And the image thumbnail on the record page: https://calisphere.org/crop/100x100/19662ad7863ffbdda69de5dbfdb3817b

Were the thumbnail image URLs updated at some point? Is there a way we can easily resolve on our end? Or do we need to ask UCI to update the thumbnail image URLs?

**Comment by aturner** [comment]
Message to Audra, Madelynn, and Paul to request the update: https://help.oac.cdlib.org/a/tickets/140814

**Comment by amywieliczka** [comment]
Once this is done, we can remove [harvested_images/](https://us-west-2.console.aws.amazon.com/s3/buckets/static-ucldc-cdlib-org?region=us-west-2&bucketType=general&prefix=harvested_images/&showversions=false) and the thumbnailer beanstalk.

**Comment by aturner** [comment]
@amywieliczka UCI updated the Artists' Books portal, changing the old https://thumbnails.calisphere.org/clip/ base URLs to the new https://calisphere.org/clip/ base URL. So we're all set on that front! https://www.lib.uci.edu/sites/all/plodab/index.php
