### ISSUE TITLE
UCB BAMPFA: Remove 5 collections

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#1035]
## Collection details
- Endpoint: OAC
- [x] 4072
- [x] 4328
- [x] 10126
- [x] 10616
- [x] 10664

## Communications
- Freshdesk thread URL: 

## Request type
- [ ] New collection harvest
- [ ] Re-harvest whole collection (on request)
- [ ] Re-harvest metadata only (on request)
- [ ] Scheduled recurring harvests
- [x] Delete whole collection (on request)
- [ ] Item record removals
- [ ] OAC METS replacement
- [ ] Redirects needed
- [ ] Other

Notes:

## Harvesting request details
[copy/paste from forms]

**Comment by aturner** [comment]
@gamontoya the collections have been unpublished from CSphere. The METS can now be removed from OAC, and finding aids updated with a top-level <dao> (and <daogrp> file/item-level links can be removed)

**Comment by gamontoya** [comment]
@aturner @christinklez I believe I already did this work in early July. See: https://help.oac.cdlib.org/a/tickets/140203
