### ISSUE TITLE
UCLA DLP: 27 collections

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#1049]
## Collection details
Airflow shortcuts to find the staged versions:
- [28227 Airflow run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?&dag_run_id=manual__2024-05-06T22%3A20%3A25%2B00%3A00&base_date=2024-05-06T22%3A20%3A25)
- [28254 Airflow run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-05-13T21%3A28%3A32%2B00%3A00&base_date=2024-05-13T21%3A28%3A32)
- [28255 Airflow run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-05-15T17%3A00%3A21%2B00%3A00&base_date=2024-05-16T17%3A00%3A21)
- [28183 Airflow run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?&dag_run_id=manual__2024-05-22T18%3A26%3A45%2B00%3A00&base_date=2024-05-23T18%3A26%3A45)
- [28277 Airflow run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-05-29T17%3A41%3A11%2B00%3A00&base_date=2024-05-30T17%3A41%3A11)

Registry URLs:
- [x] [28227](https://registry.cdlib.org/admin/library_collection/collection/28227) - version path: `28227/vernacular_metadata_2024-05-06T22:20:37/mapped_metadata_2024-05-06T22:20:48/with_content_urls_2024-05-06T22:21:08/`
- [x] [28228](https://registry.cdlib.org/admin/library_collection/collection/28228) - version path: `28228/vernacular_metadata_2024-05-06T22:20:37/mapped_metadata_2024-05-06T22:21:01/with_content_urls_2024-05-06T22:21:25/`
- [x] [28229](https://registry.cdlib.org/admin/library_collection/collection/28229) - version path: `28229/vernacular_metadata_2024-05-06T22:20:34/mapped_metadata_2024-05-06T22:20:48/with_content_urls_2024-05-06T22:21:17`
- [x] [28230](https://registry.cdlib.org/admin/library_collection/collection/28230) - version path: `28230/vernacular_metadata_2024-05-06T22:20:28/mapped_metadata_2024-05-06T22:22:11/with_content_urls_2024-05-06T22:23:14/`
- [x] [28231](https://registry.cdlib.org/admin/library_collection/collection/28231) - version path: `28231/vernacular_metadata_2024-05-06T22:20:27/mapped_metadata_2024-05-06T22:20:49/with_content_urls_2024-05-06T22:21:15/`
- [x] [28232](https://registry.cdlib.org/admin/library_collection/collection/28232) - version path: `28232/vernacular_metadata_2024-05-06T22:20:19/mapped_metadata_2024-05-06T22:20:33/with_content_urls_2024-05-06T22:20:58/`
- [x] [28233](https://registry.cdlib.org/admin/library_collection/collection/28233) - version path: `28233/vernacular_metadata_2024-05-06T22:20:09/mapped_metadata_2024-05-06T22:20:27/with_content_urls_2024-05-06T22:20:53/`
- [x] [28254](https://registry.cdlib.org/admin/library_collection/collection/28254) - version path: `28254/vernacular_metadata_2024-05-13T21:28:42/mapped_metadata_2024-05-13T21:29:09/with_content_urls_2024-05-13T21:31:07/`
- [x] [28255](https://registry.cdlib.org/admin/library_collection/collection/28255) - version path: `28255/vernacular_metadata_2024-05-15T17:00:34/mapped_metadata_2024-05-15T17:00:45/with_content_urls_2024-05-15T17:01:02/`
- [x] [156](https://registry.cdlib.org/admin/library_collection/collection/156) - version path: `156/vernacular_metadata_2024-05-15T18:37:17/mapped_metadata_2024-05-15T18:37:35/with_content_urls_2024-05-15T18:38:14/`
- [x] [26899](https://registry.cdlib.org/admin/library_collection/collection/26899) - version path: `26899/vernacular_metadata_2024-05-20T17:17:34/mapped_metadata_2024-05-20T17:18:05/with_content_urls_2024-05-20T17:20:23/`
- [x] [28183](https://registry.cdlib.org/admin/library_collection/collection/28183) - version path: `28183/vernacular_metadata_2024-05-22T18:28:47/mapped_metadata_2024-05-22T18:28:57/with_content_urls_2024-05-22T18:29:23/`
- [x] [28184](https://registry.cdlib.org/admin/library_collection/collection/28184) - version path: `28184/vernacular_metadata_2024-05-22T23:20:40/mapped_metadata_2024-05-22T23:22:13/with_content_urls_2024-05-22T23:25:07/`
- [x] [28185](https://registry.cdlib.org/admin/library_collection/collection/28185) - version path: `28185/vernacular_metadata_2024-05-22T23:20:14/mapped_metadata_2024-05-22T23:21:33/with_content_urls_2024-05-22T23:23:49/`
- [x] [28186](https://registry.cdlib.org/admin/library_collection/collection/28186) - version path: `28186/vernacular_metadata_2024-05-22T23:20:04/mapped_metadata_2024-05-22T23:22:15/with_content_urls_2024-05-22T23:25:13/`
- [x] [28187](https://registry.cdlib.org/admin/library_collection/collection/28187) - version path: `28187/vernacular_metadata_2024-05-22T23:20:15/mapped_metadata_2024-05-22T23:22:27/with_content_urls_2024-05-22T23:25:19/`
- [x] [28188](https://registry.cdlib.org/admin/library_collection/collection/28188) - version path: `28188/vernacular_metadata_2024-05-22T23:19:55/mapped_metadata_2024-05-22T23:21:49/with_content_urls_2024-05-22T23:25:03/`
- [x] [28189](https://registry.cdlib.org/admin/library_collection/collection/28189) - version path: `28189/vernacular_metadata_2024-05-22T23:19:31/mapped_metadata_2024-05-22T23:20:56/with_content_urls_2024-05-22T23:25:07/`
- [x] [28190](https://registry.cdlib.org/admin/library_collection/collection/28190/) - version path: `28190/vernacular_metadata_2024-05-22T23:19:37/mapped_metadata_2024-05-22T23:22:02/with_content_urls_2024-05-22T23:25:19/`
- [x] [28193](https://registry.cdlib.org/admin/library_collection/collection/28193) - version path: `28193/vernacular_metadata_2024-05-22T23:19:08/mapped_metadata_2024-05-22T23:20:40/with_content_urls_2024-05-22T23:23:15/`
- [x] [28194](https://registry.cdlib.org/admin/library_collection/collection/28194) - version path: `28194/vernacular_metadata_2024-05-22T23:19:01/mapped_metadata_2024-05-22T23:20:57/with_content_urls_2024-05-22T23:24:44/`
- [x] [28256](https://registry.cdlib.org/admin/library_collection/collection/28256) - version path: `28256/vernacular_metadata_2024-05-22T23:18:39/mapped_metadata_2024-05-22T23:20:19/with_content_urls_2024-05-22T23:22:00/`
- [x] [28257](https://registry.cdlib.org/admin/library_collection/collection/28257/) - version path: `28257/vernacular_metadata_2024-05-22T23:18:31/mapped_metadata_2024-05-22T23:20:24/with_content_urls_2024-05-22T23:23:31/`
- [x] [28258](https://registry.cdlib.org/admin/library_collection/collection/28258/) - version path: `28258/vernacular_metadata_2024-05-22T23:18:05/mapped_metadata_2024-05-22T23:19:00/with_content_urls_2024-05-22T23:21:33/`
- [x] [28192](https://registry.cdlib.org/admin/library_collection/collection/28192) - version path: `28192/vernacular_metadata_2024-05-22T23:19:35/mapped_metadata_2024-05-22T23:21:39/with_content_urls_2024-05-22T23:24:44/`
- [x] [28277](https://registry.cdlib.org/admin/library_collection/collection/28277) - version path: `28277/vernacular_metadata_2024-05-29T17:41:23/mapped_metadata_2024-05-29T17:41:35/with_content_urls_2024-05-29T17:42:02/`
- [x] [28278](https://registry.cdlib.org/admin/library_collection/collection/28278) - version path: `28278/vernacular_metadata_2024-05-29T17:41:43/mapped_metadata_2024-05-29T17:42:03/with_content_urls_2024-05-29T17:42:54/`

Preview on -stage:
- Carey McWilliams Papers, 1894-1982 (bulk 1921-1980) -- https://calisphere-stage.cdlib.org/collections/28227 
- Carleton Watkins Collection of Photographs -- https://calisphere-stage.cdlib.org/collections/28228 
- Caro Minasian Collection of Armenian Material -- https://calisphere-stage.cdlib.org/collections/28229 
- Cashin (Bonnie) Collection of Fashion, Theatre, and Film Costume Design -- https://calisphere-stage.cdlib.org/collections/28230 
- Cole Family Papers -- https://calisphere-stage.cdlib.org/collections/28231 
- Colin Higgins Papers, ca. 1960-1987 -- https://calisphere-stage.cdlib.org/collections/28232 
- Collection of California Postcards -- https://calisphere-stage.cdlib.org/collections/28233 
- Ethnomusicology Archive: Photographic collection -- https://calisphere-stage.cdlib.org/collections/28254 
- Grot (Anton) Papers. Collection 956 -- https://calisphere-stage.cdlib.org/collections/28255 
- Aldous and Laura Huxley Papers -- https://calisphere-stage.cdlib.org/collections/156 
- Miriam Matthews Photograph Collection -- https://calisphere-stage.cdlib.org/collections/26899 
- Paul Monette Papers, 1945-1995 -- https://calisphere-stage.cdlib.org/collections/28183 
- Photograph album collection, circa 1850-1964 -- https://calisphere-stage.cdlib.org/collections/28184 
- Picture collection, 1890-1980s -- https://calisphere-stage.cdlib.org/collections/28185 
- Porter (Bern) Papers. Collection 639 --  https://calisphere-stage.cdlib.org/collections/28186 
- Rainbow Bridge -- https://calisphere-stage.cdlib.org/collections/28187 
- Raymond Chandler Papers, 1930-1959 -- https://calisphere-stage.cdlib.org/collections/28188 
- Red Bird, Oklahoma glass plate negatives -- https://calisphere-stage.cdlib.org/collections/28189 
- Richard and Dion Neutra Papers, 1925-1970 -- https://calisphere-stage.cdlib.org/collections/28190 
- Roberts (L. G. (Lawrence G.)) Papers -- https://calisphere-stage.cdlib.org/collections/28193 
- Ruth Eleanor McKee Papers, 1905-1972 -- https://calisphere-stage.cdlib.org/collections/28194 
- Packman (Ana B. de) Papers -- https://calisphere-stage.cdlib.org/collections/28256 
- Palmer Family Papers -- https://calisphere-stage.cdlib.org/collections/28257 
- Rochlin (Harriet) Collection of Photographs of Western Jewish Life -- https://calisphere-stage.cdlib.org/collections/28258 
- Robert D. Farquhar Architectural Drawings -- https://calisphere-stage.cdlib.org/collections/28192 
- Early Printed Books -- https://calisphere-stage.cdlib.org/collections/28277 
- UCLA East Asian Archaeology Corona Satellite Images Collection -- https://calisphere-stage.cdlib.org/collections/28278 

## Communications
- Freshdesk thread URL: https://help.oac.cdlib.org/a/tickets/138997

## Request type
[Select all that apply]
- [x] New collection harvest
- [ ] Re-harvest whole collection (on request)
- [ ] Re-harvest metadata only (on request)
- [ ] Scheduled recurring harvests
- [ ] Delete whole collection (remove from publication)
- [ ] Item record removals (remove from publication)
- [ ] OAC METS replacement
- [ ] Redirects needed
- [ ] Other

Notes:

## Harvesting request details
[copy/paste from webform request]

**Comment by christinklez** [comment]
Hi @gamontoya! T-Kay has approved all of these collections for publication.

Since we harvested these to -stage before the publication DAG was developed, we'll need to trigger the publication jobs from Airflow (and not Registry).

I went ahead and tracked down the version paths by locating the Airflow runs. These version paths are listed in the initial comments, above.

When you have a moment, would you be able to publish these through (by following steps outlined in "option 2") to production? And also, please feel free to update our notes! https://docs.google.com/document/d/1grOS3ifpi03Kj3CMd4sGtXbqf_ylkTqrNbkT6ZyRl6Q/edit#heading=h.y2brb7h13iqt

**Comment by gamontoya** [comment]
- [ ] [123661](https://registry.cdlib.org/admin/library_collection/collection/12661) - version path: 12661/vernacular_metadata_2024-05-15T21:56:57/mapped_metadata_2024-05-15T21:57:18/with_content_urls_2024-05-15T21:58:08
- [ ] [153](https://registry.cdlib.org/admin/library_collection/collection/153) - version path: 153/vernacular_metadata_2024-05-06T22:47:43/mapped_metadata_2024-05-06T22:52:54/with_content_urls_2024-05-06T22:54:10
