### ISSUE TITLE
UCB staff e-mail address compilation (for upcoming e-mail changes)

### ISSUE THREAD

**Issue by aturner** [ucldc/rikolti#1104]
- [x] OAC voro accounts (~43 library.berkeley.edu accounts)
- [x] CSphere Registry accounts (6 accounts)
- [x] Mailchimp
- [x] Freshdesk (63 library.berkeley.edu subscribers Contacts)

==

Per Kristen:
`UC Berkeley Library is removing their email accounts ending in @library.berkeley.edu (example: [username@library.berkeley.edu](mailto:username@library.berkeley.edu)) at the end of the year and creating new accounts ending in @berkeley.edu. NOTE: Some of the e-mails might not be a 1:1 change (example [old.username@library.berkeley.edu](mailto:old.username@library.berkeley.edu) might map to [new.username@berkeley.edu](mailto:new.username@berkeley.edu))
UCB wanted to confirm the impact this change has on CDL services. They would like to learn more about how this e-mail change might impact our listservs, slack, application notifications, logins across all services, and anything else that might be impacted by retiring these email addresses.`

**Comment by aturner** [comment]
Compilation spreadsheet in progress at https://docs.google.com/spreadsheets/d/19sgxKElj7qzBASKr3sQKdh-Ud9guT1qQI0DCSvDqxHk/edit?usp=sharing

**Comment by gamontoya** [comment]
@aturner I think we've zapped non-active users in all relevant apps
