### ISSUE TITLE
Audit existing mappers for bespoke date logic

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/rikolti#1113]

**Comment by amywieliczka** [comment]
Need to take a look at (expressed in legacy registry codes):

Confirmed date mapping logic doesn't include bespoke date parsing logic:
- ucd_json
- flickr_api
- yosemite_oai_dc

Still to check:
- ucsd_blacklight_dc
- burbank_islandora
- ucldc_nuxeo

Maybe we ETLed these? Marked as reviewed post mvp fixes in the spreadsheet. If we ETLed these, then we'll pick up any bespoke mapping logic when we revisit these mappers later and don't need to check them for this initial date enrichment:
- chico_oai_dc
- csu_sac_oai_dc

Pretty sure we ETLed these, so we'll pick up any bespoke date mapping logic when we migrate these mappers later and don't need to check them for this initial date enrichment:
- marc
- ucsf_solr
- cavpp_islandora
- ucb_bampfa_solr
- pastperfect_xml
- internet_archive

**Comment by christinklez** [comment]
A quick note that we harvested a Nuxeo collection yesterday/today and this collection's decade faceting & sort date functions look good! https://calisphere-stage.cdlib.org/collections/26713/

Looks like the bespoke date logic may be in place for Nuxeo?

**Comment by amywieliczka** [comment]
`ucsd_blacklight` is the only mapper that does some custom date processing, which Lucas already ported over. 🙏

**Comment by amywieliczka** [comment]
Moved to 'ready for review' just as a reminder for Monday's meeting re: good to go on reharvesting
