### ISSUE TITLE
Nuxeo `content_harvesting` error: `AttributeError: 'dict' object has no attribute 'decode'`

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#1122]
2 Nuxeo harvesting jobs reporting this error: `AttributeError: 'dict' object has no attribute 'decode'`
(I've only tried harvesting these 2 Nuxeo harvests so far. These both previously harvested to -stage successfully.)

Run ID: manual__2024-09-30T18:34:32+00:00
Error log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-09-30T18%3A34%3A32%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=0&num_runs=100
Registry ID: 28012

Run ID: manual__2024-10-01T22:10:57+00:00
Error log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-10-01T22%3A10%3A57%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&num_runs=100
Registry ID: 27594

**Comment by barbarahui** [comment]
@christinklez @gamontoya This should be fixed now.

**Comment by gamontoya** [comment]
@barbarahui Confirming that this is indeed fixed. Ran a Nuxeo collection successfully.
