### ISSUE TITLE
Generate ARK-to-local ID lists for Corona Public Library collections

### ISSUE THREAD

**Issue by gamontoya** [ucldc/rikolti#1162]
@gamontoya could you please generate the ARK-to-local ID lists for these 2 collections from Corona Public Library?

https://oac.cdlib.org/items/ark:/13030/kt3c60249v/
https://oac.cdlib.org/items/ark:/13030/kt5t1nd3bf/

Per https://docs.google.com/document/d/1Jf_6-kUn8lBqALuQ7K_r3SEyfi-4PW4cXqhA_vEdemQ/edit?tab=t.0#heading=h.4ekxxhmcdnfd

**Comment by gamontoya** [comment]
@aturner The two lists are attached. 

- [citrus_crate_label.txt](https://github.com/user-attachments/files/18066902/citrus_crate_label.txt)
- [shades_of_corona.txt](https://github.com/user-attachments/files/18066903/shades_of_corona.txt)

**Comment by aturner** [comment]
Thanks @gamontoya !
