### ISSUE TITLE
Create CONTENTdm_OAI_Mapper(OAIDublinCoreMapper)

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#143]
- [ ] ArcK_OAIMapper(CONTENTdm_OAI_Mapper)
- [ ] BlackGold_OAIMapper(CONTENTdm_OAI_Mapper)
- [ ] Califa_OAIMapper(CONTENTdm_OAI_Mapper)
- [ ] Chico_OAI_Mapper(CONTENTdm_OAI_Mapper)
- [ ] CVPL_CONTENTdm_OAI_Mapper(CONTENTdm_OAI_Mapper)
- [ ] CONTENTdm_OAI_Mapper_get_sound_thumbs(CONTENTdm_OAI_Mapper)
- [ ] CONTENTdm_OAI_Suppress_Description_Mapper(CONTENTdm_OAI_Mapper)
- [ ] CSU_DSpace_Mapper(CONTENTdm_OAI_Mapper)
- [ ] CSU_Sac_OAI_Mapper(CONTENTdm_OAI_Mapper)
- [ ] CSUDH_CONTENTdm_OAI_Mapper(CONTENTdm_OAI_Mapper)
- [ ] LAPL_OAIMapper(CONTENTdm_OAI_Mapper)
- [ ] Quartex_OAIMapper(CONTENTdm_OAI_Mapper)
- [ ] UCBTIND_OAIMapper(CONTENTdm_OAI_Mapper)
- [ ] USC_OAIMapper(CONTENTdm_OAI_Mapper)

**Comment by amywieliczka** [comment]
Deleting this issue - it wound up getting broken out into separate issues that Lucas at CIC developed.
