### ISSUE TITLE
Update Rikolti harvesting specimen sheet with some large collections, collections with large files, lots of components

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/rikolti#149]

**Comment by aturner** [comment]
Updated https://docs.google.com/spreadsheets/d/1sZK22O37xnLRkBXUvd6Sye6bKKK9LgTcuUxWAb_NjR8/edit#gid=765151772 with examples (two new tabs -- one for collections with large files, one for collections with lots of components)
