### ISSUE TITLE
Finalize contracting with CIC, in coordination with CDL Business Services and UCOP Procurements

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#172]

**Comment by aturner** [comment]
Finalized scope of work proposal with CIC: https://drive.google.com/file/d/1a5dctyBcNPlNdfEjuXLAv7h4TfLzdllp/view?usp=sharing .

**Comment by aturner** [comment]
In-process of securing OP HR & Subdivision Head approvals on the contract
