### ISSUE TITLE
Propose models for data fidelity targets, sample record criteria, and fetcher/mapper integration tests

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#176]

**Comment by aturner** [comment]
Notes on p. 2-3 at https://docs.google.com/document/d/1g1L5I_6sNwjLP5fjYigeyqrSXDvf4AW4w-VCE64XKIo/edit

**Comment by aturner** [comment]
Draft documentation: https://docs.google.com/document/d/1Efy0kgjg-SahvvFCuVw3ZH5H5-qPWtvM4q9wnnFIUI4/edit?usp=sharing

**Comment by christinklez** [comment]
@amywieliczka @barbarahui requesting review

**Comment by barbarahui** [comment]
@aturner @christinklez I made some clarifying edits to the document and added some comments/questions.

**Comment by amywieliczka** [comment]
@barbarahui @aturner @christinklez I responded to a few comments in the document, but I think these are all a bit inconsequential to the document itself. I also added a comment regarding the characterization of these requirements. Not sure whose call it is to make, but that's my own two cents. I think the doc looks good, overall, though.
