### ISSUE TITLE
Prioritize fetcher and mappers to migrate

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#178]

**Comment by aturner** [comment]
Mappers and proposed priority: https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1733241055

**Comment by aturner** [comment]
To incorporate fetchers into spreadsheet

**Comment by christinklez** [comment]
Prepared a proposed fetcher prioritization here: https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=305207230

The queue is based on the mapper prioritization list (same sheet, different tab).

@amywieliczka @barbarahui -- just a heads up!
