### ISSUE TITLE
Establish CIC project tracking method

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#180]

**Comment by christinklez** [comment]
Document ready for review: https://docs.google.com/document/d/1KBG6e59uR7UgLEGIXG4UypjLWicGwdDxx2CdIAgsMzM/edit#

**Comment by christinklez** [comment]
@amywieliczka @barbarahui ready for your review.

**Comment by barbarahui** [comment]
@christinklez @aturner Looks good to me. I made one comment.

**Comment by amywieliczka** [comment]
@christinklez @aturner looks good to me as well. I made a suggestion regarding details to add to any pull requests in order for the PR to show up in the project board. I also made one a comment.

**Comment by christinklez** [comment]
@aturner made some tweaks to address reviewer comments. Left those tweaks as suggestions so that you can find them easily. Thanks!
