### ISSUE TITLE
Understand fetcher & mapper associations

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#187]

**Comment by barbarahui** [comment]
Added new section to the "Analysis of Existing Infrastructure" wiki page: https://github.com/ucldc/rikolti/wiki/Analysis-of-Existing-Infrastructure#relationship-of-fetchers-to-mappers

**Comment by barbarahui** [comment]
@amywieliczka @christinklez @aturner I updated the script to use Amy's `published` filter, and now the output makes more sense.

**Comment by christinklez** [comment]
Adrian and I reviewed this, and think the list looks great! Thank you @barbarahui !
