### ISSUE TITLE
Discuss and document the formal Calisphere object naming scheme (metadata, files)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#201]

**Comment by amywieliczka** [comment]
https://jamboard.google.com/d/1Q-KNKQMHO4_CP_3vQ5C7-Odo36Fh7fcCTrSHax2i694/viewer

**Comment by amywieliczka** [comment]
@christinklez @aturner should this be documented anywhere else right now, or can we close this issue?

**Comment by amywieliczka** [comment]
Add the above to a wiki page.
