### ISSUE TITLE
Finalize (and publish)data fidelity/acceptance criteria documentation

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#205]

**Comment by aturner** [comment]
Draft: https://docs.google.com/document/d/1Efy0kgjg-SahvvFCuVw3ZH5H5-qPWtvM4q9wnnFIUI4/edit

To incorporate into https://github.com/ucldc/rikolti/wiki/Testing

**Comment by aturner** [comment]
@amywieliczka for review

**Comment by gamontoya** [comment]
@amywieliczka @aturner The Testing doc looks good. When should we come up with a list of sample collections to test against?
