### ISSUE TITLE
Add sample collections to mapper cards / identify any particular collections that need special care and should be tested

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#206]
Identify any particular collections that need special care and should be tested (finicky, tricky, large, etc.); list that out somewhere. Timing dependency is before a specific mapper is developed (so that those collections can be tested)

**Comment by gamontoya** [comment]
@aturner @christinklez Can you elaborate on what "special care" means? Do you mean things like:

- large worker required for harvesting
- large working required for synching to prod
- lacks type of resource for all objects
- ??

**Comment by christinklez** [comment]
@gamontoya I believe @amywieliczka characterized it as collections that have been known to fail (or run into problems) in the current harvester, such as Klein.

**Comment by gamontoya** [comment]
@christinklez I can track down my notes to see if there are others.

**Comment by christinklez** [comment]
@amywieliczka will help us generate a list of collections associated with particular mappers.

**Comment by christinklez** [comment]
This work is happening as part of #400
