### ISSUE TITLE
Fetcher: SLR

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#263]
Mappers dependent on this fetcher:
- ~~UCLASolrDCMapper(DublinCoreMapper)~~ (obsolete)
- UCSDBlacklightDCMapper(DublinCoreMapper) #265 
***
- Some general links to know:
  - [Development contribution process](https://github.com/ucldc/rikolti#development-contribution-process)
  - ["CIC all tasks" list view](https://github.com/orgs/ucldc/projects/1/views/20)
  - ["CIC current sprint" status view](https://github.com/orgs/ucldc/projects/1/views/7)

- Specific to this fetcher:
  - List of collections, by fetcher type: https://registry.cdlib.org/?harvest_type=SLR
***
- Rikolti MVP project board cheat sheet:
  - Please @ CDL developers liberally, in the comments.
  - When **picking up an "issue,"** please indicate: 
    - a) Assignees: self assign; 
    - b) Sprint: select the current sprint cycle; 
    - c) Date started: indicate the start date -- see right side fields
  - CIC developers will likely need to **create PRs** (and possibly additional issues). When doing so, please also indicate the following: 
    - a) Repository: Rikolti; 
    - b) Milestone: "4 CIC work" (these details are required in order for them to surface in the Rikolti MVP project board); and 
    - c) link the PR to the associated issue.
  - When **requesting review,** please:  
    - a) include a comment & @ CDL developers; and 
    - b) Date delivered: indicate the date delivered (field on the right)

**Comment by lthurston** [comment]
@aturner @christinklez I'm getting 404s for the Blacklight endpoint, which is the same URL for all of the collections that rely on the Solr mapper (excluding the obsolete UCLASolrDC).

Here's the URL: [http://lib-metadata.ucsd.edu/solr/blacklight/](http://lib-metadata.ucsd.edu/solr/blacklight/) (getting a 404 for https:// as well)

Here's the list of collections for this fetcher: [https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&harvest_type=slr](https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&harvest_type=slr)

Also, there are several flavors of Solr fetchers housed in the legacy Solr mapper module (https://github.com/ucldc/harvester/blob/master/harvester/fetcher/solr_fetcher.py), but only RequestsSolrFetcher has the signature I'd expect in the __init__() method for a mapper that relies on the registry. Once I have access to the endpoint, that's the legacy mapper I'll use as a guide.

**Comment by christinklez** [comment]
@lthurston it looks like it needs the collection tesim query in order to work.

In the registry entry, if you go into a particular collection, you will see a "harvesting extra data" field. 
For example, this collection entry: https://registry.cdlib.org/27756/100-island-challenge-collection-the-goal-of-this-s/
includes this: `collections_tesim:bb1610330b`

Appending to the endpoint should look like:
https://lib-metadata.ucsd.edu/solr/blacklight/select?q=collections_tesim:bb1610330b

As a side note, this query might return everything (but unsure if it will sort by collection): http://lib-metadata.ucsd.edu/solr/blacklight/select?q=*:*&fq=type_tesim:Collection

Feel free to let me know if you have any questions. Thanks!

**Comment by lthurston** [comment]
@christinklez This is a weird one in the registry:

```
{
  collection_id: 354,
  harvest_data: {
    harvest_extra_data: "RELS_EXT_isMemberOfCollection_uri_ms:info\:fedora/adamspapers\:*",
    url: "https://dl.library.ucla.edu/solr"
  },
  harvest_type: "solr",
  mapper_type: "ucla_solr_dc",
  metadata_density_score: null,
  metadata_density_score_last_updated: null,
  ready_for_publication: true,
  resource_uri: "/api/v1/rikoltifetcher/354/",
  rikolti_mapper_type: "ucla_solr.ucla_solr",
  solr_count: 478,
  solr_last_updated: "2022-11-23T12:43:15.939757"
},
```

The legacy fetcher expects the `harvest_extra_data` string in one of two formats. The first is the one we see with the `tesim` values, and the other is defined like this:

`q=<query>&header=<name>:<value>&header=<name>:<value>`

Do you have any sense as to what's going on with this collection, specifically, how I'm supposed to synthesize a request URL based on the `harvest_extra_data` and `url` values?

🤞 that it's not so obvious as last time.

**Comment by christinklez** [comment]
@lthurston Thanks for bringing this up! That is for a UCLA collection, and this UCLA mapper is obsolete. No worries if the UCLA collections don't fetch/map. Thanks!

**Comment by aturner** [comment]
Game plan is to conduct test harvesting against UC San Diego Library's Solr 8 starting on 5/30. UCSD will toggle the index at that time

**Comment by aturner** [comment]
@lthurston is the UCSD Solr fetcher/mapper work still in-process? Thanks!

**Comment by lthurston** [comment]
Not really, but it is awaiting some PRs that are in front of it.
