### ISSUE TITLE
Fetcher: FLK

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#272]
Mappers dependent on this fetcher:
- FlickrMapper(Mapper)
- FlickrSDASMMapper(FlickrMapper)
- FlickrSPPLMapper(FlickrMapper)
***
- Some general links to know:
  - [Development contribution process](https://github.com/ucldc/rikolti#development-contribution-process)
  - ["CIC all tasks" list view](https://github.com/orgs/ucldc/projects/1/views/20)
  - ["CIC current sprint" status view](https://github.com/orgs/ucldc/projects/1/views/7)

- Specific to this fetcher:
  - List of collections, by fetcher type: https://registry.cdlib.org/?harvest_type=FLK
***
- Rikolti MVP project board cheat sheet:
  - Please @ CDL developers liberally, in the comments.
  - When **picking up an "issue,"** please indicate: 
    - a) Assignees: self assign; 
    - b) Sprint: select the current sprint cycle; 
    - c) Date started: indicate the start date -- see right side fields
  - CIC developers will likely need to **create PRs** (and possibly additional issues). When doing so, please also indicate the following: 
    - a) Repository: Rikolti; 
    - b) Milestone: "4 CIC work" (these details are required in order for them to surface in the Rikolti MVP project board); and 
    - c) link the PR to the associated issue.
  - When **requesting review,** please:  
    - a) include a comment & @ CDL developers; and 
    - b) Date delivered: indicate the date delivered (field on the right)

**Comment by lthurston** [comment]
@aturner @christinklez Looks like I need an API key for this one. Is that something you can grab for me?

**Comment by lthurston** [comment]
Sorry to continue to pepper you with questions and comments, but I wanted to note that this fetcher, like PRA, also invokes "subrequests" and will store the vernacular data in a format of its own design. I think I can still proceed regardless, and will think of this in terms of processing one record at a time. That way, we have something that can be easily reworked to write pages or records, or individual records in a single file.

**Comment by aturner** [comment]
@lthurston looking back at notes we have re: the Flickr mappers, I'm not immediately seeing anything re: recording or using keys to use the API. It sounds like you aren't able to fetch the records, without a key?

In Registry, we have specific identifiers recorded for each collection (in "Harvest extra data"), which is presumably used to subset the results from Flickr by collection (https://docs.google.com/spreadsheets/d/1ACngux07b270kdEI6bVAQvL47LwycJZgodpMZSOzv94/edit?usp=sharing) -- does that have any bearing or help with the fetching?
