### ISSUE TITLE
DPLA harvesting: email request to meet

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#280]
Draft messaging and discussion points, for conversation with DPLA: https://docs.google.com/document/d/12eMmxx3wDtJZm_7sJQAOh0FdjzKivhYw2N94eBYyG60/edit?usp=sharing

**Comment by aturner** [comment]
For review by @lschiff

**Comment by lschiff** [comment]
Made comments and suggestions.

**Comment by christinklez** [comment]
@aturner feel free to review the updates when you have a moment, thanks! Let's also plan to discuss when we'd like to send this out.

**Comment by christinklez** [comment]
Emailed!
