### ISSUE TITLE
Calisphere frontend updates: QA plan for ES transition

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#281]
QA plan (draft) at https://docs.google.com/spreadsheets/d/12oailNshmaaSabXwaMupniZreR-VCZUmwSpaDEZlFsg/edit?usp=sharing

**Comment by lschiff** [comment]
Just reviewed this.  It looks very thorough!  I added one suggestion about testing search from another page in addition to the homepage.  We should also do some testing using a few different browsers--maybe distribute it a bit across some volunteer testers.  We might not need to test everything on every browser, but some sampling at least would be good.

**Comment by christinklez** [comment]
Thank you! Made some tweaks based on Lisa's suggestions (added in various "check search" tasks). Also thinking that once we firm this checklist up, it can be used as a template for the various browsers that need to be tested (and set up as several tabs in the sheet).

**Comment by christinklez** [comment]
@aturner feel free to review the updates when you have a moment, thanks!

**Comment by aturner** [comment]
@christinklez this looks good to go, done deal!
