### ISSUE TITLE
[ongoing] Review of CIC mapper prioritization and queue + endpoint troubleshooting

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#295]
Mapper queue: https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1733241055

**Comment by aturner** [comment]
Endpoint troubleshooting in-process:

* San Diego Air and Space Museum, South Pasadena Public Library, Sierra Madre Public Library - Flickr (flickr.flickr, flickr.sdasm, flickr.sppl)
* Oakland Public Library - ATOM (cmis_atom.cmis_atom)
* Oakland Public Library - direct API (preservica.preservica) 
* Los Angeles Public Library - Rescarta (lapl_26096.lapl_26096)

**Comment by aturner** [comment]
UCD Collection 8 (UCD) has a handful of items without an `identifier` attribute. They all have an `@id` attribute, however, which Lucas is using for the legacy couch db id in the absence of an ark. The @id values below. 

The objects aren't in CSphere. They appear to have minimal metadata (e.g., https://digital.ucdavis.edu/collection/eastman/D-051/000/414). Are these intentionally not ready for publication/harvesting? To check with UCD:

/collection/eastman/D-051/000/425
/collection/eastman/D-051/B-8/B-8773
/collection/eastman/D-051/D-9/D-948
/collection/eastman/D-051/000/933
/collection/eastman/D-051/000/495
/collection/eastman/D-051/000/941
/collection/eastman/D-051/B-1/B-1878
/collection/eastman/D-051/000/421
/collection/eastman/D-051/000/415
/collection/eastman/D-051/000/419
/collection/eastman/D-051/000/422
/collection/eastman/D-051/B-2/B-249A
/collection/eastman/D-051/000/972
/collection/eastman/D-051/000/417
/collection/eastman/D-051/000/418
/collection/eastman/D-051/000/955
/collection/eastman/D-051/000/426
/collection/eastman/D-051/000/420
/collection/eastman/D-051/000/950
/collection/eastman/D-051/B-1/B-1717
/collection/eastman/D-051/000/413
/collection/eastman/D-051/000/2018
/collection/eastman/D-051/000/945
/collection/eastman/D-051/000/943
/collection/eastman/D-051/000/658
/collection/eastman/D-051/B-2/B-249B
/collection/eastman/D-051/Misc/bsktslr
/collection/eastman/D-051/000/953
/collection/eastman/D-051/B-2/B-246-B
/collection/eastman/D-051/000/414
/collection/eastman/D-051/000/105
/collection/eastman/D-051/000/991
/collection/eastman/D-051/000/969
/collection/eastman/D-051/000/974
/collection/eastman/D-051/000/424
/collection/eastman/D-051/000/423
/collection/eastman/D-051/000/461

**Comment by christinklez** [comment]
@aturner just an fyi that I've updated the [mappers queue spreadsheet](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1733241055) to reflect the updated priorities discussed today:
- bump up MRC/marc/pymarc/tind & GLBT HS Islandora mapper -- see rows 37-40
- deprioritize all other mappers/fetchers (plan to ETL the collections using these mappers)

Along those lines, I've also updated the [collections to ETL spreadsheet](https://docs.google.com/spreadsheets/d/1zSV75qNlHFuk-awet2LexKBnKRp8gJ4fo2GKu_jSgFM/edit#gid=627154438) and added a new tab/bucket for mappers that will be prioritized post the MVP cutover.
