### ISSUE TITLE
Establish a framework and protocol to review reports and provide feedback

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#297]
Begin to review data fidelity tests/validation reports for each completed mapper; feedback to CIC or sign-off

While reviewing the first (set?) validation report, establish a framework and protocol to test and provide feedback.

While reviewing the validation reports, identify whether a summary data validation report of each collection will be useful. (If so, identify specific criteria of such a summary, such as: extent count update (X items added/dropped); X items metadata changed)

**Comment by aturner** [comment]
Plan is to provide feedback on specific mapper issues to CIC using the "Sample collections VALIDATE" tab on the main spreadsheet at https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640 . Will likely refine this a bit further, once we are fully underway with reviewing mappers and reporting issues to CIC -- but done deal for now.
