### ISSUE TITLE
Communication plan: Prepare a migration FAQ page to post on Freshdesk

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#310]
Draft here: https://docs.google.com/document/d/1kP1cL1E7KpcKBuXKkWkqJXqW8MDjI1CaU78LXRTNs6g/edit#heading=h.vp1zqxptvwaj

**Comment by christinklez** [comment]
@lschiff requesting your review, specifically pages 1-9 only. This includes our overall key communication points/goals, communication timeline, and a Rikolti migration FAQ that will be posted on Freshdesk. Thanks!

**Comment by lschiff** [comment]
@christinklez By when do you need this?

**Comment by christinklez** [comment]
@lschiff Our goal is to have this solid by the end of this sprint (March 10). If you're able to review by the end of Friday, that would be super appreciated! Please do feel free to let me know if it works better for you to get to next week. Also happy to do a quick Zoom huddle for any questions. Thanks!

**Comment by lschiff** [comment]
Hi @christinklez Just took a pass at this and left comments, questions, and some suggested edits.  Let me know if you have any questions.  Note that I won't have any time free for this until this Friday.
