### ISSUE TITLE
ID generation: Investigate logic for Rikolti ID generation, and understand the variance issue between Solr ID and Rikolti ID

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#322]

**Comment by amywieliczka** [comment]
@barbarahui and I met and discussed the Rikolti ID generation. We think we have managed to recreate the logic from the existing mapper, and hopefully can manage to generate Rikolti IDs that are == to the existing Solr IDs. We're going to lean on the validation report to catch any discrepancies and will investigate further on a case-by-case basis. If there are too many cases, then we will revisit this issue at a systemic level.
