### ISSUE TITLE
Strategy for revisting OAI-PMH harvesting discussion with Pacific Rim Library (PRL)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#329]
PRL messaging / meeting key points: https://docs.google.com/document/d/1c3OrJOZCf6RAJqki1TPb6xleHhKS8EJ4q4F_HISynKI/edit?usp=sharing

**Comment by aturner** [comment]
@christinklez moved to in-progress, got a draft message going -- putting forward some initial questions, also proposing a meeting

**Comment by aturner** [comment]
Draft message / discussion points: https://docs.google.com/document/d/1c3OrJOZCf6RAJqki1TPb6xleHhKS8EJ4q4F_HISynKI/edit?usp=sharing

**Comment by christinklez** [comment]
Discussed that we would like to propose a meeting with PRL to strategize if there might be alternatives to OAI-PMH harvesting.
Also, here's this link: https://github.com/ucldc/oaiapp
