### ISSUE TITLE
LAPL_26096Mapper(DublinCoreMapper)--NOT DOING

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#339]
- Some general links to know:
  - [Development contribution process](https://github.com/ucldc/rikolti#development-contribution-process)
  - ["CIC all tasks" list view](https://github.com/orgs/ucldc/projects/1/views/20)
  - ["CIC current sprint" status view](https://github.com/orgs/ucldc/projects/1/views/7)

- Specific to this mapper:
  - List of collections, by mapper type: ~~https://registry.cdlib.org/?mapper_type=omeka~~
  - https://registry.cdlib.org/?mapper_type=lapl_26096
  - Endpoint:
    - http://173.196.26.121:8080/oai/provider
  
***
- Rikolti MVP project board cheat sheet:
  - Please @ CDL developers liberally, in the comments.
  - When **picking up an "issue,"** please indicate: 
    - a) Assignees: self assign; 
    - b) Sprint: select the current sprint cycle; 
    - c) Date started: indicate the start date -- see right side fields
  - CIC developers will likely need to **create PRs** (and possibly additional issues). When doing so, please also indicate the following: 
    - a) Repository: Rikolti; 
    - b) Milestone: "4 CIC work" (these details are required in order for them to surface in the Rikolti MVP project board); and 
    - c) link the PR to the associated issue.
  - When **requesting review,** please:  
    - a) include a comment & @ CDL developers; and 
    - b) Date delivered: indicate the date delivered (field on the right)

**Comment by lthurston** [comment]
I suspect that this is the correct URL: `https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&mapper_type=lapl_26096`

**Comment by lthurston** [comment]
@aturner Any word on this one? Looks like the endpoint is timing out: http://173.196.26.121:8080/oai/provider

**Comment by aturner** [comment]
@lthurston sorry for the delay, we're still holding for Los Angeles Public Library to re-establish the OAI-PMH feed; pinged them again, and will be in touch re: the status. Thanks!
