### ISSUE TITLE
UCBTIND_MARCMapper(PyMarcMapper)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#363]
Mapper dependency: PyMARCMapper #362   
***
- Some general links to know:
  - [Development contribution process](https://github.com/ucldc/rikolti#development-contribution-process)
  - ["CIC all tasks" list view](https://github.com/orgs/ucldc/projects/1/views/20)
  - ["CIC current sprint" status view](https://github.com/orgs/ucldc/projects/1/views/7)

- Specific to this mapper:
  - List of collections, by mapper type: https://registry.cdlib.org/?mapper_type=ucb_tind_marc
  - Endpoint: https://digicoll.lib.berkeley.edu/oai2d
***
- Rikolti MVP project board cheat sheet:
  - Please @ CDL developers liberally, in the comments.
  - When **picking up an "issue,"** please indicate: 
    - a) Assignees: self assign; 
    - b) Sprint: select the current sprint cycle; 
    - c) Date started: indicate the start date -- see right side fields
  - CIC developers will likely need to **create PRs** (and possibly additional issues). When doing so, please also indicate the following: 
    - a) Repository: Rikolti; 
    - b) Milestone: "4 CIC work" (these details are required in order for them to surface in the Rikolti MVP project board); and 
    - c) link the PR to the associated issue.
  - When **requesting review,** please:  
    - a) include a comment & @ CDL developers; and 
    - b) Date delivered: indicate the date delivered (field on the right)

**Comment by christinklez** [comment]
TIND validation reports: https://drive.google.com/drive/folders/1AWpJn9QTCrZaiQ6GjVowFuBR6BLn5oTw

**Comment by christinklez** [comment]
Reviewing older Rikolti notes, it looks like we had summarized the TIND data validation issues & requested fixes here:
https://docs.google.com/document/d/1g1L5I_6sNwjLP5fjYigeyqrSXDvf4AW4w-VCE64XKIo/edit?pli=1&tab=t.0#heading=h.3nhco2rvvf9d

It looks like we had also asked Lucas to work on some "pairing" and "deduplication" work, specifically as related to Sugoroku (27435). Summary of our request here: https://docs.google.com/document/d/1g1L5I_6sNwjLP5fjYigeyqrSXDvf4AW4w-VCE64XKIo/edit?pli=1&tab=t.0#heading=h.vuz0embmudcp

I'm not exactly sure on the state of that work Lucas did. Perhaps before digging back into TIND, would it be possible to generate a fresh validation report for 27435?

**Comment by barbarahui** [comment]
@christinklez I created a fresh validation report and put in on drive: https://drive.google.com/drive/folders/1-ZKZzOW8pAbcBmpgqYFIHOIuQtR-GTYI

**Comment by barbarahui** [comment]
New validation report after working on some of the issues:

[validation_2024-10-26T00:37:04.csv](https://github.com/user-attachments/files/17546308/validation_2024-10-26T00.37.04.csv)

**Comment by christinklez** [comment]
Thanks so much, @barbarahui! Notes are in column E of this report: https://docs.google.com/spreadsheets/d/1U23IgV7fGCeujWaHYjRhA03jv8LTW5PyxSMv5C8KSUE/edit?gid=1480107829#gid=1480107829

General notes:
- Sugoroku has translations and is depending on the 880 fields to pair the Romanized characters with the Japanese characters.
- UCB is using the subfield codes to pair these, but sometimes seemingly inconsistently.

**First request: Undo the deduplication.**
- We'd like to undo the deduplication we requested from Lucas. Now that the 2xx and 880 pairing seems to be in working order, we believe we want any intended duplication that comes from the source data.
- `alternative title`: row 387 - we're seeing that Rikolti is dropping 246/880-04. This is likely because we asked Lucas to de-duplicate values. We're interested in seeing how the pairing works once the deduplication is dropped.

**Second request: 2xx and 880 pairing & sequence**
- First, pair the 2xx fields with the 880 fields by `<marc:subfield code="6" >`
- Then, further pair by `<marc:subfield code="a" >` or `<marc:subfield code="b" >` or `<marc:subfield code="c" >`, as they exist.
   - `title`: row 401 - Request to pair by 245 and 880 fields; this row is also dropping one of the 880 values.
   - `publisher`: row 11 - the 260 and 880 subfields do not seem to be pairing, and this row is also dropping one of the 880 values. 
   - `date`: row 9 - the 260-c and 880-c subfields do not seem to be pairing. Note that in a previous iterations, these were pairing.
   - `alternative title`: row 387 - 
- Additionally, sometimes there are multiple `<marc:subfield code="a" >`'s listed within a given 2xx or 880. We would like to respect the order. 
   - `publisher`: see row 67 - this example has two `<marc:subfield code="a" >`'s - and these should be paired in the sequence displayed.

**Acceptable discrepancies: No changes requested**
- url_item: http vs https
- extent: listified values!
- is_shown_by & is_shown_at: we are getting URLs
- subject: likely source data drift
- facet_decade: we think this is a legacy Solr value; this is not in the source data

**Comment by barbarahui** [comment]
New validation report on google drive: https://drive.google.com/drive/folders/1wPZeUH-uzqxhdEgX6gSQmV9QSAj2Y6yY

**Comment by christinklez** [comment]
Hi @barbarahui! The Sugoroku report looks great! The data looks even better than the legacy mapper.

When you have a moment, would you be able to get this mapper into main? We'll review some of the other collection reports to verify. (Or feel free to let us know if it's easier to do that before merging the mapper into main.)

Thank you so much!!
