### ISSUE TITLE
Stabilize data validation code with CIC / PR review

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#391]
Reports: https://drive.google.com/drive/u/0/folders/1AgDPsz6oyDhsfgRuLyjomaXYgE1sPLNT

- [ ] Run the validator locally, just to generate some sample reports
- [ ] Evaluate the initial reports with some sample collections
- [ ] ...

**Comment by amywieliczka** [comment]
https://github.com/ucldc/rikolti/pull/421
