### ISSUE TITLE
Identify whether a summary data validation report of each collection will be useful; if so, include specific criteria

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#401]
[While reviewing available validation reports] Identify whether a summary data validation report of each collection will be useful. (If so, indicate specific criteria, such as: extent count update (X items added/dropped); X items metadata changed; etc.)

**Comment by aturner** [comment]
Draft notes in-progress at https://docs.google.com/document/d/1Q5-FXGikY9_EH5xROT7-U0OdUZW3PIx6SEBTsi3i3Qw/edit?usp=sharing

**Comment by aturner** [comment]
Proposed specific update to data validation report summarized at https://github.com/ucldc/rikolti/issues/412

**Comment by christinklez** [comment]
Discussed the proposed summary reports. While these will be useful, they may not fit easily within the existing validator reporting framework. These proposed reports may be reconsidered as part of the workflow management system reporting.
