### ISSUE TITLE
Amy/Barbara pair up and explore Temporal and Airflow together; update the rubric

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#422]
In working together on Airlfow, there are a few issues that should be explored:

- working local dev environment with actual http requests in python
- How to run multiple instances of the same workflow simulatenously
- How to get details of a workflow run filtered by a paramter provided to the workflow (in this case, a collection ID)
  -  can this be done in the UI?
  - Could this be done with the API?
  - Maybe after each run we push run details to a separate datastore just for this purpose?
- fan out of multiple parallel tasks in a single workflow, parallel mapping of fetched results pages. [Dynamic Task Mapping](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dynamic-task-mapping.html#mapping-over-multiple-parameters) might be useful. Other path is to move

**Comment by amywieliczka** [comment]
Regarding running multiple instances of the same workflow simultaneously: 
- application level configuration [max_active_runs_per_dag](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#max-active-runs-per-dag) 
- dag level configuration [max_active_runs](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/dag/index.html#airflow.models.dag.dag)
Next, I'll create a parameterized dag and run multiple at once.

**Comment by christinklez** [comment]
Link to rubric: https://docs.google.com/spreadsheets/d/1u6YZDZKYfj-XZnXa2OfWqxQd3H4Mli3f_EC3eQXrdKI/edit#gid=0

**Comment by amywieliczka** [comment]
The Airflow API specifies a [dagRuns endpoint](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag_runs) that is dag-specific: `/api/v1/dags/<harvest_collections>/dagRuns` lists all dagRuns and their configuration, for example: 

```json
{
      "conf": {
        "collection_ids": [
          "20",
          "22",
          "230"
        ]
      },
      "dag_id": "harvest_collections",
      "dag_run_id": "manual__2023-05-26T22:02:03+00:00",
      "data_interval_end": "2023-05-26T22:02:03+00:00",
      "data_interval_start": "2023-05-26T22:02:03+00:00",
      "end_date": "2023-05-26T22:02:37.406406+00:00",
      "execution_date": "2023-05-26T22:02:03+00:00",
      "external_trigger": true,
      "last_scheduling_decision": "2023-05-26T22:02:37.402582+00:00",
      "logical_date": "2023-05-26T22:02:03+00:00",
      "note": null,
      "run_type": "manual",
      "start_date": "2023-05-26T22:02:16.726055+00:00",
      "state": "success"
}
```

However, this endpoint does not allow filtering by dag run conf, and is dag-specific - it would not be able to answer the question: "tell me about all dag runs on collection 230" and is limited to "tell me about all harvest collection dag runs on collection 230". 

There is also a [batch list DAG runs](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_dag_runs_batch) that is not dag-specific, and therefore could "tell me about all dag runs" but it still does not allow for filtering by dag run configuration, ie "...on collection 230". 

It looks like there has been issue with the DAG runs conf filter. This issue, reported in Feb 2021: "Search in 'DAG Runs' crashed with 'Conf' filter" (https://github.com/apache/airflow/issues/14374) resulted in "Remove 'conf' from search_columns in DagRun View" (https://github.com/apache/airflow/pull/15099) in late March of 2021. I've not found any plans to fix filtering by `conf` back to the Airflow UI or really any mention of it at all vis-à-vis the REST API, excepting the POST request to trigger a new DAG run (which accepts a payload including `conf` data). 

It does seem impossible to filter by DAG Run configuration in the UI and the API. 😢



One alternate solution would be to create an Airflow DAG that runs at a regular interval (for example, every hour). It would send a POST to the Airflow API at `/api/v1/dags/~/dagRuns/list` with a payload `{"start_date_gte": <now - 1 hour>}` for all DAG Runs started in the past hour, and would then send a POST to a new registry endpoint to create a new DAG Run in the registry for each DAG Run in airflow. Then we could write a view in the registry to filter DAG Runs by their `conf`. This would involve:
- building a DAG Run model in the Registry database that is linked to Collection Ids
- updating our Registry API to accept Create and Update POST requests
- establishing an API-specific authentication mechanism
- navigating auth-required API calls around the Shibboleth authentication mechanism used for the Registry UI

**Comment by amywieliczka** [comment]
### ✅🆗 Dynamic Task Mapping

#### ✅ Modeling dynamic tasks of calculable length
Ex: running a "map page" task for all pages found in a given folder. `map_shepherd`, below, calculates dynamic task length. 

```python
@task
def map_page(collection_id, page):
    print(f"[{collection_id}]: mapping page {page}")
    return f"{page}-processed"

@task
def map_shepherd(collection_id):
    print(f"[{collection_id}]: get pages for mapping")
    return [i for i in range(int(random()*10))]

@dag(schedule=None, start_date=datetime(2022, 4, 2), tags=["rikolti"])
def rikolti_map():
    fetched_pages = map_shepherd(26697)
    mapped_pages = map_page.partial(collection_id=26697).expand(page=fetched_pages)

rikolti_map()
```

#### ❌✴️ Modeling dynamic tasks of unknown length
Ex: running a "fetch page" task until "fetch page" returns False (ie: tells us there are no more pages to fetch). This is not possible! However, there is a very reasonable workaround! 

```python
@task
def fetch_page_and_next(collection_id, page):
    print(f"[{collection_id}]: fetched page {page}")

    total_pages = int(random()*10)
    if page+1 < total_pages:
        return page+1
    else:
        return None

@dag(schedule=None, start_date=datetime(2022, 4, 2), tags=["rikolti"])
def failed_dag_import():
    next_page = fetch_page_and_next(26697, 0)
    while next_page:
         next_page = fetch_page_and_next(26697, next_page)

failed_dag_import()

def page_generator(collection_id):
    total_pages = int(random()*10)
    for page in range(0, total_pages):
        yield page

@task
def fetch_page(collection_id, page):
    print(f"[{collection_id}]: fetched page {page}")

@dag(schedule=None, start_date=datetime(2022, 4, 2), tags=["rikolti"])
def failed_expand_param_type():
    fetch_page.partial(26697).expand(page=page_generator(26697))

failed_expand_param_type()
```

Workaround:

```python
# Note: this is not a task now
def fetch_page_and_next(collection_id, page):
    print(f"[{collection_id}]: fetched page {page}")

    total_pages = int(random()*10)
    if page+1 < total_pages:
        return page+1
    else:
        return None

@task
def fetch_collection(collection_id, page_number=0):
    print(f"[{collection_id}]: start fetching pages")
    next_page = fetch_page_and_next(collection_id, 0)
    total_pages = 1

    while next_page:
        next_page = fetch_page_and_next(collection_id, next_page)
        total_pages += 1

    print(f"[{collection_id}]: fetched {total_pages} total pages")
    return total_pages

@dag(schedule=None, start_date=datetime(2022, 4, 2), tags=["rikolti"])
def rikolti_fetch():
    fetch_collection(26697)

rikolti_fetch()
```

🆗 Controlling dynamic task execution (ex: throttling, parallelization)
There are options to throttle within Airflow configuration globally (set Airflow config `parallelism=#`), as well as options to throttle specific DAGs (set DAG config `concurrency=#`), but there does not seem to be specific control of dynamic task execution. For our application, we don't care overly much about throttling mapping, but we do care about throttling content harvesting - we don't want to hammer an institution for all their thumbnails all at once. Even sending 100 different requests for 100 different images all at once could get onerous for an institution's server. 

✅ Modeling [dynamic tasks with classic style operators](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dynamic-task-mapping.html#mapping-with-non-taskflow-operators) (not TaskFlow) (ex: with a DockerOperator)
