### ISSUE TITLE
Generate validation reports for sample collections

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#425]

**Comment by aturner** [comment]
List of sample collections for all fetchers/mappers at https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640 . For the initial sampler, let's start with the Nuxeo ones -- that'll get us going with QA review and analysis, for the time being
