### ISSUE TITLE
Review data fidelity tests/validation reports for each completed mapper; feedback to CIC or sign-off

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#427]
New validations are here: https://drive.google.com/drive/u/1/folders/1AgDPsz6oyDhsfgRuLyjomaXYgE1sPLNT

It’s only the first 20 collections in Chapman (rather than all 48), but the others are complete sets - at least of what is marked “ready for publication” in the registry

**Comment by aturner** [comment]
Unpacked files at https://drive.google.com/drive/u/1/folders/1fTUuzE1x67sEQsFe1PWiRi-Hjge25ale

**Comment by aturner** [comment]
Review process notes: https://docs.google.com/document/d/1-HtOoRLGyRSeSl9wNAQLhL9nt5zfXv3IeYjdeneDQeA/edit?usp=sharing

**Comment by aturner** [comment]
2023-09-19 cca vault reports (round #2): https://drive.google.com/drive/folders/1WU5upZIH3Ydou8KUrh1T_-GGHXAzlSWS

**Comment by aturner** [comment]
UCD reports (round #1) are in-process

**Comment by christinklez** [comment]
Closing this as we'll be using the ["Validation Reports" project board](https://github.com/orgs/ucldc/projects/1/views/30) view, with a distinct issue for each given mapper's set of reports, to manage the validation report review process.
