### ISSUE TITLE
flickr.sppl mapper validation results

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#461]
A couple of issues with the flickr.sppl mapper:

description: needs to be in an array (wrap brackets)

description: map original Flickr-based Description to Description with the exception of any fields successfully parsed out using the existing set of parsed fields (listed below). Description should be all the things we were unable to parse out.

type
provenance
date
identifier
owner
previous_identifier_discard
previous_identifier
category
rights_information

We would like to ensure that any data in the source Description that could not be parsed and re-designated to a particular Rikolti field should be retained in the Rikolti Description.

**Comment by christinklez** [comment]
Notes from collection 27432: https://docs.google.com/spreadsheets/d/1Fw05at13cEbxcZR7DPJ4kBM1cuaXDBqFuC_x5WcnwoQ/edit#gid=1979820799 -- notes in row 3.

(This mapper is being utilized by both the South Pasadena Public Library and Lambda Archives institutions. SPPL collections look good! But the Lambda Archives seems to have some info dropping off.)

**Comment by lthurston** [comment]
I've modified the description mapping logic to prevent the removal of the `Owner` data, and now am producing this value:

`Owner: Lambda Archives of San Diego Collection/Accession: Pride Photo Collection/ L2013.63 Local Call number: P505.101m.r.t This image is provided for education and research purposes by Lambda Archives of San Diego (LASD). The image may not be sold or redistributed, copied or distributed as a photograph, electronic file, or any other media without written permission from LASD. Rights may be reserved. Responsibility for securing permissions to distribute, publish, reproduce or other use rest with the user. This photo may have had minor color/contrast correction. The original uncorrected file is available from LASD. For additional information on use and obtaining high-resolution images see our Copyright and Use Statement. LASD has made every effort to determine copyright and credit this photo appropriately. If you believe you hold copyright please contact us or comment below. If you are incorrectly identified in this photo, or identified and do not wish to be please contact us.`

The value in the validation report is:

`Collection/Accession: Pride Photo Collection/ L2013.63 Owner: Lambda Archives of San Diego`

A few things are different: 

1. I'm not sure why the copyright / use statement wasn't present when your team ran the report. Is it possible that's been added to the description in the source data? 
2. Another thing that's changed is that the "Local Call number" is now present. Same question as #1.
3. Lastly, the order of the fields has changed. My code simply removes values that match a regex, in this case, it's only the Date field that is pulled out. The remaining fields remain in the same order they were in originally.

What would you like me to do here?

**Comment by aturner** [comment]
Hi @lthurston confirming that Lambda Archives of San Diego has updated the source collection, since the time that we originally published it in Calisphere. We reharvested the collection to our Calisphere test site, and are seeing updated metadata

**Comment by lthurston** [comment]
Thanks @aturner and @christinklez. With regard to `previous_identifier_discard`, this only matches if the "Previous Identifier" value is "N/A". If you want to retain that in the description, I can remove this special handling of the "N/A" values, and have the value get picked up by the regular `previous_identifier` matcher.

**Comment by lthurston** [comment]
Actually, what I just wrote is confusing. I suspect you don't want an "N/A" value in the identifier field, which is where the previous identifiers end up. They are removed from the description.

**Comment by aturner** [comment]
@lthurston thanks for the update, and for the tip that `Previous Identifier: N/A` appears in collection 27338 (https://calisphere.org/collections/27338/ -- e.g., https://www.flickr.com/photos/sopaslibrary/7166655682/). I'd propose that we do not map N/A over to the "Identifier" element in our metadata scheme. But I do think we should retain it in our "Description" element (just to preserve/retain the original metadata and informational context -- may be helpful for a researcher/South Pasadena Library to know that this item explicitly does not have any previous identifier)

**Comment by christinklez** [comment]
@lthurston, one more request for this mapper. This request specifically relates to one collection #27432, and is for the "identifier" field. It seems that there are 7 records (out of 102 in the collection) in which the Flickr source record includes a "Local Call number:" label, instead of the usual and expected "Identifier:" label.

Would you be able to update the logic so that in either instances of "Identifier:" as well as "Local Call number:" that these values map to "identifier"?

Example in row 33 here: https://docs.google.com/spreadsheets/d/1PtpzX2jwDdoElN4VFf1q3uISxTqnaHzYnBHaSq_fWF0/edit#gid=563779707
(Note that this sheet has an active filter to surface this specific reported issue.)

One other thing to note: @amywieliczka has made some additional updates on the flickr.sppl mapper (to address a somewhat hard to explain ARK URL issue). Please work off this latest version.

Please let me know if you have any questions. Thanks!

**Comment by lthurston** [comment]
Thanks, Christine. I'll take a look and should be able to address this quickly.

**Comment by christinklez** [comment]
@lthurston Nevermind on my request! It looks like Amy was working on some updates on `flickr_sppl` and addressed my latest request. Sorry about that, and thanks!

**Comment by lthurston** [comment]
Disregarded!
