### ISSUE TITLE
Write the fetcher Dag

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#464]
This is step 2 of the [Airflow Architecture doc](https://docs.google.com/document/d/1pgPwDzFXrclVdR_3rukjb39YnZ5GDbV20b5xKS1WwLM/edit#heading=h.98hqpyjwzlrn)

Devs pairing up on this as this is the first Dag!

**Comment by amywieliczka** [comment]
Closed with https://github.com/ucldc/rikolti/pull/496 ! 🎉
