### ISSUE TITLE
Generate OAC-based data validation reports

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#470]
Mapper types spreadsheet, see sample collections tab: https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640

OAC mapper collections in rows 248-277.

**Comment by amywieliczka** [comment]
Blocked by #474

**Comment by aturner** [comment]
Will run one more report, but we otherwise have enough to review (seeing some common issues across 4 collections already)
