### ISSUE TITLE
oai.samvera mapper validation results

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#498]
See validation reports: #[27086](https://docs.google.com/spreadsheets/d/1hmkt4FqHYGfLCKyGWSJtz4gL_AmzcDtU2BYTqzRgylg/edit#gid=907869814) (08-17); #[27156](https://docs.google.com/spreadsheets/d/1uBF4Mx8cCiwk7r72FLFHIRqsIqnlW0emq4T8wnutvqQ/edit#gid=1653704597) (08-17); #[5105](https://docs.google.com/spreadsheets/d/1gfrSBpVwLqFsX6szsbje33YPsMlHduiEEKB3L2nWlpc/edit?usp=drive_web&ouid=100664038034622746046) (08-17); #[154 ](https://docs.google.com/spreadsheets/d/1TbMPaTeZJSsmeIazqly5Fw4kTOVzfl2bYAXjcIL6B8w/edit#gid=1232353712)(08-17); #[159 ](https://docs.google.com/spreadsheets/d/1X4FUgmNu6ZxVGak8Dj753e4L2xTRj_L51mOp_TiZ5bQ/edit#gid=1391927138)(08-17)

- type: Missing data. map type (See 27086 and 27156)
- language: Missing data. map language (See 27156 and 154)
- source: Missing data. map source (See 5105, 154, and 159)
- alternative title: Missing data. map alternative title (See 5105)
- is_shown_at: Missing data. Map is_shown_at (all collections)
- is_shown_by: Missing data. Map is_shown_by (all collections)

Also a quick note that collections 27086 and 27156 are coming from UCSC--it looks like they are no longer exposing some fields that we have previously harvested from. We will be reaching out to them to ask about that.

Otherwise, we've verified that all of the mapping requests indicated above are showing up in the vernacular. Thanks!

**Comment by lthurston** [comment]
@christinklez with regards to `type`, the values appear to come from a controlled vocabulary. For instance, images are `http://id.loc.gov/vocabulary/resourceTypes/img`. I'm not seeing these values being mapped to other values in the legacy  mapper, but it's happening somewhere. In any case, I can do this value mapping in the samvera mapper, and if we need to move it up a level later, so that other OAI mappers can use it, we can easily do that.

**Comment by lthurston** [comment]
Further comments re: `type`. The value is getting mangled by enrichments in some cases, resulting in the value not getting assigned to the final mapped data. One example is 27156, in which the following enrichment converts "image" into `[None]`:

`https://registry.cdlib.org/required-values-from-collection-registry?field=type&mode=overwrite`

That's not the only code that touches the type field in the course of mapping. There's an enrichment called `enrich-type` and some code in the conversion to `solr_doc` related to type.

I'm able to follow the course of these changes through the mapping and enrichment process, but it's not intuitive to me what or where the actual issue with the mapping of this collection, or what side effects there will be in other mappers if I change code. I think this requires the eyes of someone who knows this project a little better, but I'm happy to make any changes that come out of that review. 

The rest of the mapping issues have been addressed.
