### ISSUE TITLE
Re-generate ccavault data validation reports

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#511]

**Comment by christinklez** [comment]
Per notes here: https://github.com/ucldc/rikolti/pull/484

CDL requested: coverage / spatial: List items are being mapped as a string; they should be kept as distinct list items. Map as distinct list items. (See examples in #[3433](https://docs.google.com/spreadsheets/d/1nW63pR5bakrKkHDgD7xzEYr-cq4cFlUn74DGH5jwt5M/edit#gid=252656704), in particular line 1236 also includes the vernacular data.)

Lucas investigated and notes:
This is the result of an enrichment. See

`"/shred?prop=sourceResource%2Fspatial&delim=--"`

on https://registry.cdlib.org/api/v1/rikolticollection/3433/?format=json.

**Comment by aturner** [comment]
2023-09-19 validation reports: https://drive.google.com/drive/folders/1WU5upZIH3Ydou8KUrh1T_-GGHXAzlSWS
