### ISSUE TITLE
Prepare a list of collections that need to be ETL'd from Solr to ElasticSearch

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#541]
Running list of obsolete endpoints: https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1019256667

**Comment by aturner** [comment]
Baseline list at https://docs.google.com/spreadsheets/d/1zSV75qNlHFuk-awet2LexKBnKRp8gJ4fo2GKu_jSgFM/edit?usp=sharing
