### ISSUE TITLE
rerun flickr and ccavault and tvacademy (review for any adverse effects from base mapper changes)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#614]
- [x] flickr_api: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-01-29T17%3A46%3A50%2B00%3A00
- [x] flickr_sdasm: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-01-29T17%3A46%3A50%2B00%3A00
- [x] flickr_sppl: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-01-29T17%3A47%3A55%2B00%3A00
- [x] cca_vault_oai_dc: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-10-24T22%3A46%3A00%2B00%3A00
- [x] tv_academy_oai_dc: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-10-26T18%3A54%3A55%2B00%3A00

**Comment by amywieliczka** [comment]
I think this is defunct/was done a long time ago? @christinklez safe to close?

**Comment by christinklez** [comment]
Just did a double-check on these. All look good! (With the exception of TV Academy; we're currently working on addressing the endpoint issue with them.) Thanks!
