### ISSUE TITLE
ucd_json.ucd_json mapper validation results

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#621]
![Image](https://github.com/ucldc/rikolti/assets/32110172/61c86a70-da45-40c3-a21f-8bcf3cddc980)

- [ ] **title** -- "Title unknown": Titles are not mapping; instead "Title unknown" appears in the title field; the title seems to be coming from vernacular "name" field. Also, please be weary of the "name" fields in keywords/subjects (these are working fine!) -- Please map title from "name" (see screenshot)
- [ ] **rights_uri** -- type mismatch: Type mismatch errors--expect "list of str" vs actual "str". Please investigate type mismatch errors.

**Comment by lthurston** [comment]
I've fixed the title issue.

WRT the rights_uri, I can set the value from the license and return it in a list (of str), but the value in Solr is a string. I assume we want to store it as a list of str, in which case, we may need a custom content match validator on this field to compare the first item in a list (the actual value) with the expected value (a str).

I'll wait to hear back before proceeding with the validator change, and will push the change to sets the rights_uri as a list of str.

**Comment by barbarahui** [comment]
The `rights_uri` field is definitely a regular (not multivalued) string in solr.

I think the default field definition in the Validator should be updated to be `"type": str,`:

https://github.com/ucldc/rikolti/blob/main/metadata_mapper/validator/validator.py#L512

I guess this hasn't been an issue before because other collections have not had the field `rights_url`.

**Comment by barbarahui** [comment]
@aturner @christinklez @amywieliczka Just sanity checking that we haven't seen any collections with `rights_url` before. (See comment above).

**Comment by aturner** [comment]
@barbarahui that's correct -- UCD is the first (and only?) to use `rights_uri` for RightsStatements.org URLs

**Comment by barbarahui** [comment]
@lthurston OK, so can you please update the default field definition for `rights_uri` in the Validator to check for type `str` (rather than list of str)? That should resolve the issues for this mapper.

**Comment by lthurston** [comment]
> @lthurston OK, so can you please update the default field definition for `rights_uri` in the Validator to check for type `str` (rather than list of str)? That should resolve the issues for this mapper.

Done! There are no `title` or `rights_uri`field issues in the validation report.
