### ISSUE TITLE
oai.content_dm.chico validation results: [base contentdm is_shown_by logic]

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#635]
### likely a base contentdm issue
- [ ] **is_shown_by**: Need to fish `<dc:identifier>` and transform that URL; see the legacy base contentdm mapper: https://github.com/calisphere-legacy-harvester/dpla-ingestion/blob/cfe3dcb06008c0c6cb9d8207fe28bfaa1a855e4f/lib/mappers/contentdm_oai_dc_mapper.py#L31 

Example 1 from [26762 report](https://docs.google.com/spreadsheets/d/11pFMHaVWrHJpC5aV4e-moihSUubVTv1QgJ60pihEym8/edit#gid=1119837120): 
Fish for: `<dc:identifier>http://archives.csuchico.edu/cdm/ref/collection/coll11/id/10006</dc:identifier>`
& transform to: `http://archives.csuchico.edu/utils/getthumbnail/collection/coll11/id/10006`
[Note: Collections 26762, 26765, 26766, 26768 use this URL transformation to grab thumbnails.]

Example 2 from [26763 report](https://docs.google.com/spreadsheets/d/1mk0mbyjyCvFnW8TOqGAYuff_eLTuOwHlEDXb6q0R7fI/edit#gid=1184541777): 
Sometimes, the legacy mapper also seems to try to get a larger thumbnail. In this example, the mapper fishes `<dc:identifier>http://archives.csuchico.edu/cdm/ref/collection/coll10/id/1001</dc:identifier>`
and transforms the URL to snag this larger thumbnail: `http://archives.csuchico.edu/utils/ajaxhelper?CISOROOT=coll10&CISOPTR=1001&action=2&DMHEIGHT=2000&DMWIDTH=2000&DMSCALE=17`
Note that this smaller thumbnail also works fine: `http://archives.csuchico.edu/utils/getthumbnail/collection/coll10/id/1001`
[Note: Collection 26763 and 26765 use this URL transformation for the larger thumbnails.]

### type capitalization; enrichment issue(?)
- [ ] **type**: expect image; Rikolti has Image. type is provided by the Registry (fill)

***

## resolved issues
- [x] **source**: in the vernacular; pull in -- map `<dc:source>` to source -- this may be getting addressed in the base oai mapper.

**Comment by barbarahui** [comment]
Fixes should trickle down from the base OAI mapper. See https://github.com/ucldc/rikolti/issues/678
