### ISSUE TITLE
oai.islandora mapper validation results: [temporal special treatment for #3155]

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#640]
### base islandora mapper issues
- [x] temporal: map `<dc:coverage>` to temporal -- via enrichment for collection 3155 only.

***

#### addressed by the base oai mapper updates
- [x] language: map `<dc:language>` to language. (Note that there is one record that has English & Spanish listed; we should make sure they map correctly) -- possibly addressed in the base oai mapper.

#### base islandora mapper issues
- [x] is_shown_at: please see legacy mapper logic (sjsu_islandora) which includes details on how this URL was generated
- [x] is_shown_by: please see legacy mapper logic (sjsu_islandora) which includes details on how this URL was generated

Note: The legacy `sjsu_islandora` mapper has this URL logic: https://github.com/calisphere-legacy-harvester/dpla-ingestion/blob/ucldc/lib/mappers/sjsu_islandora_mapper.py
However, I'm unsure if adding this logic to the Rikolti `oai.islandora` mapper will inadvertently affect `oai.burbank_islandora` & `oai.chs_islandora` as well. Please verify; if the URL logic introduces issues to the child mappers, we may need to carve out a dedicated sjsu mapper.

![Image](https://github.com/ucldc/rikolti/assets/32110172/dc22a976-2fd9-4e94-9fde-cfaef72de56f)

~~Also, please note that oai.islandora mapper is being used by another contributor--the is_shown_at and is_shown_by logic proposed may not apply to them (Palos Verdes Library District). **Edited to add: PVLD is planning to move to Recollect early 2024; so if the adjustments do not work for PVLD, we're okay with accepting that (and can ETL PVLD's collections instead).**~~ Updated plan to ETL PVLD's collections. This mapper will now only be used by SJSU.

**Comment by amywieliczka** [comment]
This should be addressed with PR #716
