### ISSUE TITLE
oai.content_dm.pepperdine validation results (base OAI mapper request)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#641]
- [x] alternative_title: missing alternative title; map `<dcterms:alternative> `to alternative title

Please address this at the base oai mapper. (omeka.omeka and oai.samvera both need have "alternative_title" requests)

**Comment by lthurston** [comment]
If you provide me with a collection to validate, I can confirm that this is working as expected in either Chapman or Samvera branches.

**Comment by christinklez** [comment]
Lucas checked the base oai mapper work addresses the alternative title issue.
