### ISSUE TITLE
Determine 3-5 test collections for Fetcher/Mapper types

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/rikolti#66]
- OAI-PMH
- Legacy OAC
- Nuxeo
- Solr Index
- Flickr API

**Comment by aturner** [comment]
Proposed sample collections (running list): https://docs.google.com/spreadsheets/d/1sZK22O37xnLRkBXUvd6Sye6bKKK9LgTcuUxWAb_NjR8/edit?usp=sharing
