### ISSUE TITLE
oai.islandora.burbank validation results: character encoding only

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#666]
**character encoding:**
- [x] identifier: Â shows up in the vernacular but Rikolti ignores it -- Â ""\u00c2"" appears in the identifier field for 19 records. These are not in the oai (see: https://burbankinfocus.org/oai2/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:burbankinfocus.org:islandora_1965), but seem to pop up in the vernacular. Need to investigate
- [x] format: Â ignored by Rikolti 

![Image](https://github.com/ucldc/rikolti/assets/32110172/7380ab91-2020-4524-b27b-0a80ddb8b283)

**Comment by aturner** [comment]
Issues have been resolved based on review of latest 2023-12-21 validation report
