### ISSUE TITLE
oai.quartex validation results: [split logic (language)]

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#669]
#### oai.quartex
- [x] base quartex issue: split ; -- see legacy mapper: https://github.com/calisphere-legacy-harvester/dpla-ingestion/blob/cfe3dcb06008c0c6cb9d8207fe28bfaa1a855e4f/lib/mappers/oai_dublin_core_mapper.py#L17C1-L22C26
Examples included in #27415 (subject), #26220 (subject, coverage, spatial), #26216 (subject, coverage, spatial, language), #26218 (subject), #27845 (subject)
   - [x] subject: Expecting several distinct "subject" entries; however "subject" data is provided within one tag, separated by semi-colons. Does Rikolti need logic?
   - [x] coverage/spatial: same issue as subject
   - [x] language: likely same issue (See #26216 example in row 3) `<dc:language>heb; lat</dc:language>`
[please see screenshot below]

#### enrichments
- [ ] Add to: https://github.com/ucldc/rikolti/blob/0e03c4fe6a08172ed9affaf04b9f34c9bcb5d8c8/metadata_mapper/mappers/constants.py
   - [ ] type: `<dc:type>Administrative records</dc:type>` --> text
   - [ ] type: `<dc:type>Artifacts</dc:type>` --> physical object
- [ ] On the list; investigate? https://github.com/ucldc/rikolti/blob/0e03c4fe6a08172ed9affaf04b9f34c9bcb5d8c8/metadata_mapper/mappers/constants.py
   - [ ] type: `<dc:type>Correspondence</dc:type> ` --> text
   - [ ] type: `<dc:type>Other</dc:type> ` --> physical object
   - [ ] type: `<dc:type>Still image</dc:type>` --> image
   - [ ] type: `<dc:type>Collection</dc:type>` --> collection

![Image](https://github.com/ucldc/rikolti/assets/32110172/efc71a00-0f53-4ec6-99cd-9a9b65b2875e)

*** 

#### base oai issues
- [x] language: map language 
- [x] source: Map source

**Comment by christinklez** [comment]
@amywieliczka I've just added in some collection examples for where the split logic should kick in:
split ; logic -- for subject, coverage, spatial, language

Legacy mapper: https://github.com/calisphere-legacy-harvester/dpla-ingestion/blob/cfe3dcb06008c0c6cb9d8207fe28bfaa1a855e4f/lib/mappers/oai_dublin_core_mapper.py#L17C1-L22C26 

See examples in #27415 (subject), #26220 (subject, coverage, spatial), #26216 (subject, coverage, spatial, language), #26218 (subject), #26258 (Subject), #26255 (subject), #26256 (subject), #27845 (subject)

**Comment by amywieliczka** [comment]
This addresses splitting on `;` for subject: https://github.com/ucldc/rikolti/pull/712
There are more issues here though, so I don't want to link the PR (which would close this issue when the PR closes)

**Comment by christinklez** [comment]
@amywieliczka -- I just took a peek at these validation reports to try to close out any issues. The split logic looks good for the most part, with the exception of "language" -- see screenshot. Thanks! This is collection 26216.

![Image](https://github.com/ucldc/rikolti/assets/32110172/f828ae85-cee7-4143-8d08-b527ed807b89)

**Comment by amywieliczka** [comment]
This was addressed in PR #716
