### ISSUE TITLE
oai.content_dm.lapl: [base contentdm is_shown_by logic & split logic]

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#671]
### base contentdm
- [ ] **split ; logic**: date -- see example in [27224](https://docs.google.com/spreadsheets/d/1P825CqxXmuheDp_mqYk-vUMIOJ26XraTFO5tHTaMNzY/edit#gid=760737926).

- [ ] **is_shown_by**:  Known issue: CONTENTdm mapper logic to fish out a thumbnail image (using data from `<dc:identifier>`) doesn't look like it's in place. Re-run validation report once Lucas has this fixed at the base CONTENTdm mapper level

Example 1 from [27224 report](https://docs.google.com/spreadsheets/d/1P825CqxXmuheDp_mqYk-vUMIOJ26XraTFO5tHTaMNzY/edit#gid=760737926): 
Fish for: `<dc:identifier>http://173.196.26.125/cdm/ref/collection/menus/id/1001</dc:identifier>`
& transform to: `http://173.196.26.125/utils/getthumbnail/collection/menus/id/1001`
[Note: Collection 27224 uses this URL transformation to grab thumbnails.]

Example 2 from [27225 report](https://docs.google.com/spreadsheets/d/1zJsL3l5g_GARVfbBTNCR_FNZuEsCsMZ4qLkEa2vCMZ0/edit#gid=1649856657): 
Sometimes, the legacy mapper also seems to try to get a larger thumbnail. In this example, the mapper fishes `<dc:identifier>http://173.196.26.125/cdm/ref/collection/movie/id/0</dc:identifier>`
and transforms the URL to snag this larger thumbnail: `http://173.196.26.125/utils/ajaxhelper?CISOROOT=movie&CISOPTR=0&action=2&DMHEIGHT=2000&DMWIDTH=2000&DMSCALE=51`
Note that this smaller thumbnail also works fine: `http://173.196.26.125/utils/getthumbnail/collection/movie/id/0`
[Note: Collection 26094, 27219, 27220, 27221, 27222, 27223, 27225, 27226, & 27227 use this URL transformation for the larger thumbnails.]

### type enrichments
- [ ] **type:** registry supplied "Image" retains capital "Image"; expect "image" -- 26094 only, when type is supplied by the registry.

***
### questions: Validator or mapper issues?**
- [x] **rights_uri**: Expected value is a `List of str`; source data has no relevant data. Validator is over-checking?
- [x] **is_shown_by**: Expected value is a `str`; but Rikolti notes `NoneType`

### character encoding
- [x] **Character encoding issues**: Some special Unicode/UTF-8 characters in `<dc:subject>` and `<dc:description>` are getting garbled post-fetching/mapping. The source XML looks AOK . E.g, search for this object `oai:173.196.26.125:movie/4` and see first subject heading `Vélez, Lupe` in 1) vernacular data at https://rikolti-data.s3-us-west-2.amazonaws.com/27225/vernacular_metadata_2023-12-02T03%3A39%3A12/data/0 and mapped data at https://rikolti-data.s3-us-west-2.amazonaws.com/27225/mapped_metadata/0 vs. 2) source OAI at http://173.196.26.125/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=movie
![Image](https://github.com/ucldc/rikolti/assets/32110172/0494eeda-7d35-434c-aa79-783ddd51de5d)

### base oai mapper
- [x] **alternative_title**: Known issue: lacks mapping from `<dcterms:alternative>`. Re-run validation report once Lucas has this fixed at the base OAI mapper level

**Comment by barbarahui** [comment]
Fixes should trickle down from the base OAI mapper. See https://github.com/ucldc/rikolti/issues/678
