### ISSUE TITLE
Investigate issue with application of  `rights_statement_default` in Rikolti mapper (from metadata_mapper/mappers/constants.py)

### ISSUE THREAD

**Issue by aturner** [ucldc/rikolti#706]
We have a default rights statement specified in metadata_mapper/mappers/constants.py (`rights_statement_default`) , intended to be supplied as a "statement of last resort" if there is nothing in the source metadata -- and if we neglected to intentionally add a boilerplate statement into records at the time of harvesting.

In running Rikolti mapper validation tests, we've noticed that this statement of last resort doesn't seem to be getting invoked and applied, for cases where there's nothing in the source metadata. Two example collections, below:

https://registry.cdlib.org/admin/library_collection/collection/29
https://registry.cdlib.org/admin/library_collection/collection/26713

For the time being, we've intentionally added the statement within the "Rights statement" field in Registry, so it is explicitly there -- and should be applied per the `/required-values-from-collection-registry?field=title&mode=fill,` enrichment chain.  That can be backed out, when re-investigating this issue.

**Comment by barbarahui** [comment]
I removed the "rights statement" from Registry for collections 29 and 26713. I didn't run 26713 yet though because it's so huge.

**Comment by christinklez** [comment]
From collection 29, this record doesn't have a Nuxeo-supplied copyright info: 
- -stage: https://calisphere-stage.cdlib.org/item/ark:/81235/d85n69/
- Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/7dc2fe1b-207b-485f-8d8e-632f172a0367/view_documents
   - The Nuxeo record is indeed missing rights details. 

Timeline:
- **January 30th**: In Registry, Barbara removed the Registry-supplied rights description (on January 30th, according to the Registry history).
- **April 24th**: According to the [Publication Sequence spreadsheet](https://docs.google.com/spreadsheets/d/1nsatqPLvbuwty3wWxgosPfIsoScsiFmKGgYgDLPrn3E/edit#gid=1997346240) -- collection 29 was most recently harvested on April 24th.

Based on this timeline, my sense is that the template `rights_statement_default` appears to be working!
