### ISSUE TITLE
Calisphere frontend updates to use OpenSearch and new content/media hosting infrastructure

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#747]
Calisphere frontend updates to use OpenSearch and new content/media hosting infrastructure 
- Note: Frontend UI work includes OpenSearch talking to Calisphere; there may be additional back-end changes. Legacy currently has one Solr index; Rikolti will have multiple indices (one per collection)

As part of this:
- **Ensure frontend works with OpenSearch** (spin up a completely new CSphere stage front-end that is working with OpenSearch data)
   - Update the environment variable about where to find the OS index; permissions associated with searching the OS index.
   - Ensure the Registry custom metadata facets & Aeon requests work
   - Image mosaics (collections listing mosaics; related items carousel results; exhibit item lightbox) – need these to call from OS (instead of Solr)
   - New cloudfront configuration
- **Frontend depends on media.json to understand which viewer to use** (e.g., zoomer, video player, etc.) as well as display the child metadata; will need to change the source of the child metadata. 
   - Note that our current operations include several layers of requests! Instead this will streamline to one request.

**Comment by barbarahui** [comment]
@christinklez I think all of the things mentioned in the description here are covered by other cards, so this one can be closed.

**Comment by barbarahui** [comment]
Oh actually I'm not sure that this is done: "Ensure the Registry custom metadata facets & Aeon requests work". Should we create a separate issue for it?

**Comment by christinklez** [comment]
Thanks @barbarahui! Custom metadata facets/filter (on collection pages) & Aeon request buttons (on certain item record pages) both *seem* to work in -stage! I've been checking while QA-ing collections that are harvested through. I can plan to create new issues for these if I observe any cases in which they don't work. Thank you!
