### ISSUE TITLE
oai.omeka validation results [updated identifier -> is_shown_by logic needed]

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#750]
I just came across the saddest snafu with the Omeka mappers.

**The background:** The Omeka mapper currently has a special logic built in. Many of the collections are supplying multiple `<dc:identifier>`s; the special logic is set up to move the `<dc:identifier>s3.amazonaws.com</dc:identifier>` formatted URLS into `is_shown_by`'s, while also suppressing these from mapping to `identifier`. 

Here is the Rikolti logic that moves the AWS identifiers into `is_shown_by`: https://github.com/ucldc/rikolti/blob/0e03c4fe6a08172ed9affaf04b9f34c9bcb5d8c8/metadata_mapper/mappers/oai/omeka_mapper.py#L20

**The issue:** These URLs have updated to `<dc:identifier>https://d1y502jg6fpugt.cloudfront.net/</dc:identifier>` -- and so now this is broken for 7 (of 29) collections using this mapper. This is a recent change that has happened in the source OAI, as evidenced by these vernacular report comparisons: see [vernacular 2024-01-24 vs 2024-02-01](https://drive.google.com/drive/folders/1qX5BdjU54DFz15gWGXfNJ0iZJuO4D8B5). It seems to impact all hosted Omeka instances (i.e., Omeka sites running on `omeka.net`)

**Request:** I think this could uniformly be updated to `https://d1y502jg6fpugt.cloudfront.net/` -- all 7 OAI sets seem to have this beginning URL. (Or, instead of updating, another option is to add in this alternative logic as well.) I do believe that all the Omeka instances that were utilizing this logic have all had their identifier/URL domains updated, so simply swapping out the URL *should* be harmless.

[ ] **identifier:** now picking up a cloudfront URL to the `identifier`; this used to be an AWS link. We should remove this cloudfront URL from `identifier`.
[ ] **is_shown_by:** mapper now has no data for `is_shown_by`. The cloudfront URL (which is in a `<dc:identifier>` field) needs to map to `is_shown_by`

Note that no collections utilizing the child `omeka.nothumb` mapper will be impacted by this logic.

***

If helpful, here are the OAI links:
- https://welgadigitalarchive.omeka.net/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=5
- https://welgadigitalarchive.omeka.net/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=6
- https://mpdsfdance.omeka.net/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=2
- https://mpdsfdance.omeka.net/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=1
- https://mpdsfdance.omeka.net/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=9
- https://mpdsfdance.omeka.net/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc&set=4
- https://annahalprindigitalarchive.omeka.net/oai-pmh-repository/request?verb=ListRecords&metadataPrefix=oai_dc

**Comment by barbarahui** [comment]
@christinklez do you have the registry collection IDs for these 7 collections?

**Comment by barbarahui** [comment]
Actually nevermind, I'm using 27433 for testing :)

**Comment by christinklez** [comment]
@barbarahui reviewed the collections and they all look amazing! Thank you so, so much!
