### ISSUE TITLE
Nuxeo mapper: handle half-created records

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#755]
There are some half-created records in Nuxeo, for example:

https://nuxeo.cdlib.org/nuxeo/nxpath/default/asset-library/UCB/UCB%20EDA/jekyll/6827693808047028933@view_documents?tabIds=%3A&conversationId=0NXMAIN4

And others noted in this issue: https://github.com/ucldc/rikolti/issues/598

We can have the Nuxeo mapper skip these records, which don't have a title or any other metadata populated.

**Comment by christinklez** [comment]
Thanks @barbarahui! Looks like this empty record was likely created in error. We can definitely reach out to folks to do a bit of cleanup.

Is there a way to get a list of the empty/half-created records that are tripping up our runs?

**Comment by barbarahui** [comment]
Well right now, these empty records aren't going to trip up your runs anymore. 

The validator doesn't validate new records, so it won't flag them. This means that they are getting mapped, which we don't want.

Proposed work to remedy this:
1. have the mapper skip these records, based on the fact that they're missing title and other metadata
2. have the mapper print a warning when the record is skipped because it's empty
3. run a QA report once the collection is on stage to double-check that no required fields are missing

We can also write a report to do a global search in Nuxeo for records that are missing required fields so that you can alert contributors, but I think this would be a separate task and outside the scope of Rikolti MVP.

**Comment by barbarahui** [comment]
Re 2. above, we could add functionality to create a report (like a csv) so that you have a handy list to send to contributors. But this would be a bit of work and I think outside the scope of MVP work?

**Comment by christinklez** [comment]
Discussed on Feb 6: Let's skip these records, and throw an error in the log (in the mapping output).

Post-mvp: We can discuss a skip reports of sorts.

**Comment by barbarahui** [comment]
This is ready for code review but not yet deployed to Airflow.

**Comment by barbarahui** [comment]
@christinklez  the nuxeo mapper will now print a message to the airflow logs when it skips a record. It will appear in the map_endpoint_task log and look like this:

```
[2024-02-07, 00:16:50 UTC] {{logging_mixin.py:150}} INFO - **SKIPPED RECORD**: [26864] Record with uid  f8656ae0-d5ff-44cc-b572-b2f247be2669 has no title; not mapping
```
