### ISSUE TITLE
[bug] Mapping task (triggered by Registry) results in error: TypeError "must be str, not None"

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#765]
Collection: 28202
Mapper type: nuxeo.nuxeo
Log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-02-07T18%3A12%3A27%2B00%3A00&task_id=fetch_collection_task&tab=logs
-test URL: https://calisphere-test.cdlib.org/collections/28202/
Note: This is a new collection (not published in -test or prod; no data in Solr; but there is content ready in Nuxeo.)

Collection: 28174
Mapper type: oai.samvera
Log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-02-09T20%3A31%3A13%2B00%3A00
-test URL: https://calisphere-test.cdlib.org/collections/28174/

**Comment by amywieliczka** [comment]
This is resolved as well! https://github.com/ucldc/rikolti/commit/751b7aab13ae7a44511aec44a7d80b12cc7669ea
