### ISSUE TITLE
[bug] Mapping task (triggered by Registry) results in error: "unmappable return value length: 7174 > 1024"

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#766]
Collection: 27768
Mapper type: oai.samvera
Log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-02-09T20%3A55%3A29%2B00%3A00&task_id=fetch_collection_task&tab=logs
-test URL: https://calisphere-test.cdlib.org/collections/27768/
Note: This collection is new, and not yet on -test or -prod. There are records in the OAI: https://digital.library.ucla.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dpla&member_of_collection_ids_ssim:k13t1n-89112

**Comment by amywieliczka** [comment]
This is resolved!
