### ISSUE TITLE
Nuxeo harvesting error during content harvesting (401 Client Error)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#780]
28043 (UCI, collection with 50+ complex object records) and 27551 (UCSF, collection with 2 simple object records) are both experiencing errors during the "content harvesting" task in Airflow. Seems to be a 401 Client Error.

28043 logs: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-04T17%3A11%3A59%2B00%3A00&task_id=content_harvesting.content_harvest

27551 logs: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-04T18%3A57%3A19%2B00%3A00&task_id=content_harvesting.content_harvest

**Comment by barbarahui** [comment]
@christinklez We had the username misspelled in our MWAA config file. It should be fixed now. Can you try again?

**Comment by christinklez** [comment]
Thank you--the authentication issue looks to be resolved! Was able to run through 27551 (and it's appearing in the stage index). 

Parts of 28043 has run through successfully, though there seems to be an issue with some particular records. These errors do not seem to occur consistently.
- See 49--4th attempt: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-04T17%3A11%3A59%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=49 -- 3rd (previous) attempt ran fine
- See 7---3rd attempt: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-04T17%3A11%3A59%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=70 -- 4th & 5th (subsequent) attempts ran fine

**Comment by amywieliczka** [comment]
I'm not quite clear on why the content harvester will occasionally report `WARNING - State of this instance has been externally set to failed. Terminating instance` - perhaps there are too many ECS containers running? Typically, I can rerun these failed tasks and they do work the second time around. This is definitely a completely different issue than the Nuxeo errors, and one I don't think is critical right at this moment. 

The rest of the error messages reported in these logs are errors about trying to report the error out to SNS/SQS/ultimately the registry. I'm currently working on fixing that, actually.

**Comment by christinklez** [comment]
Thank you! I was eventually able to run 28043 completely through, so I'm going to close this issue out for the moment!

If I come across this error again, I'll track it in a new issue. Thank you!
