### ISSUE TITLE
[bug] `content_harvest` errors (3 Nuxeo collections)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#783]
## Error notes from 2024 March 12
26864 is running into issues during the `content_harvest` task.

- Log for 26864-[page 29](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T20%3A33%3A10%2B00%3A00&num_runs=100&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=29) - [permanent link to content_harvest map index 29](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-12T20%3A33%3A10%2B00%3A00&map_index=29)
   - The log seems to indicate the error is happening while running this Nuxeo complex object record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/4e820d82-4282-4e29-bfeb-c894fa72fc04/view_documents -- this complex object includes 17 objects.
   - 18-017-109.tif seems to be the object that's experiencing errors: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/405c77b1-d153-45a3-b861-5bd53655835f/view_documents
   - Record on -prod: https://calisphere.org/item/4e820d82-4282-4e29-bfeb-c894fa72fc04/ -- specific object: https://calisphere.org/item/4e820d82-4282-4e29-bfeb-c894fa72fc04/?order=6
   - The error message is:
```
make_jp2 command failed: ['/usr/bin/convert', '-quiet', '-format', '-jp2', '-define', 'jp2:rate=10', '/tmp/18-017-109.tif[0]', '/tmp/18-017-109.jp2']
returncode was: 1
output was: 
convert: width or height exceeds limit `/tmp/18-017-109.tif' @ error/cache.c/OpenPixelCache/3909.
convert: no images defined `/tmp/18-017-109.jp2' @ error/convert.c/ConvertImageCommand/3229.

"; 13557)
```

## Error notes from 2024 March 4
Three pages in the collections 28198, 28196, 27626 (so far) are running into issues during the `content_harvest` task. I've retried these and they continue to experience errors. Note that other pages in these collections went through to success.

- Log for 28198-[page 3](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-04T23%3A48%3A59%2B00%3A00&num_runs=100&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=3) - [permalink for mapped index 3](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-04T23%3A48%3A59%2B00%3A00&map_index=3)
   - The log seems to indicate the error is happening while running this Nuxeo complex object record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/b9794fa7-5104-4650-b9ca-a19216ad4d83/view_documents -- this complex object includes 10 component objects.
   -  Of the 10 component objects, the content-harvest task seems to have been able to convert 9 of the images. Here is the image that is missing: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/8d8c2294-1bb6-4fcf-9388-99f705ddac93/view_documents -- named ps002887.tif (813 MB)
   - The error message is:
```
make_jp2 command failed: ['/usr/bin/convert', '-quiet', '-format', '-jp2', '-define', 'jp2:rate=10', '/tmp/ps002887.tif[0]', '/tmp/ps002887.jp2']
returncode was: 1
output was: 
convert: cache resources exhausted `/tmp/ps002887.tif' @ error/cache.c/OpenPixelCache/4095.
convert: no images defined `/tmp/ps002887.jp2' @ error/convert.c/ConvertImageCommand/3229.

; 13527)
```

- Log for 28196-[page 11](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T01%3A00%3A46%2B00%3A00&num_runs=100&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=11) - [permanent link to content_harvest map index 11](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-05T01%3A00%3A46%2B00%3A00&map_index=11)
   - The log seems to indicate the error is happening while running this Nuxeo complex object record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/38cdc9e0-a29c-4b77-81e5-cfc9504ce90c/view_documents -- this complex object includes 5 component objects.
   - I couldn't tell which object is getting stuck.
   - The error message is:
```
make_jp2 command failed: ['/usr/bin/convert', '-quiet', '-format', '-jp2', '-define', 'jp2:rate=10', '/tmp/18-044-004.tif[0]', '/tmp/18-044-004.jp2']
returncode was: 1
output was: 
convert: cache resources exhausted `/tmp/18-044-004.tif' @ error/cache.c/OpenPixelCache/4095.
convert: no images defined `/tmp/18-044-004.jp2' @ error/convert.c/ConvertImageCommand/3229.

; 13485)
```

- Log for 27626-[page 0](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T02%3A22%3A25%2B00%3A00&num_runs=100&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=0) - [permalink to failed dag run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/graph?run_id=manual__2024-03-05T02%3A22%3A25%2B00%3A00&execution_date=2024-03-05+02%3A22%3A25%2B00%3A00) - [permalink to content_harvest map index 0](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-05T02%3A22%3A25%2B00%3A00&map_index=0) - [permalink that includes collection id](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dagrun/list/?_flt_0_run_id=manual__2024-03-05T02%3A22%3A25%2B00%3A00)
  - This is the Nuxeo collection running: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/0ea470f5-f2be-42b3-bf25-9c632eaf5c0f/view_documents (includes 10 Nuxeo documents)
  - The error seems to be happening while running this PDF: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/8bd64cb5-d7c3-49c4-a8b2-78b4911745d4/view_documents -- named ar2015-17_1_127committeeonartsandlectures_andersendog.pdf (25 MB)
  - The error message is:
```
pdf_to_thumb command failed: ['/usr/bin/convert', '-quiet', '-strip', '-format', 'png', '-quality', '75', '/tmp/ar2015-17_1_127committeeonartsandlectures_andersendog.pdf[0]', '/tmp/ar2015-17_1_127committeeonartsandlectures_andersendog.png']
returncode was: 1
output was: 
   **** Error: Couldn't initialise file.
               Output may be incorrect.

Requested FirstPage is greater than the number of pages in the file: 0
   No pages will be processed (FirstPage > LastPage).
convert: no images defined `/tmp/ar2015-17_1_127committeeonartsandlectures_andersendog.png' @ error/convert.c/ConvertImageCommand/3229.

; 12841)
```

**Comment by amywieliczka** [comment]
Bettered content_harvester error reporting: 
- https://github.com/ucldc/rikolti/commit/34acb2fba428c023f3e6745df5f48e05b42bdaef
- https://github.com/ucldc/rikolti/commit/cffbf9d3fa01cb99e37ef6d1548d38647844932b

And broke this out into 3 separate issues - more details in each of those issues - closing out this issue: 
- https://github.com/ucldc/rikolti/issues/817
- https://github.com/ucldc/rikolti/issues/818
- https://github.com/ucldc/rikolti/issues/819
