### ISSUE TITLE
[bug] `create_stage_index` date-related errors (1 Nuxeo & 4 non-Nuxeo collections)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#784]
Several collections are running into issues during the create-stage-index task. I've retried these and they continue to experience errors.

- [x] [Log for 12903](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T02%3A23%3A52%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) (mapper: nuxeo.nuxeo) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-05T02%3A23%3A52%2B00%3A00)
   - Run ID: manual__2024-03-05T02:23:52+00:00
   - `[2024-03-05, 02:32:42 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 9030 for task create_stage_index (3 errors in bulk indexing 28 records: ['mapper [date] cannot be changed from type [text] to [date]']; 6547)`
   - This is a Nuxeo collection: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/f4626766-f617-4a77-a518-abe1fa26d324/view_documents

- [x] [Log for 26684](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T02%3A36%3A09%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) (mapper: oai.content_dm.pepperdine) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-05T02%3A36%3A09%2B00%3A00)
   - Run ID: manual__2024-03-05T02:36:09+00:00
   - `[2024-03-05, 02:38:53 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 9044 for task create_stage_index (1 errors in bulk indexing 18 records: ["failed to parse field [date] of type [date] in document with id '175ca414849d8027d8a63f51882ccc78'. Preview of field's value: 'ca. 1976'"]; 6681)`

- [x] [Log for 3767](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T03%3A07%3A39%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) (mapper: oai.cca_vault) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-05T03%3A07%3A39%2B00%3A00)
   - Run ID: manual__2024-03-05T03:07:39+00:00
   - `[2024-03-05, 03:18:49 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 9478 for task create_stage_index (6 errors in bulk indexing 10 records: ["failed to parse field [date] of type [date] in document with id '87568e587296108f2ddd1a783c5052e4'. Preview of field's value: '9/9/92'", "failed to parse field [date] of type [date] in document with id 'c66a5fd0408026729f1e57885ebc70f3'. Preview of field's value: '5/5/94'", "failed to parse field [date] of type [date] in document with id '0932f924ae7c470d9beb65b71edc636c'. Preview of field's value: '5/7/94'", "failed to parse field [date] of type [date] in document with id '0223869607f4d5c4438fe3f3a30a3117'. Preview of field's value: '4/2/93'", "failed to parse field [date] of type [date] in document with id '9e5c5cecf3030ec574ab1b6b0eb9cbc9'. Preview of field's value: '6/10/92'", "failed to parse field [date] of type [date] in document with id 'f5ef568fd0946ec06f85fc827e6d8b9d'. Preview of field's value: '10/1/93'"]; 8352)`

- [x] [Log for 27143](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T21%3A18%3A43%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) (mapper: oai.omeka.nothumb) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-05T21%3A18%3A43%2B00%3A00)
   - Run ID: manual__2024-03-05T21:18:43+00:00
   - `[2024-03-06, 03:24:59 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 16362 for task create_stage_index (6 errors in bulk indexing 49 records: ['mapper [date] cannot be changed from type [text] to [date]']; 2990)`

- [x] [Log for 27148](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-06T03%3A49%3A14%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) (mapper: oai.omeka.nothumb) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-06T03%3A49%3A14%2B00%3A00)
   - Run ID: manual__2024-03-06T03:49:14+00:00
   - `[2024-03-06, 04:04:45 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 16588 for task create_stage_index (2 errors in bulk indexing 50 records: ['mapper [date] cannot be changed from type [date] to [text]', "failed to parse field [date] of type [date] in document with id '7e5ad0cb5fb440da4541ce2c3b4927e0'. Preview of field's value: '[?]-11-23'"]; 10616)`

**Comment by amywieliczka** [comment]
Added an index template to force `date` to always be of type `text`, instead of allowing OpenSearch to make it of type `date` when many records in the collection (but not all) had valid dates.
