### ISSUE TITLE
Rename *_url fields

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#791]
It'd be nice to rename the *_url fields -- in fact I see in the frontend was anticipating this change:

collection_url --> collection_ids
campus_url --> campus_ids
repository_url --> repository_ids

~~Also, it looks like it would be better to make these fields type `keyword` rather than `long`, because we're using them in `term` rather than `range` queries. See the tip on Mapping numeric identifiers here: https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#keyword-field-type~~

**Comment by amywieliczka** [comment]
@barbarahui Hm, renaming these fields breaks validation, so I'd rather wait till post MVP. 

If the Calisphere UI is super difficult to reason about, we could perform a pre-index mapping of *_url fields to *_ids fields and post MVP change them at the mapping level. This seems like a safe pre-index mapping, and it seems safe enough to promise to later to move that pre-index mapping down a few layers into mapping proper, given how simple a change this is. 

It looks like collection_url and repository_url are already `keyword`? https://github.com/ucldc/rikolti/blob/main/record_indexer/index_templates/record_index_config.py

**Comment by christinklez** [comment]
Leverage OpenSearch alias features? https://www.elastic.co/guide/en/elasticsearch/reference/current/field-alias.html
