### ISSUE TITLE
[bug] Burbank landing page error (unintended splitting on single colons in the collection title)

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#792]
There seems to be an error loading the Burbank's repository landing page: https://calisphere-stage.cdlib.org/institution/251/collections/

```
InvalidURL at /institution/251/collections/
URL can't contain control characters. '/api/v1/collection/ Businesses, Homes, and Streets/?format=json' (found at least ' ')
```

**Comment by christinklez** [comment]
Investigate updating this line to a double colon:
https://github.com/ucldc/rikolti/blob/main/metadata_mapper/mappers/mapper.py#L1437

**Comment by amywieliczka** [comment]
@barbarahui the `sort_collection_data` field is now updated to use double colon delimiters `::` - we'll need to re-run the harvests to see the updates in calisphere-stg though.
