### ISSUE TITLE
`type` field is not getting mapped through for some (complex?) objects

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#801]
Some of the objects that are currently in calisphere-stage don't have a `type`. For example:

https://calisphere-stage.cdlib.org/item/5eb99c20-de2d-481a-a3e8-0fd2e641c3cc/

and a bunch of other objects in that collection. It might be that they're complex objects, but just wanted to flag this somewhere.

**Comment by christinklez** [comment]
@barbarahui for the record you've linked, here's the corresponding Nuxeo document: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/5eb99c20-de2d-481a-a3e8-0fd2e641c3cc/view_documents
The Nuxeo document does not have a `type`, either.

**Comment by amywieliczka** [comment]
Now that complex objects are merging correctly, this is the only object missing `type` in collection 27010: https://calisphere-stage.cdlib.org/item/8ba4bda0-cb2e-44e6-b033-f4e834db077d/ - it is also missing `type` in production: https://calisphere.org/item/8ba4bda0-cb2e-44e6-b033-f4e834db077d/
