### ISSUE TITLE
Get "more like this" working on item pages

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#805]

**Comment by christinklez** [comment]
@barbarahui this looks like it works! Going to go ahead and close this. Thank you!

Item records from a variety of collections:
https://calisphere-stage.cdlib.org/item/ark:/86086/n2z036ns/
https://calisphere-stage.cdlib.org/item/3c87988e5f37bdeb53856069f859a75f/
https://calisphere-stage.cdlib.org/item/fe36e4715c2fc9ad9ae6cabd5f93c769/
