### ISSUE TITLE
[needs discussion] decade facet is not decade-ing as expected. (Seeing specific dates instead)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#807]
Some example collections:
- Nuxeo: https://calisphere-stage.cdlib.org/collections/28043/
- Nuxeo: https://calisphere-stage.cdlib.org/collections/28197/
- Nuxeo: https://calisphere-stage.cdlib.org/collections/28199/
- non-Nuxeo: https://calisphere-stage.cdlib.org/institution/49/items/
- non-Nuxeo: https://calisphere-stage.cdlib.org/institution/251/items/

**Comment by amywieliczka** [comment]
This is the result of punting on #197

**Comment by christinklez** [comment]
Discussed on March 14 that we will revisit the Decade-ing enrichment post-MVP, including strategies to pick up the Decade calculations in harvested collections (e.g., re-harvest or other strategies?)

Strategy for MVP:
- Harvested collections will have dates (as specified in the harvested metadata)
- In the frontend, rename the "Decade" facet label to "Date" #812
- ETL collections will have calculated decade values #813

**Comment by christinklez** [comment]
We previously already discussed temporarily renaming "Decade" to "Date"
