### ISSUE TITLE
[bug] content harvester is possibly not creating thumbnails for `physicalobject` types (linked Nuxeo collections as examples)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#809]
The frontend seems to need direction for type `physical object` -- I think the legacy system treated these as images, since that's how they are digitally represented, for the most part. (Or, I'm unsure if the object viewer is getting direction from elsewhere, such as Nuxeo document type.)

Here are some examples, all of which are brand new to Rikolti:
- [ ] 28197: https://calisphere-stage.cdlib.org/collections/28197/ -- This collection has 1 complex object, with 0 main content files & 10 component objects. The main content file is set to `physical object` https://nuxeo.cdlib.org/nuxeo/nxdoc/default/1d668a51-2be1-447a-baad-b897d310a67f/view_documents 
   - Run ID: manual__2024-03-12T18:49:04+00:00
- [ ] 28199: https://calisphere-stage.cdlib.org/collections/28199/ -- This collection has 23 objects, many of which are complex. The main content file is set to `physical object` https://nuxeo.cdlib.org/nuxeo/nxdoc/default/359d4688-f210-46a4-b6c5-139dd7b7e33a/view_documents
   - Run ID: manual__2024-03-12T19:07:22+00:00
- [ ] 28201: https://calisphere-stage.cdlib.org/collections/28201/ -- This collection has 7 objects, many of which are complex. The main content file is set to `physical object` https://nuxeo.cdlib.org/nuxeo/nxdoc/default/359d4688-f210-46a4-b6c5-139dd7b7e33a/view_documents
   - Run ID: manual__2024-03-12T20:11:52+00:00

Here's an example collection that was harvested through the legacy system:
- [ ] 26864: https://calisphere.org/collections/26864/ -- This collection has 107 objects, many of which are complex. The main content file is set to `physical object` https://nuxeo.cdlib.org/nuxeo/nxdoc/default/04aa4743-3f32-4566-9c70-693e05f925b4/view_documents
   - I tried to get this into -stage but ran into a `content_harvest` error (see #783)

**Comment by barbarahui** [comment]
It looks like `thumbnail` is not getting into the metadata during the content harvest, even though `thumbnail_source` is populated:

https://search-rikolti-rzmyz6hutev35hrn33azom7oxy.us-west-2.es.amazonaws.com/rikolti-stg/_search?q=collection_url:28199

**Comment by amywieliczka** [comment]
`thumbnail_source` specifies a source of "empty_picture.png": https://search-rikolti-rzmyz6hutev35hrn33azom7oxy.us-west-2.es.amazonaws.com/rikolti-stg/_search?q=collection_url:28199 

As a rule, we don't harvest placeholder images like the "empty_picture.png" Nuxeo image:
![Image](https://github.com/ucldc/rikolti/assets/172857/9cefda17-09af-4982-aa84-5273f6111a18)

**Comment by barbarahui** [comment]
@amywieliczka oh whoops, I totally missed that it was empty_picture.png

**Comment by christinklez** [comment]
Closing as these `physicalobject` records are digitally represented as images, and are displaying in the object viewer.
