### ISSUE TITLE
Content Harvester make_jp2 failed: width or height exceeds limit

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/rikolti#817]
[This issue broken out from #783]

## Error notes from 2024 March 12
26864 is running into issues during the `content_harvest` task.

- Log for 26864-[page 29](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T20%3A33%3A10%2B00%3A00&num_runs=100&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=29) - [permanent link to content_harvest map index 29](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-12T20%3A33%3A10%2B00%3A00&map_index=29)
   - The log seems to indicate the error is happening while running this Nuxeo complex object record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/4e820d82-4282-4e29-bfeb-c894fa72fc04/view_documents -- this complex object includes 17 objects.
   - 18-017-109.tif seems to be the object that's experiencing errors: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/405c77b1-d153-45a3-b861-5bd53655835f/view_documents
   - Record on -prod: https://calisphere.org/item/4e820d82-4282-4e29-bfeb-c894fa72fc04/ -- specific object: https://calisphere.org/item/4e820d82-4282-4e29-bfeb-c894fa72fc04/?order=6
   - The error message is:
```
make_jp2 command failed: ['/usr/bin/convert', '-quiet', '-format', '-jp2', '-define', 'jp2:rate=10', '/tmp/18-017-109.tif[0]', '/tmp/18-017-109.jp2']
returncode was: 1
output was: 
convert: width or height exceeds limit `/tmp/18-017-109.tif' @ error/cache.c/OpenPixelCache/3909.
convert: no images defined `/tmp/18-017-109.jp2' @ error/convert.c/ConvertImageCommand/3229.

"; 13557)
```

**Comment by amywieliczka** [comment]
I was able to reproduce this error using a local content harvester docker container by running from the `rikolti` folder:

```
$ docker build -f Dockerfile.content_harvester -t rikolti/content_harvester .
$ cd content_harvester
$ vi env.local
# add AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, NUXEO_USER, NUXEO_PASS
$ source env.local
$ docker compose run -d content_harvester
```

Then from Docker Desktop > Containers > Container > Exec tab, or however you want to run a command on the container: 

```
$ python3 -m content_harvester.by_page '26864' '["26864/vernacular_metadata_2024-03-12T20:33:21/mapped_metadata_2024-03-12T20:34:37/data/children/4e820d82-4282-4e29-bfeb-c894fa72fc04-0.jsonl"]' '26864/vernacular_metadata_2024-03-12T20:33:21/mapped_metadata_2024-03-12T20:34:37/with_content_urls_2024-03-12T20:41:26/' 'nuxeo.nuxeo'
```

**Comment by amywieliczka** [comment]
Pushed this directly up to main: https://github.com/ucldc/rikolti/commit/87c5c8bccc4a74079f43f0cd5d049504985c409d

**Comment by christinklez** [comment]
@amywieliczka I tried re-running this one and continue to see the same "width or height exceeds limit" message for this page. Likely related to the recent deployment not going through.

**Comment by christinklez** [comment]
The mapped index page indicated in the original issue has harvested through. Thank you!
