### ISSUE TITLE
Content Harvester make_jp2 failed: cache resources exhausted

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/rikolti#818]
[This issue broken out from #783]

## Error notes from 2024 March 4

- Log for 28198-[page 3](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-04T23%3A48%3A59%2B00%3A00&num_runs=100&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=3) - [permalink for mapped index 3](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-04T23%3A48%3A59%2B00%3A00&map_index=3)
   - The log seems to indicate the error is happening while running this Nuxeo complex object record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/b9794fa7-5104-4650-b9ca-a19216ad4d83/view_documents -- this complex object includes 10 component objects.
   -  Of the 10 component objects, the content-harvest task seems to have been able to convert 9 of the images. Here is the image that is missing: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/8d8c2294-1bb6-4fcf-9388-99f705ddac93/view_documents -- named ps002887.tif (813 MB)
   - The error message is:
```
make_jp2 command failed: ['/usr/bin/convert', '-quiet', '-format', '-jp2', '-define', 'jp2:rate=10', '/tmp/ps002887.tif[0]', '/tmp/ps002887.jp2']
returncode was: 1
output was: 
convert: cache resources exhausted `/tmp/ps002887.tif' @ error/cache.c/OpenPixelCache/4095.
convert: no images defined `/tmp/ps002887.jp2' @ error/convert.c/ConvertImageCommand/3229.

; 13527)
```

- Log for 28196-[page 11](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T01%3A00%3A46%2B00%3A00&num_runs=100&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=11) - [permanent link to content_harvest map index 11](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-05T01%3A00%3A46%2B00%3A00&map_index=11)
   - The log seems to indicate the error is happening while running this Nuxeo complex object record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/38cdc9e0-a29c-4b77-81e5-cfc9504ce90c/view_documents -- this complex object includes 5 component objects.
   - Of the 5 component objects, the content harvest task failed at the first one: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/8a7993a3-b57b-46e7-8a22-026a74029bf9/view_documents
   - The error message is:
```
make_jp2 command failed: ['/usr/bin/convert', '-quiet', '-format', '-jp2', '-define', 'jp2:rate=10', '/tmp/18-044-004.tif[0]', '/tmp/18-044-004.jp2']
returncode was: 1
output was: 
convert: cache resources exhausted `/tmp/18-044-004.tif' @ error/cache.c/OpenPixelCache/4095.
convert: no images defined `/tmp/18-044-004.jp2' @ error/convert.c/ConvertImageCommand/3229.

; 13485)
```

**Comment by amywieliczka** [comment]
I was able to reproduce this error using a local docker container talking to the s3 files:

# From within a docker container:
```
$ python3 -m content_harvester.by_page '28198' '["28198/vernacular_metadata_2024-03-04T23:51:53/mapped_metadata_2024-03-04T23:52:10/data/children/b9794fa7-5104-4650-b9ca-a19216ad4d83-0.jsonl"]' '28198/vernacular_metadata_2024-03-04T23:51:53/mapped_metadata_2024-03-04T23:52:10/with_content_urls_2024-03-04T23:53:34/' 'nuxeo.nuxeo'
$ python3 -m content_harvester.by_page '28196' '["28196/vernacular_metadata_2024-03-05T01:00:58/mapped_metadata_2024-03-05T01:01:15/data/children/38cdc9e0-a29c-4b77-81e5-cfc9504ce90c-0.jsonl"]' '28196/vernacular_metadata_2024-03-05T01:00:58/mapped_metadata_2024-03-05T01:01:15/with_content_urls_2024-03-05T01:02:10/' 'nuxeo.nuxeo'
```

**Comment by amywieliczka** [comment]
Pushed this directly up to `main`: https://github.com/ucldc/rikolti/commit/87c5c8bccc4a74079f43f0cd5d049504985c409d

**Comment by christinklez** [comment]
@amywieliczka I tried re-running these two and continue to see the same "cache resources exhausted" message for these pages.

**Comment by christinklez** [comment]
The mapped index pages indicated in the original issue are harvesting through. Thank you!
