### ISSUE TITLE
[bug] `create_stage_index` error for Nuxeo collections

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#822]
## Nuxeo collection with simple objects:
- [x] Registry ID: 28012 (1 PDF simple object)
   - mapper: nuxeo
   - Run ID: manual__2024-03-12T22:40:31+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T22%3A40%3A31%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) |  [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-12T22%3A40%3A31%2B00%3A00)
   - `Exception: 1 errors in bulk indexing 1 records: ['mapping set to strict, dynamic introduction of [format] within [media] is not allowed']`
   -  Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/78f13c2c-d6a9-410b-b4e9-c6d7c406118e/view_documents
- [x] Registry ID: 27551 (2 simple image objects)
   - mapper: nuxeo
   - Run ID: manual__2024-03-04T18:57:19+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-04T18%3A57%3A19%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) | [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-04T18%3A57%3A19%2B00%3A00) 
   - `Exception: 2 errors in bulk indexing 2 records: ['mapping set to strict, dynamic introduction of [format] within [media] is not allowed']`
   - Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/7e66c68f-6ac2-4c5b-af5b-4fda81cccd7a/view_documents
- [x] Registry ID: 27073 (1 simple video object)
   - mapper: nuxeo
   - Run ID: manual__2024-03-15T23:15:35+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-15T23%3A15%3A35%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) | [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-15T23%3A15%3A35%2B00%3A00) 
   - `Exception: 1 errors in bulk indexing 1 records: ['mapping set to strict, dynamic introduction of [format] within [media] is not allowed']`
   - Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/0423cb1e-e942-4c9f-83e0-ca262cda7cc6/view_documents
- [x] Registry ID: 27941 (7 simple audio objects)
   - mapper: nuxeo
   - Run ID: manual__2024-03-15T23:16:22+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-15T23%3A16%3A22%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) | [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-15T23%3A16%3A22%2B00%3A00) 
   - `Exception: 7 errors in bulk indexing 7 records: ['mapping set to strict, dynamic introduction of [format] within [media] is not allowed']`
   - Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/b80b2bc2-fa22-4d04-b9da-0d2531e96366/view_documents

## Additional Nuxeo collections with complex objects:
- [x] Registry ID: 27626 (Has 2 records. 1 is a simple object, 1 is a complex object)
   - mapper: nuxeo
   - Run ID: manual__2024-03-05T02:22:25+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T02%3A22%3A25%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) |  [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-05T02%3A22%3A25%2B00%3A00)
   - `Exception: 10 errors in bulk indexing 10 records: ['mapping set to strict, dynamic introduction of [format] within [media] is not allowed']`
   - Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/7b18ea0b-81d6-4ccf-bf14-30b4ce435c20/view_documents -- 10 PDFs
- [x] Registry ID: 28202 (I think these are complex objects)
   - mapper: nuxeo
   - Run ID: manual__2024-03-05T01:49:06+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T01%3A49%3A06%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) | [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-05T01%3A49%3A06%2B00%3A00) 
   - `Exception: 1 errors in bulk indexing 1 records: ['mapping set to strict, dynamic introduction of [format] within [media] is not allowed']`
   - Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/1f8c11fb-af0f-477e-8744-361f064a7596/view_documents

**Comment by amywieliczka** [comment]
Engineering work for this issue represented in #829

**Comment by amywieliczka** [comment]
This should be resolved - please re-run

**Comment by christinklez** [comment]
All collections successfully ran through the `create_stage_index` task.
