### ISSUE TITLE
[bug] `create_stage_index` error for Nuxeo collections (complex objects issue?)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#823]
## Nuxeo collection with 1 complex object:
- [x] Registry ID: 28197
   - mapper: nuxeo
   - Run ID: manual__2024-03-15T17:22:33+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-15T17%3A22%3A33%2B00%3A00&task_id=create_stage_index&num_runs=100&tab=logs) |  [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-15T17%3A22%3A33%2B00%3A00)
   - `Exception: 1 errors in bulk indexing 1 records: ['mapping set to strict, dynamic introduction of [is_shown_at] within [children] is not allowed']`

## Additional Nuxeo collections:
- [x] Registry ID: 28198
   - mapper: nuxeo
   - Run ID: manual__2024-03-04T23:48:59+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-04T23%3A48%3A59%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) | [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-04T23%3A48%3A59%2B00%3A00)
   - `Exception: 17 errors in bulk indexing 17 records: ['mapping set to strict, dynamic introduction of [is_shown_at] within [children] is not allowed']`
- [x] Registry ID: 28196
   - mapper: nuxeo
   - Run ID: manual__2024-03-05T01:00:46+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-05T01%3A00%3A46%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) | [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-05T01%3A00%3A46%2B00%3A00)
   - `Exception: 18 errors in bulk indexing 18 records: ['mapping set to strict, dynamic introduction of [is_shown_at] within [children] is not allowed']`
- [x] Registry ID: 26864
   - mapper: nuxeo
   - Run ID: manual__2024-03-12T20:33:10+00:00
   - [create_stage_index log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T20%3A33%3A10%2B00%3A00&num_runs=100&task_id=create_stage_index&tab=logs) | [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-12T20%3A33%3A10%2B00%3A00)
   - `Exception: 99 errors in bulk indexing 99 records: ['mapping set to strict, dynamic introduction of [is_shown_at] within [children] is not allowed']`

**Comment by amywieliczka** [comment]
Engineering work for this issue represented in #829

**Comment by amywieliczka** [comment]
This should be resolved - @christinklez please re-run

**Comment by christinklez** [comment]
All collections passed through the `create_stage_index` task.
