### ISSUE TITLE
[bug] `create_stage_index` errors for Rikolti ETL

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#824]
- [x] Log for [15685](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A45%3A09%2B00%3A00&task_id=create_stage_index&tab=logs) (legacy mapper: OAC) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A45%3A09%2B00%3A00)
   - Run ID: manual__2024-03-14T00:45:09+00:00
   - `Exception: 34 errors in bulk indexing 34 records: ['mapping set to strict, dynamic introduction of [facet_decade] within [_doc] is not allowed']`
- [x] Log for [19967](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A51%3A34%2B00%3A00&task_id=create_stage_index&tab=logs) (legacy mapper: OAC) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A51%3A34%2B00%3A00)
   - Run ID: manual__2024-03-14T00:51:34+00:00
   - `Exception: 100 errors in bulk indexing 100 records: ['mapping set to strict, dynamic introduction of [facet_decade] within [_doc] is not allowed']`
- [x] Log for [27423](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A52%3A47%2B00%3A00&task_id=create_stage_index&tab=logs) (legacy mapper: youtube_video_snippet) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A52%3A47%2B00%3A00)
   - Run ID: manual__2024-03-14T00:52:47+00:00
   - `Exception: 11 errors in bulk indexing 11 records: ['mapping set to strict, dynamic introduction of [facet_decade] within [_doc] is not allowed']`

**Comment by amywieliczka** [comment]
Engineering work for this issue represented in #829

**Comment by amywieliczka** [comment]
This should be resolved, please re-run

**Comment by christinklez** [comment]
All 3 collections successfully pass through the `create_stage_index` task.
