### ISSUE TITLE
[bug] `content_harvest` image size error

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#825]
- [x] Log for [27297 mapped task 3](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A54%3A58%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=3) (legacy mapper: csa-omeka) - [permanent link to create_stage_index](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-14T00%3A54%3A58%2B00%3A00&map_index=3)
   - Run ID: manual__2024-03-14T00:54:58+00:00
   - `PIL.Image.DecompressionBombError: Image size (219775150 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.`

**Comment by christinklez** [comment]
Perhaps take a look at error handling to try to get an item ID.

**Comment by aturner** [comment]
Skimming through the isShownBy URLs/file types for collection 27297 to see if there were any TIFFs -- it looks like they are all JPEGs (could be a supersize one in there, though):

[](https://harvest-stg.cdlib.org/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2227297%22&field=isShownBy&limit=1200)

**Comment by barbarahui** [comment]
This object with title `eichler_f3274_115_001` in collection 27297 has a 19.9MB thumbnail:

https://calisphere.org/item/c4b3852afa1319f81453e8709e8549cf/

The thumbnail server throws a 500 error when trying to serve up the image:

https://calisphere.org/crop/210x210/31f86e330cca408122a535b8d9afd23e

I'm guessing it's the same PIL.Image.DecompressionBombError we're getting from PIL in the content harvester.

Here's the legacy thumbnail that we harvested to S3:
https://static-ucldc-cdlib-org.s3.us-west-2.amazonaws.com/harvested_images/31f86e330cca408122a535b8d9afd23e

**Comment by christinklez** [comment]
**For this particular image:**
- download this file
- resize the image
- upload to s3

**Options to explore post-mvp:**
- temporarily increase the image size limit (would result in a CSphere record with a broken thumbnail image)
- during `content_harvesting` to resize the image (should fix the thumbnail)
- let the image pass as a non-blocking error (likely would still index the record)

**Comment by christinklez** [comment]
Thanks @barbarahui! This looks great!! Also ran this collection through to ETL, and it all looks great!

https://calisphere-stage.cdlib.org/item/c4b3852afa1319f81453e8709e8549cf/
