### ISSUE TITLE
[bug] `get_mapping_status` error message

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#826]
- [ ] registry ID: 28209
   - run ID: manual__2024-03-16T16:09:30+00:00
   - mapper type: ucsd_blacklight
   - link to [airflow grid](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-16T16%3A09%3A30%2B00%3A00&num_runs=100&task_id=mapping.get_mapping_status&tab=logs) - [permalink to log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=mapping.get_mapping_status&execution_date=2024-03-16T16%3A09%3A30%2B00%3A00)
   - `[2024-03-16, 16:53:19 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 20619 for task mapping.get_mapping_status (local variable 'version' referenced before assignment; 28981)`

**Comment by amywieliczka** [comment]
@christinklez This is not a bug. There are no items for this collection, which the `fetch_collection` and `map_page` task logs both indicate. I'm not sure what you would expect `get_mapping_status` to do when there are no records to map, and as such, no status from the mapping task. 

Should the `fetch_collection` task error if there are no items fetched?

**Comment by christinklez** [comment]
Thanks @amywieliczka! It looks like the wrong identifier snuck into the "harvest_extra_data" field. Thank you!

I'll make a note of this type of error message + suggestions to troubleshoot for when we happen to come across this again. Thanks!
