### ISSUE TITLE
[bug] Rikolti ETL mapper needs updating to parse out ID fields

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#831]
Rikolti ETL harvests are running through the full Airflow tasks, including `create_stage_index` but do not publish on -stage. Update the Rikolti ETL mapper to parse the collection ID, repository ID, & campus ID out of their corresponding URL fields. 

Rikolti ETL harvest jobs complete, but the item records don't populate in -stage.

- [x] create_stage_index Log for [15685](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A45%3A09%2B00%3A00&task_id=create_stage_index&tab=logs) - [permalink to log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A45%3A09%2B00%3A00)
   - Run ID: manual__2024-03-14T00:45:09+00:00
   - Legacy mapper: OAC
   - https://calisphere-stage.cdlib.org/collections/15685/

- [x] create_stage_index Log for [19967](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A51%3A34%2B00%3A00&task_id=create_stage_index&tab=logs) - [permalink to log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A51%3A34%2B00%3A00)
   - Run ID: manual__2024-03-14T00:51:34+00:00
   - Legacy mapper: OAC
   - https://calisphere-stage.cdlib.org/collections/19967/

- [x] create_stage_index Log for [27423](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A52%3A47%2B00%3A00&task_id=create_stage_index&tab=logs) - [permalink to log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A52%3A47%2B00%3A00)    
   - Run ID: manual__2024-03-14T00:52:47+00:00
   - Legacy mapper: youtube_video_snippet
   - https://calisphere-stage.cdlib.org/collections/27423/

**Comment by christinklez** [comment]
@amywieliczka the harvest jobs for these collections completed in Airflow, but the item records are not populating on -stage. I opened up a new issue for this (#841) but unsure now if that is duplicative of this existing issue.

Let me know if it makes sense to close this one out and keep the other (#841), or whether it makes sense to keep this one open and close the other. Thanks!

**Comment by amywieliczka** [comment]
@christinklez I closed the other as a duplicate - not planned and moved this one back to in progress.

**Comment by amywieliczka** [comment]
@christinklez I believe this is finally fixed - I'm now seeing 15685 on calisphere-stage. Could you please re-run the others (starting with the mapping step) and confirm?

**Comment by christinklez** [comment]
Thanks so much, @amywieliczka! Confirming that all 3 collections are now up on -stage!

cc: @aturner
