### ISSUE TITLE
`record_indexer` template update

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#832]
https://github.com/ucldc/rikolti/blob/main/record_indexer/index_templates/record_index_config.py

`media` and `thumbnail` path/filepath updates.

**Comment by barbarahui** [comment]
Thanks!






________________________________________
From: christine ***@***.***>
Sent: Tuesday, March 19, 2024 1:51 PM
To: ucldc/rikolti
Cc: Barbara Hui; Assign
Subject: [ucldc/rikolti] `record_indexer` template update (Issue #832)

CAUTION: EXTERNAL EMAIL

https://github.com/ucldc/rikolti/blob/main/record_indexer/index_templates/record_index_config.py

media and thumbnail path/filepath updates.
