### ISSUE TITLE
special characters in jp2 filename breaks potto-loris/frontend

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#837]
The filenames for the media in collection 28043 (Prison Pandemic) have special characters in them, which causes a frontend error. Example for `item/ark:/81235/d8bn9xg89/`:

`http.client.InvalidURL: URL can't contain control characters. '/iiif/28043/00_ALA_SantaRita_20220225_43871_00_Collection Cover (9).jp2/info.json' (found at least ' ')
"GET /item/ark:/81235/d8bn9xg89/ HTTP/1.1" 500 21137`

**Comment by barbarahui** [comment]
Fixed by this commit to `public_interface`: https://github.com/ucldc/public_interface/commit/b90fe372a4d932243f419f65c8a60534b7776338

And this commit to `potto-loris`:  https://github.com/ucldc/potto-loris/commit/b5956b91d4c50dc58e7fc4adf87db397bfe3b72d

**Comment by amywieliczka** [comment]
This seems like it's still fixed: https://calisphere-stage.cdlib.org/item/ark:/81235/d8bn9xg89/
