### ISSUE TITLE
[bug] content harvest errors `UnidentifiedImageError` messages (previous Rikolti harvests for these collections ran in success)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#838]
Two collections are running into errors during the content_harvesting stage. These collections previously went through to Rikolti; when viewing the logs, click into log run 1 (March 6) and the logs show success. These are both in -stage.

- [ ] 27143 - [link to content_harvest grid](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A54%3A58%2B00%3A00&task_id=content_harvesting.content_harvest)
   - Run ID: `manual__2024-03-05T21:18:43+00:00`
   - mapper type: `omeka.nothumb`
   - content_harvest permalink to mapped pages error logs: [701](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-05T21%3A18%3A43%2B00%3A00&map_index=701) and [809](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-05T21%3A18%3A43%2B00%3A00&map_index=989)
   - 701: `PIL.UnidentifiedImageError: cannot identify image file '/tmp/730dc7908dbb30f9e18ac336af09a413.jpg'`
   - 989: `PIL.UnidentifiedImageError: cannot identify image file '/tmp/f98a6a0f011057e206ebecb30c5e3075.jpg'`
- [ ] 27148 - [link to content_harvest grid](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-06T03%3A49%3A14%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks)
   - Run ID: `manual__2024-03-06T03:49:14+00:00`
   - mapper type: `omeka.nothumb`
   - content_harvest permalink to mapped pages error logs: [1](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-06T03%3A49%3A14%2B00%3A00&map_index=1), [2](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-06T03%3A49%3A14%2B00%3A00&map_index=2), and [3](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-03-06T03%3A49%3A14%2B00%3A00&map_index=3)
   - 1: `PIL.UnidentifiedImageError: cannot identify image file '/tmp/a3b3a58e583a985aa6b65510210a8eb2.jpg'`
   - 2: `PIL.UnidentifiedImageError: cannot identify image file '/tmp/d15d2283f6b2b3e7b7304fbe95bc30d0.jpg'`
   - 3: `PIL.UnidentifiedImageError: cannot identify image file '/tmp/772e25d5171eca8d842ee4b263cfe4dc.jpg'`

**Comment by barbarahui** [comment]
@christinklez 

The first error for collection 27143 is due to this object's `is_shown_by` url returning HTML rather than the jpg:

`is_shown_at`: https://history.santacruzpl.org/omeka/items/show/113478#?c=0&m=0&s=0&cv=0
`is_shown_by`: https://history.santacruzpl.org/omeka/files/thumbnails/730dc7908dbb30f9e18ac336af09a413.jpg

I'm guessing that the rest of the errors are due to something similar, namely that the thumbnail image is missing (?). Instead of giving a 404, the contributor's site returns HTML.

I can update Rikolti to capture information on the URL for the "image" that's causing problems, so at least you see that in the logs?

**Comment by barbarahui** [comment]
Same issue for the 2nd error in collection 27143:

`is_shown_at`: https://history.santacruzpl.org/omeka/items/show/129307
`is_shown_by`: https://history.santacruzpl.org/omeka/files/thumbnails/f98a6a0f011057e206ebecb30c5e3075.jpg

**Comment by barbarahui** [comment]
@amywieliczka I know you've done some work around how to best capture and bubble up information around errors to the airflow logs. Is there an example of this pattern in the codebase you can point me to?

**Comment by christinklez** [comment]
Hi @barbarahui, thanks for investigating! This is true the source collections include records that both have thumbnails as well no thumbnails. I think the detail in this mapper is to map only the records that have thumbnail images (and skip the ones that do not).

For example, 27143 [fetches 86,765 items](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-05T21%3A18%3A43%2B00%3A00&task_id=fetching.fetch_collection&tab=logs), but I expect it to map 35,937 items (according to a recent [validation report](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-05T21%3A18%3A43%2B00%3A00&task_id=mapping.validate_collection&tab=logs).

Here's the [omeka.no_thumb mapper](https://github.com/ucldc/rikolti/blob/0e03c4fe6a08172ed9affaf04b9f34c9bcb5d8c8/metadata_mapper/mappers/oai/omeka/nothumb_mapper.py).

**Comment by barbarahui** [comment]
@christinklez Gotcha. The Identifier for the first record getting an error is "CF-37606". It looks like this record isn't getting skipped by the mapper like it should be.

**Comment by christinklez** [comment]
If this is a mapper issue, we can plan to ETL these collections instead--let me know.

The only strange thing is that both collections passed through all the stages earlier this month, when we ran them through to -stage:

27143 on -stage: 10,000 records display, but there are likely more (harvested March 6th) -- https://calisphere-stage.cdlib.org/collections/27143/
27143 on -test: 32,712 records -- https://calisphere-test.cdlib.org/collections/27143/

27148 on -stage: 3,512 records (harvested March 6th) -- https://calisphere-stage.cdlib.org/collections/27148/
27148 on -test: 3,512 records -- https://calisphere-test.cdlib.org/collections/27148/

Let me know what you think!

**Comment by barbarahui** [comment]
@christinklez It looks like 35,937 items are getting mapped correctly for collection 27143 if you look at the airflow logs. 

The records that are causing the error are correctly **not** being skipped by the mapper. For example, the identifier for this problematic record does not contain any of the strings that the `omeka.no_thumb` mapper is looking for as a sign to skip it:

```
        "identifier": [
            "CF-37608"
        ],
        "is_shown_at": "https://history.santacruzpl.org/omeka/items/show/113478",
        "is_shown_by": "https://history.santacruzpl.org/omeka/files/thumbnails/730dc7908dbb30f9e18ac336af09a413.jpg",
```

**Comment by barbarahui** [comment]
@christinklez I don't think this is a mapper issue. I think the thumbnails must've been taken offline since you last harvested the collection. ETLing should solve the problem though.

**Comment by barbarahui** [comment]
@christinklez Here are the identifiers in the source (vernacular) metadata:

```
          <dc:identifier>CF-37608</dc:identifier>
          <dc:identifier>https://history.santacruzpl.org/omeka/items/show/113478</dc:identifier>
          <dc:identifier>https://history.santacruzpl.org/omeka/files/original/730dc7908dbb30f9e18ac336af09a413.PDF</dc:identifier>
```

File: https://rikolti-data.s3.us-west-2.amazonaws.com/27143/vernacular_metadata_2024-03-05T21%3A24%3A47/data/1387

**Comment by barbarahui** [comment]
We've decided to table this for later, but for posterity: it looks like the mapper is correctly **not** skipping these records.

**Comment by christinklez** [comment]
Moving this issue to the bottom of "to do" for now, so that we can add to this if we come across any additional examples. Otherwise, will plan to move this to the post-mvp board. Thanks!

**Comment by christinklez** [comment]
Subsumed by #881.
Barbara made it possible to gather more information in the error logs. (Thank you!)
The issues we are experiencing are due to errors on the contributor platform side. Closing this issue out, and we will confer with Santa Cruz Public Libraries on next steps.
