### ISSUE TITLE
[bug] Rikolti ETL'd item records don't populate in -stage

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#841]
Rikolti ETL harvest jobs complete, but the item records don't populate in -stage.

- [ ] create_stage_index Log for [15685](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A45%3A09%2B00%3A00&task_id=create_stage_index&tab=logs) - [permalink to log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A45%3A09%2B00%3A00)
   - Run ID: manual__2024-03-14T00:45:09+00:00
   - https://calisphere-stage.cdlib.org/collections/15685/

- [ ] create_stage_index Log for [19967](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A51%3A34%2B00%3A00&task_id=create_stage_index&tab=logs) - [permalink to log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A51%3A34%2B00%3A00)
   - Run ID: manual__2024-03-14T00:51:34+00:00
   - https://calisphere-stage.cdlib.org/collections/19967/

- [ ] create_stage_index Log for [27423](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A52%3A47%2B00%3A00&task_id=create_stage_index&tab=logs) - [permalink to log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=create_stage_index&execution_date=2024-03-14T00%3A52%3A47%2B00%3A00)
    - Run ID: manual__2024-03-14T00:52:47+00:00
   - https://calisphere-stage.cdlib.org/collections/27423/

**Comment by amywieliczka** [comment]
Duplicate #831
