### ISSUE TITLE
[bug] From a given item record page, Rikolti ETL records `is_shown_at` URL points to itself, instead of the external source record URL

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#845]
## Expected
Item records should have a link that points to its original data source or DAMS.

## What's happening
Item records have a link that circles to the current item record page we're already on, on -stage. For example,
- This OAC record: https://calisphere-stage.cdlib.org/item/ark:/13030/tf0f59n4hb/
   - The `is_shown_at` link points to https://calisphere-stage.cdlib.org/item/ark:/13030/tf0f59n4hb/
   - It should point to: http://oac.cdlib.org/ark:/13030/tf0f59n4hb/?brand=oac4
   - Record on -test: https://calisphere-test.cdlib.org/item/ark:/13030/tf0f59n4hb/
- This YouTube record: https://calisphere-stage.cdlib.org/item/2d127a351007071272723c58995f6cf5/
   - The `is_shown_at` link points to: https://calisphere-stage.cdlib.org/item/2d127a351007071272723c58995f6cf5/ 
   - It should point to: https://www.youtube.com/watch?v=CkLkqzhuo2w
   - Record on -test: https://calisphere-test.cdlib.org/item/2d127a351007071272723c58995f6cf5/

## List of Rikolti ETL collections on -stage. (i.e., task list for Christine to rerun.)
- [x] [15685 airflow run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A45%3A09%2B00%3A00&tab=logs)
   - Run ID: manual__2024-03-14T00:45:09+00:00
   - Legacy mapper: OAC
   - https://calisphere-stage.cdlib.org/collections/15685/

- [x] [19967 airflow run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A51%3A34%2B00%3A00&tab=logs)
   - Run ID: manual__2024-03-14T00:51:34+00:00
   - Legacy mapper: OAC
   - https://calisphere-stage.cdlib.org/collections/19967/

- [x] [27423 airflow run](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=100&dag_run_id=manual__2024-03-14T00%3A52%3A47%2B00%3A00&tab=logs)
   - Run ID: manual__2024-03-14T00:52:47+00:00
   - Legacy mapper: youtube_video_snippet
   - https://calisphere-stage.cdlib.org/collections/27423/

**Comment by barbarahui** [comment]
Fixed with this PR: https://github.com/ucldc/rikolti/pull/847

**Comment by christinklez** [comment]
Thanks @barbarahui! Harvested all three ETL collections, and the items are now all pointing to their source records. Thank you!!

cc: @aturner
