### ISSUE TITLE
Product Management: how the full text (and search) works/feature specs from the front-end/end user perspective

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/rikolti#86]

**Comment by aturner** [comment]
Draft scoping notes: https://docs.google.com/document/d/1isdL3D1qR79FkxPexpjFxPqnnMOSNXKaPkvDsO4b9K4/edit?usp=sharing

**Comment by aturner** [comment]
Draft discussion/presentation points for 6/16 Calisphere/DAMS user group meeting: https://docs.google.com/document/d/1CkmmXYI1fuDW23YL1qoQN6ts_sCrsmrWB8HzmGF4Wyg/edit?usp=sharing
