### ISSUE TITLE
[bug] ETL'd collections do not get listed in the institution landing page

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#862]
The following institutions have ETL'd collections:
- Oakland Museum of California: https://calisphere-stage.cdlib.org/institution/94/collections/
   - https://calisphere-stage.cdlib.org/collections/15685
- Corona Public Library: https://calisphere-stage.cdlib.org/institution/63/collections/
   - https://calisphere-stage.cdlib.org/collections/19967
- Harrison Memorial Library: https://calisphere-stage.cdlib.org/institution/279/collections/
   - https://calisphere-stage.cdlib.org/collections/27423
- California State Archives: https://calisphere-stage.cdlib.org/institution/153/collections/
   - https://calisphere-stage.cdlib.org/collections/27297
- Santa Cruz Public Libraries: https://calisphere-stage.cdlib.org/institution/245/collections/
   - https://calisphere-stage.cdlib.org/collections/27148
   - https://calisphere-stage.cdlib.org/collections/27143
   - Note that SCPL does have one collection listed, which was not ETL'd. 

These ETL'd collections exist on -stage, but are not listed on the institution landing page. They are found in the collections browse list.

**Comment by amywieliczka** [comment]
Just checked all these against production calisphere and confirmed that all the Collections are listed in the institution landing page now.
