### ISSUE TITLE
[to do] Test and compare search experience for complex objects (parent- & component-level) search in OpenSearch

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#865]
Note that OpenSearch does not search nested fields. (Barbara thinks we won't get these at this point.)

**Comment by aturner** [comment]
I'm not able to verify that we're currently supporting searching of component-level metadata in current CSphere prod/Solr:

Searching for "Those who mourn the loss of these gone" in component Transcription (https://calisphere.org/search/?q=Those%20who%20mourn%20the%20loss%20of%20these%20gone) 
or searching for "18650101" in component TItle (https://calisphere.org/search/?q=18650101)

... should pull up this item:

Henry O. Nightingale diary, 1864 
https://calisphere.org/item/ark:/13030/kt4b69r9x7/

(Date and Transcription snippets are in the component at https://calisphere.org/item/ark:/13030/kt4b69r9x7/?order=14 )

**Comment by christinklez** [comment]
Agree with Adrian. It looks like CSphere prod/Solr does not support search queries within component objects.

From this complex object record:
- on prod: https://calisphere.org/item/ark:/86086/n2kw5fss/?order=20
- on stage: https://calisphere-stage.cdlib.org/item/ark:/86086/n2kw5fss/?order=20

I tried to search, `curivsc_ms096_002_gf_1943_021` (identifier)
- prod: https://calisphere.org/search/?q=curivsc_ms096_002_gf_1943_021 - 0 results
- stage (sitewide): https://calisphere-stage.cdlib.org/search/?q=curivsc_ms096_002_gf_1943_021

I also tried to search a partial phrase, `Lot of people all dressed up today` (transcription)
- prod: https://calisphere.org/search/?q=Lot%20of%20people%20all%20dressed%20up%20today - 2 results, but not for the record I'm looking for.
- stage (sitewide): https://calisphere-stage.cdlib.org/search/?q=Lot%20of%20people%20all%20dressed%20up%20today - A LOT of results, from 2,571 collections. I think OpenSearch needs to be refined a bit more.
- prod (Fujimoto diaries only): https://calisphere.org/collections/81/?q=&sort=a&rq=Lot%20of%20people%20all%20dressed%20up%20today -- 0 records
- stage (Fujimoto diaries only): https://calisphere-stage.cdlib.org/collections/81/?rq=Lot%20of%20people%20all%20dressed%20up%20today -- 46 records (there are 46 in this collection)

**Comment by christinklez** [comment]
Closing as completed. New issue created (post-mvp board) with next steps to strategize what component objects searching means: https://github.com/ucldc/rikolti/issues/978
