### ISSUE TITLE
[bug] Complex objects carousels do not display thumbnails for PDF & video objects

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#866]
See examples:

Broken carousels -- PDF thumbnail not displaying in multiple browsers (Firefox, Chrome, Safari, etc.), ex: https://calisphere-stage.cdlib.org/item/ark:/81235/d8fj29s3q/

Ex 2: MP4 and PDF broken: 
https://calisphere-stage.cdlib.org/item/ark:/81235/d8v40kc5f/

**Comment by barbarahui** [comment]
The fix for this is deployed to -stage and -test

**Comment by christinklez** [comment]
The carousel thumbnails look great--thank you!
