### ISSUE TITLE
[bug] Type facet capitalization issues: mapper update to lower-case all type values

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#883]
New issue created from the proposed options here: https://github.com/ucldc/rikolti/issues/863#issuecomment-2067380416

Option 1:

In calisphere_solr.calisphere_solr, replace https://github.com/ucldc/rikolti/blob/main/metadata_mapper/mappers/calisphere_solr/calisphere_solr_mapper.py#L40 type: self.source_metadata.get("type", None) with type: [lower(t) for t in self.source_metadata.get('type', None)]
In solr_updater, replace
[rikolti/metadata_mapper/mappers/mapper.py](https://github.com/ucldc/rikolti/blob/466f1c0516d4a71a23fb9309628bedc62d137812/metadata_mapper/mappers/mapper.py#L1496)

Line 1496 in [466f1c0](https://github.com/ucldc/rikolti/commit/466f1c0516d4a71a23fb9309628bedc62d137812)

 'type': filter_blank_values(record.get('type')), 
'type': filter_blank_values(record.get('type')) with 'type': [lower(t) for t in filter_blank_values(record.get('type'))]
Write a one-off script for reading every record in OpenSearch and updating the type field to be lowercase
This wouldn't hold up harvesting - if harvesting continues, we will use the one-off script to fix more records than currently exist, but we have records that need fixing anyway.

One implication, though: in the legacy harvester, we had a "raw" type value (type), as well as a normalized, lowercase type value (type_ss). As far as @barbarahui and I can tell, the "raw" type value was never used anywhere except for in the item level metadata display. We may lose some instances of capitalized type for some records if we choose to normalize the type field. It's really impossible to figure out how widespread instances of a capitalized "raw" type value - many mappers already normalize type to a lowercase value anyway. We were able to find this one instance, though: https://calisphere.org/item/9a25f3bd3e1d97e88869404d5b497e67/.

**Comment by barbarahui** [comment]
@christinklez @aturner The mapper update is deployed to Airflow and any records you harvest from now onward should have their `type` field value(s) lower-cased. Maybe you could re-harvest a small collection that's known to have uppercase type values just to verify everything looks good?

**Comment by christinklez** [comment]
Thank you! We'll test this out with some collections that are currently on -stage.

- `Image` (708): https://calisphere-stage.cdlib.org/collections/26654/
- `Text` (3): https://calisphere-stage.cdlib.org/collections/26707/
- `Dataset` (1): https://calisphere-stage.cdlib.org/collections/28206/

**Comment by christinklez** [comment]
Reharvested these three collections; including results:

- `image` (715) & `sound` (1): https://calisphere-stage.cdlib.org/collections/26654/
- `text` (3): https://calisphere-stage.cdlib.org/collections/26707/
- `dataset` (1): https://calisphere-stage.cdlib.org/collections/28206/

The fix looks great! Thank you!
