### ISSUE TITLE
[bug] placeholder image does not display in the frontend for Nuxeo objects; in Nuxeo, the doctype is `text` but has `png` files

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#887]
These two Nuxeo collections have a placeholder image (PNG) instead of a content file. The issue seems to be that in Nuxeo, these document types are "text" (instead of "image").

The placeholder image is not displaying, and instead there are broken objects appearing in place of the placeholder image.

I am able to click "download text" and download the image file from -stage.

26109:
-stage: https://calisphere-stage.cdlib.org/collections/26109
-prod: https://calisphere.org/collections/26109

26117:
-stage: https://calisphere-stage.cdlib.org/collections/26117
-prod: https://calisphere.org/collections/26117

It seems the legacy harvester somehow supported a "text" document with an "image" main file; the resulting frontend page using the PDF/text viewer logic (instead of the image viewer). Would it be possible to support this with Rikolti as well?

==
(harvesting in progress, need to check how this looks. Suspect this will be fine, as the placeholder images are in Nuxeo image document types.)
27124:
-stage: https://calisphere-stage.cdlib.org/collections/27124
-prod: https://calisphere.org/collections/27124

**Comment by barbarahui** [comment]
Ohh, it's because the frontend determines whether or not the item is hosted based on mapper type. I can update the mapper type in OpenSearch to `nuxeo.nuxeo` for this one record. It's a bit hacky, and if you re-ETL this record it will break the viewer again but I think it's acceptable compromise for now?

**Comment by barbarahui** [comment]
@christinklez Can you re-run the content harvest step for this collection? I updated the content harvester so it should create thumbnails based on the placeholder png image now.

**Comment by christinklez** [comment]
@barbarahui This looks great! Collection landing page has thumbnails, and the image displays on the item record page! (It also downloads just fine.) Thank you!

https://calisphere-stage.cdlib.org/collections/26109/

**Comment by christinklez** [comment]
Quick update that both collections harvested through and look great!

https://calisphere-stage.cdlib.org/collections/26109/
https://calisphere-stage.cdlib.org/collections/26117

Thank you!
