### ISSUE TITLE
[file format issue] `500` errors for records in collection `27` (missing `.mov` extension) & `27795` (convert `m4v` to `mp4` within Nuxeo)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#888]
## Video file 500s

- [x] https://calisphere-stage.cdlib.org/collections/27
   - Clicking to view the item record pages results in a 500 error.
   - Here's the collection on production: https://calisphere.org/collections/27
   - Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/5b191b9e-8135-4b46-ad57-340e7ea03bfc/view_documents
   - UCI is reconstructing the `.mov` object: https://help.oac.cdlib.org/a/tickets/137544

- [x] https://calisphere-stage.cdlib.org/collections/27795
   - Clicking to view some (not all) complex object video results in a 500 error.
   - Example record: https://calisphere-stage.cdlib.org/item/ark:/81235/d8b27q477/
   - Nuxeo (m4v file): https://nuxeo.cdlib.org/nuxeo/nxdoc/default/243626ba-cbab-4f53-a75f-3e0f5875ca95/view_documents
   - Here's the collection on production: https://calisphere.org/collections/27795

***

## Audio file 500s

- [x] https://calisphere-stage.cdlib.org/collections/40/
   - Clicking to view complex object audio pages results in a 500 error.
   - Here's the collection on production: https://calisphere.org/collections/40/

- [x] https://calisphere-stage.cdlib.org/collections/26855
   - Clicking to view complex object audio pages results in a 500 error.
   - Here's the collection on production: https://calisphere.org/collections/26855

**Comment by christinklez** [comment]
Audio 500s fixed via #892!

**Comment by barbarahui** [comment]
This is a content harvester issue. The only movie format it is set up to handle is `video/mp4`. I can add `video/quicktime`.

**Comment by barbarahui** [comment]
The frontend is expecting all hosted audio, video and file objects to have a thumbnail. I think we need to run a report at some point to validate that all of these objects do indeed have a thumbnail, or maybe the content harvester should throw an error if it can't create one.

**Comment by barbarahui** [comment]
Oh, it looks like you should get a message in the airflow logs for the content harvester task if it isn't able to create a thumbnail: 

`ERROR: no thumbnail found for {record_type} record {calisphere-id} in page {mapped_page_path}`

The content_harvest mapped task won't actually throw an error though, so the task will be marked "success".

**Comment by barbarahui** [comment]
@christinklez Can you try reharvesting nuxeo collection(s) with quicktime content files to see if this issue is fixed?

**Comment by christinklez** [comment]
Reharvested!

In collection 27, this item record still results in a 500:
- https://calisphere-stage.cdlib.org/item/ark:/81235/d8ms5b/
- Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/1bb0e8e0-182a-40ce-8756-c747512b683d/view_documents
(The other items in the collection work great!)

Collection 26711 is still churning.

**Comment by christinklez** [comment]
@barbarahui here's the latest list of file formats supported by Nuxeo, which are hopefully also supported in Calisphere:
https://help.oac.cdlib.org/support/solutions/articles/9000100797-creating-objects

We can update this list if there are file formats that aren't supported in Calisphere.

**Comment by barbarahui** [comment]
The content harvester thinks that this video content file is of type `application/octet-stream`, and so doesn't know how to create a thumbnail for it, and the frontend handles this ungracefully.

It's possible that if you try changing adding `.mov` to the filename in Nuxeo, it will be recognized properly. You'll have to then reharvest the collection from scratch.

**Comment by christinklez** [comment]
Thank you! I can't find a way to edit the filename directly in Nuxeo--we may need to download, change the filename, and upload it back. Or, perhaps Paul can script something. I'll ask them!

**Comment by christinklez** [comment]
@barbarahui for 27795, would you be able to add `m4v` as a video format?

**Comment by barbarahui** [comment]
I'm not sure why the nuxeo derivative creation process wasn't triggered for the objects in these collections when they were uploaded. I went ahead and clicked convert for these 3 m4v videos, and they now have mp4 derivatives, which the mapper should pick up:

https://nuxeo.cdlib.org/nuxeo/nxdoc/default/cca761a2-91f6-4f5b-987a-b0de9f8abaa9/view_documents
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/160b4d0d-82df-469b-b848-1a65bd3b0991/view_documents
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/160b4d0d-82df-469b-b848-1a65bd3b0991/view_documents

This does mean you'll have to reharvest the collection starting with the mapping though. If we run into more m4v videos then we can add it to the content harvester as a valid format.

**Comment by christinklez** [comment]
Thanks @barbarahui! Using the Nuxeo-app converter to produce mp4's (out of the m4v's) worked! Adding a note/reminder to self that we also need to reharvest from scratch when this happens.

**Comment by christinklez** [comment]
UCI updated the content file with a`.mov` extension. Harvested the collection, but awaiting the shard error to make sure the record looks good on -stage.

**Comment by christinklez** [comment]
Both collections are now on -stage.
