### ISSUE TITLE
[bug] Error for complex object audio components

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#892]
Click on one of the audio components for this object:
https://calisphere-stage.cdlib.org/item/ark:/81235/d8fj29s3q/

I think this is just happening for audio components.

**Comment by christinklez** [comment]
Possibly related: #888

**Comment by barbarahui** [comment]
Ready for review on calisphere-stage

**Comment by christinklez** [comment]
Thanks @barbarahui ! This also fixed the audio file issues listed in #888! (Video file 500s remain.)
