### ISSUE TITLE
Content harvest failure: 1 item (ETL collection #26819) - "no thumbnail found for ['text']record"

### ISSUE THREAD

**Issue by aturner** [ucldc/rikolti#894]
**Collection registry number:** #26819

**Rikolti mapper type:** ETL

**Airflow Run ID:** manual__2024-04-25T20:15:22+00:00

**Airflow Run:** https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-25T20%3A15%3A22%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=18

**Notes:**
The run errors out at the content harvesting stage. Out of 3712 items, it looks like 1 item (or 2 items) are failing:

Exception: PIL.UnidentifiedImageError for calisphere-id oai:rekloa:rekl_96883: cannot identify image file '/tmp/d41d8cd98f00b204e9800998ecf8427e'
Harvesting content for 100 records at 26819/vernacular_metadata_2024-04-25T20:40:39/mapped_metadata_2024-04-25T20:40:56/data/18.jsonl
ERROR: no thumbnail found for ['text']record oai:rekloa:rekl_13102 in page 26819/vernacular_metadata_2024-04-25T20:40:39/mapped_metadata_2024-04-25T20:40:56/data/18.jsonl; 12250)

I can't locate rekl_96883 or rekl_13102 in the mapped metadata.

rekl_96883 doesn't appear to ever have been published to CSphere. Here's rekl_13102:  https://calisphere.org/item/7c57e55af844538cad59ceac4357f0b1/

**Comment by barbarahui** [comment]
There are 2 different issues here. The mixture of error messages is pretty confusing. You can see the metadata for both of these objects in this file: `26819/vernacular_metadata_2024-04-25T20:40:39/mapped_metadata_2024-04-25T20:40:56/data/18.jsonl`

**rekl_13102**
The solr record doesn't have a reference_image_md5 in it, so there isn't a thumbnail for this object. The content harvester is alerting you about that. This is just a message; it doesn't actually hold up the content harvester (as we discussed earlier in stand-up)

Here's the object on calisphere:
https://calisphere.org/item/7c57e55af844538cad59ceac4357f0b1/

**rekl_96883**
Oddly, the thumbnail we currently have stashed on S3 for this object is empty (0 bytes). I have no idea how this happened. The content harvester doesn't know what to do with this, so it throws an error.

Here's the object on calisphere; as you can see, there is no thumbnail:
https://calisphere.org/item/826356349027b401df0f67e87e9aa2ed/

Here is the object on the contributor site: https://digital.lib.calpoly.edu/010-1-c-04-06-27

We could download a thumbnail from here and upload it to S3 to fix the problem manually like we did for another object a while ago. Lmk if you'd like me to do that.

**Comment by aturner** [comment]
Thanks @barbarahui ! Whew re: rekl_13102 -- I'll be more mindful of that particular error message! Re: rekl_96883, the edit-and-forget it approach (manual stashing of a thumbnail) sounds good to me!

**Comment by barbarahui** [comment]
@aturner I've uploaded a jpeg: https://calisphere.org/clip/500x500/d41d8cd98f00b204e9800998ecf8427e

You should be able to rerun that failed content harvester task now.

**Comment by aturner** [comment]
Thanks @barbarahui -- just re-ETL'ed and it sailed through fine! Done deal
