### ISSUE TITLE
[bug] investigate `t` `e` `x` `i` `m` `a` `g` type faceting in the frontend

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#895]
https://calisphere-stage.cdlib.org/search/?q=

These facets found in (all harvested today, 4/25):
University of the Pacific
Palm Springs Public Library
San Jose State University

**Comment by barbarahui** [comment]
This should be fixed now. You'll need to re-harvest the affected collections starting from the mapping step. (No need to re-run the fetcher).

**Comment by christinklez** [comment]
Thank you so much! I just tested out on one collection first (https://calisphere-stage.cdlib.org/collections/26715) -- this resolves the type faceting & the icon placeholder. Also re-harvested starting from the mapping step. Thank you!!
