### ISSUE TITLE
[bug] content harvest error for 2 Nuxeo collections (no space left / failed to seek in the stream)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#898]
These are both extremely large collections, with hundreds of pages in complex objects.

## Collection 26771
- Error seems to be on this record: `uclaclark_fDA660W35S4v2_0268.tif`
- Nuxeo record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/fbc3fc9e-4b8e-4d26-8c29-f312b4b90251/view_documents
- Run ID: manual__2024-04-25T02:33:38+00:00
   - Mapped task: 5
   - Gridview to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-25T02%3A33%3A38%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=5
   - Permalink to the error: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-25T02%3A33%3A38%2B00%3A00&map_index=5

**Error log for 26771 `uclaclark_fDA660W35S4v2_0268.tif`**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 104, in harvest_record_content
    downloaded_md5 = download_content(request, http, thumbnail.tmp_filepath)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 203, in download_content
    f.write(block)
OSError: [Errno 28] No space left on device
/tmp/uclaclark_fDA660W35S4v2_0267.tif converted to /tmp/uclaclark_fDA660W35S4v2_0267.jp2
Mime-type 'image/tiff' was pre-checked and recognized as something we can try to convert.
--------------------------------
ERROR: make_jp2 command failed: ['/usr/bin/convert', '-quiet', '-format', '-jp2', '-define', 'jp2:rate=10', '/tmp/uclaclark_fDA660W35S4v2_0268.tif[0]', '/tmp/uclaclark_fDA660W35S4v2_0268.jp2']
returncode was: 1
output was: 
convert: Failed to seek in the stream.
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194.
convert: unable to encode image file `/tmp/uclaclark_fDA660W35S4v2_0268.jp2' @ error/jp2.c/WriteJP2Image/1141.
convert: unable to write file `/tmp/uclaclark_fDA660W35S4v2_0268.jp2' @ error/constitute.c/WriteImage/1353.
--------------------------------; 8388)
[2024-04-26, 04:48:03 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
```

## Collection 27124
- Error seems to be on this record: `sim_181_000_012_0031.tif`
- Nuxeo record: 
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/78c4be3a-c5fc-45a0-90ef-9abdcc449479/view_documents
- Run ID: manual__2024-04-24T17:18:21+00:00
   - Mapped task: 48
   -Gridview to the log: [https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-25T02%3A33%3A38%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=5](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-24T17%3A18%3A21%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=48)
   - Permalink to the error: [https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-25T02%3A33%3A38%2B00%3A00&map_index=5](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-24T17%3A18%3A21%2B00%3A00&map_index=48)

**Error log for 27124 `sim_181_000_012_0031.tif`**
```
/tmp/sim_181_000_012_0030.tif converted to /tmp/sim_181_000_012_0030.jp2
Mime-type 'image/tiff' was pre-checked and recognized as something we can try to convert.
--------------------------------
ERROR: make_jp2 command failed: ['/usr/bin/convert', '-quiet', '-format', '-jp2', '-define', 'jp2:rate=10', '/tmp/sim_181_000_012_0031.tif[0]', '/tmp/sim_181_000_012_0031.jp2']
returncode was: 1
output was: 
convert: Failed to seek in the stream.
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194.
convert: unable to encode image file `/tmp/sim_181_000_012_0031.jp2' @ error/jp2.c/WriteJP2Image/1141.
convert: unable to write file `/tmp/sim_181_000_012_0031.jp2' @ error/constitute.c/WriteImage/1353.
--------------------------------
[2024-04-25, 07:13:17 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=48, execution_date=20240424T171821, start_date=20240424T174602, end_date=20240425T071317
[2024-04-25, 07:13:17 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: 355885a2-5265-54a9-869d-db0656a8a647
[2024-04-25, 07:13:17 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 78597 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
/tmp/sim_181_000_011_0050.tif converted to /tmp/sim_181_000_011_0050.jp2

```

**27124 also has the "no space left" error**
```
/tmp/sim_181_000_012_0003.tif converted to /tmp/sim_181_000_012_0003.jp2
Mime-type 'image/tiff' was pre-checked and recognized as something we can try to convert.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 104, in harvest_record_content
    downloaded_md5 = download_content(request, http, thumbnail.tmp_filepath)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 203, in download_content
    f.write(block)
OSError: [Errno 28] No space left on device
/tmp/sim_181_000_012_0004.tif converted to /tmp/sim_181_000_012_0004.jp2

```

**Comment by barbarahui** [comment]
It looks like the `No space left on device` error is actually fine -- the machine recovers and the jp2 is written to S3.

The `convert: Failed to seek in the stream.` error is a problem though. There's something about the tif file that OpenJP2 doesn't like. Are these new tiffs, or are they on calisphere prod? Just wondering if our legacy conversion tool was able to handle them.

**Comment by christinklez** [comment]
27124 is also on production:
- Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/89235286-24b6-4e78-9c52-ac435d769a9c/view_documents
- on -test: https://calisphere-test.cdlib.org/item/ark:/86086/n21z4672/?order=30

**Comment by barbarahui** [comment]
I am able to run the jp2 conversion process successfully in a content harvester docker container running on my local machine, so it looks like the out of space error is actually the issue. We deleting the files in /tmp after each file is processed.

I think we need to use Fargate's ephemeral storage:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html

Looks like we would do this by configuring the docker container with `tmp_dir` and `mount_tmp_dir: True`:

https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/_api/airflow/providers/docker/operators/docker/index.html

**Comment by barbarahui** [comment]
@christinklez This should be fixed now. You can try re-running the content harvester just for the failed mapped tasks.

**Comment by christinklez** [comment]
Thanks @barbarahui! I think your fix is good! However, I re-ran both failed pages (at the same time) and after running for 12 hours and 8 minutes, they both seem to just stop running.

SIM: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?base_date=2024-04-24T17%3A18%3A21%2B00%3A00&dag_run_id=manual__2024-04-24T17%3A18%3A21%2B00%3A00&task_id=content_harvesting.content_harvest&map_index=48&tab=logs

Clark: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?base_date=2024-04-25T02%3A33%3A38%2B00%3A00&dag_run_id=manual__2024-04-25T02%3A33%3A38%2B00%3A00&task_id=content_harvesting.content_harvest&tab=logs&map_index=5

I can try running each of these individually overnight (and not at the same time) to see if that helps. Feel free to let me know if you have other ideas!

**Comment by barbarahui** [comment]
I don't think that re-running the content harvest for those pages is going to help. I'm guessing you'll run into the same error again once it hits the 12 hour mark. 

Airflow is configured to keep pinging ECS for 24 hours, but something happens at 12 hours that causes the task to stop. Based on the messages at the very end of the logs, it looks like Airflow is trying to re-run the task, but can't because it's already running. And then it stops, either immediately (in the case of 26771) or soon after (in the case of 27124).

**Comment by christinklez** [comment]
Thanks @barbarahui! I let 27124 run overnight on just that one task, and it finished! It did take 12h23m47s.

I'll try letting 26771's one task run solo as well.

**Comment by christinklez** [comment]
I do think when running multiple harvests, the job is competing for Nuxeo resources.

For 27124, attempt number 3 stopped after this file:
`/tmp/sim_190_000_007_0088.tif converted to /tmp/sim_190_000_007_0088.jp2`-- so presumably, it took 12 hours to get here.

Attempt number 4 got through this file at around the 5 hour mark (and continues on to churn through the remaining files, of which there are many more).

Here's the `[log to this mapped task 48](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?base_date=2024-04-24T17%3A18%3A21%2B00%3A00&dag_run_id=manual__2024-04-24T17%3A18%3A21%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=48)`, in case it is of interest!

**Comment by barbarahui** [comment]
Looks like it finished successfully this time!

**Comment by barbarahui** [comment]
Based on the errors in the logs, I still think the errors have something to with Airflow mismanaging lots of concurrent tasks (maybe specifically dynamic tasks?). Not sure what's going on there, and it concerns me because this is exactly what Airflow's job is supposed to be. We don't want to have to coordinate with other users of Airflow once other PAD services start using it. Anyway, we can run these big pages overnight on their own for now just to get it through, but I think we'll need to figure it out post-MVP.

**Comment by christinklez** [comment]
Thanks so much, @barbarahui! Each of the Nuxeo super-sized mapped pages did complete, when run individually!

26771's page5 content harvest took 9h31m44s
27124's page48 content harvest took 12h23m27s.

Is it okay if we close this out for now, and open up a new issue if we run into this again (and if running a solo job doesn't help)?

**Comment by barbarahui** [comment]
Sounds good!
