### ISSUE TITLE
When running any harvest (ETL, Nuxeo, non-Nuxeo) as of 4/29, getting a `maximum shards open` error message at the `create_stage_index` stage

### ISSUE THREAD

**Issue by aturner** [ucldc/rikolti#907]
**Issue:**
When running any (?) ETL-based harvests today (starting around noon), I'm getting a pretty consistent error message at the very last "create_stage_index" stage relating to a max'ing of shards:

`"[2024-04-29, 23:52:26 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 99123 for task create_stage_index (100 errors in bulk indexing 100 records: ['Validation Failed: 1: this action would add [3] total shards, but this cluster currently has [3000]/[3000] maximum shards open;']; 3226) [2024-04-29, 23:52:26 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1"`

Below are some example Run IDs, with associated links to the particular stage and log reports. This is happening consistently, with different collections/contributors:

**Collection IDs:**
27853
27731
26263

**Run IDs:**
manual__2024-04-29T20:18:30+00:00  
manual__2024-04-29T20:18:49+00:00
manual__2024-04-30T00:51:36+00:00

**Links:**
https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-29T20%3A18%3A30%2B00%3A00&task_id=create_stage_index&base_date=manual__2024-04-29T20%3A18%3A30%2B00%3A00

https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-29T20%3A18%3A49%2B00%3A00&task_id=create_stage_index&base_date=manual__2024-04-29T20%3A18%3A49%2B00%3A00

https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-30T00%3A51%3A36%2B00%3A00&task_id=create_stage_index&base_date=manual__2024-04-30T00%3A51%3A36%2B00%3A00

**Comment by christinklez** [comment]
Do we need more shards? Do we need bigger shards? Do we need to look at how we "shard our data"? (Am I using the word "shard" properly?)
https://opensearch.org/blog/optimize-opensearch-index-shard-size/

**Comment by barbarahui** [comment]
It looks like we need to add more capacity in the form of nodes/shards!

**Comment by barbarahui** [comment]
@amywieliczka @bibliotechy I did some math on how many nodes our cluster needs to have. Here's what I came up with. If you could check it for sanity that'd be great:

**How we're using up our current 3000 shards**
Our cluster currently has 3 nodes. Each node has 1000 shards (the max that OpenSearch allows. We're using all 3000. To see how we're using them, run `GET _cat/shards`.
- each index has 1 primary and 2 replica shards
- we currently have 852 collections on stage. 852 * 3 = 2556. Plus some of the collections have 2 indices. Plus there are miscellaneous kibana and reports related indices. All of this accounts for 3000 shards.

**Shard size and shards per node configuration**
We have configured each of our indices to use 1 shard. The recommendation is to keep shard size between 10-30G for cases where search latency is the objective. Our largest index right now is 36M, so 1 shard per index seems fine for us. It also sounds fine that we have the default number of shards (1000) per node. See this documentation: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/sizing-domains.html#bp-sharding

**Number of indices per collection**
Eventually, we can expect to have up to 3 indices per collection:
- 1 production
- 1 stage
- 1 old retained index

**How many shards/node we need**
To support the number of collections currently on production, I think we need to increase our cluster to 23 nodes:

2539 collections * 3 indices * 3 shards = 22851 shards needed
At 1000 shards per node, that's 23 nodes

We are harvesting new collections that are not currently on production. Plus we need room to grow. We could increase to 23 and add more when we get there, or add a couple more in anticipation.

**Comment by barbarahui** [comment]
I'm actually wondering if we should specify 1 primary shard and 1 replica shard for a total of 2 shards per index. Right now we're not specifying the number of replicas and I guess it defaults to 2:

https://github.com/ucldc/rikolti/blob/main/record_indexer/index_templates/record_index_config.py

AWS documentation recommends 1 replica if it's not a read-heavy workload: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/sizing-domains.html#bp-storage

**Comment by bibliotechy** [comment]
oof. 23 nodes is gonna be expensive!

**Comment by amywieliczka** [comment]
Hmmm, I was going to ask about reducing to one replica per index, but I would characterize our workload as pretty read-heavy. 

Is it an option to have 1 replica for stg and increase to 2 replicas when we promote a stg index to prod, and decrease to 1 replica again when we demote an index to a retained index? At 2539 collections * (2 stg shards + 2 retained shards + 3 prod shards) = 17,773 shards, or 18 nodes. That would save us 5 nodes. 

We could also rethink our indexing strategy and maintain an index per institution instead of an index per collection? I don't think we'd have shard size constraints: if our largest collection index is only 36MB, an institution would need to have 227 collections that were all the same size as that 36MB collection before we would hit the 10GB threshold, let alone the 30GB threshold, for an institution index.

At 391 institutions (https://registry.cdlib.org/repositories/) at 3 indices each with 2 replicas, that would be 3,519 shards, or 4 nodes. 

The cost is that our writes would go way up, since each time we'd harvest a collection, we'd have to re-write all the other collections at that institution to the index in order to maintain the immutability of our indicies.

**Comment by barbarahui** [comment]
>> Is it an option to have 1 replica for stg and increase to 2 replicas when we promote a stg index to prod, and decrease to 1 replica again when we demote an index to a retained index?_

Well, the number of shards/replicas is defined at index creation time, and cannot be modified. We'd have to actually create a new index to change the number of replicas.

>> We could also rethink our indexing strategy and maintain an index per institution instead of an index per collection?

We could certainly do this, but yeah, it would definitely be a more complex model than what we currently have.

**Comment by barbarahui** [comment]
@christinklez You should be able to create new collection indices now. Can you try running the `create_stage_index` task for one of the collections that failed to verify?

**Comment by christinklez** [comment]
Confirming that we're able to re-run only the `create_stage_index` task, from the existing harvest run. Super fast! Thank you!
