### ISSUE TITLE
[bug] Rikolti does not seem to fetch/harvest all items within a Nuxeo folder (deeply nested records?)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#908]
The harvester does not seem to be picking up all the records in a Nuxeo project folder -- there are many folders within the project folder.

We want to harvest all the records in this Nuxeo folder: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/a73960b5-4c69-460e-b816-d59e0130dd7b/view_documents

-test: 33,733 items currently on [production](https://calisphere-test.cdlib.org/collections/26713/)
-stage: 1,521 items harvested to [stage](https://calisphere-stage.cdlib.org/collections/26713/)
- Run ID: manual__2024-04-25T01:03:29+00:00
- Fetch log details: `[2024-04-25, 01:06:16 UTC] {{logging_mixin.py:150}} INFO - 26713 : success,   101 pages,   1521 items,  33733 solr items, -32212 lost items, solr count last updated: May 02, 2023 15:26:50.129314`
- [Airflow gridview](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?base_date=2024-04-25T01%3A03%3A29%2B00%3A00&dag_run_id=manual__2024-04-25T01%3A03%3A29%2B00%3A00)

For example, these records did not get harvested to stage `Slides/S01862`: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/9b457399-a89a-4d34-8f12-b2f89e8b0901/view_documents (these appear on the first page of the collection browse page on -test)

But these records did get harvested to stage `Slides/S01103`: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/2d2c1b9c-9cb4-4ec9-a16f-820172eaf2de/view_documents (these appear on the first page of the collection browse page on -stage)

***

Side note:
- on registry, the "harvest extra data" is: `asset-library/UCI/SCA_UniversityArchives/AS-061/Slides`
- UCI (last week) moved this folder to: `asset-library/UCI/SCA_UniversityArchives/AS-061/Do Not Publish (items were found with no metadata)/Slides/` -- we had a miscommunication about another collection that is rooted here `asset-library/UCI/SCA_UniversityArchives/AS-061/`
- What is currently on -stage is from when the Nuxeo folder was located here: `asset-library/UCI/SCA_UniversityArchives/AS-061/Slides`
- I'll be asking them to move the `Slides` folder out of the `Do Not Publish` folder

As a result, I've temporarily updated the Registry "harvest extra data" to `asset-library/UCI/SCA_UniversityArchives/AS-061/Do Not Publish (items were found with no metadata)/Slides/`

**Comment by barbarahui** [comment]
@christinklez It sounds like this is a data entry issue?

**Comment by christinklez** [comment]
Well, even without the data entry issue (which is when I initially harvested this collection) there are many, many missing records.

I do need to ask them to move the folder over. But we're still not harvesting all the contents of the objects in the Nuxeo folder.

**Comment by barbarahui** [comment]
Gotcha. OK, I can take a look at what's going on.

**Comment by christinklez** [comment]
I'll update the Nuxeo folder in the Registry while you investigate (to point to where they currently have it stashed in Nuxeo!) Thank you!

**Comment by christinklez** [comment]
Harvest extra data endpoint temporarily updated to:
`/asset-library/UCI/SCA_UniversityArchives/AS-061/Do Not Publish (items were found with no metadata)/Slides`

Was: `/asset-library/UCI/SCA_UniversityArchives/AS-061/Slides` (Christine needs to ask UCI to move this project folder back, but wants to provide accurate item counts as well.)

**Comment by barbarahui** [comment]
@christinklez This should be fixed. I didn't test it completely on my local machine though because the collection is huge. Let me know if you run into any issues.

**Comment by christinklez** [comment]
Thanks so much @barbarahui! I let this harvest overnight and all looks good!
