### ISSUE TITLE
[bug] UCM (2) & UCR (1) collections: `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Container Overrides length must be at most 8192`

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#936]
`botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Container Overrides length must be at most 8192`

## UCM UCCE Fresno 27767
- Registry: `/asset-library/UCM/UCCE/Fresno`
- Nuxeo permalink: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/7fc1146c-7b7d-4d62-af7f-60627f50122d/view_documents
- Nuxeo document count: 2,899
- Fetch log count: `[2024-05-10, 05:28:54 UTC] {{logging_mixin.py:150}} INFO - 27767 : success,  2941 pages,  29068 items,   2898 solr items,     1 new items, solr count last updated: May 02, 2023 15:26:48.778362`
- Run ID: manual__2024-05-10T05:08:14+00:00
- [Airflow Gridview](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-05-10T05%3A08%3A14%2B00%3A00&base_date=2024-05-10T05%3A08%3A14%2B00%3A00)
- 48 (out of 50) map index failures during the content harvesting task
- [Permalink to map index 1 error log only](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-05-10T05%3A08%3A14%2B00%3A00&map_index=1)
   - Note: I also tried running this one solo, but got the same results. 

## UCM UCCE Madera 27809
- Registry: `/asset-library/UCM/UCCE/Madera/`
- Nuxeo permalink: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/11fdd588-641c-4f7b-a311-afdddba42951/view_documents
- Nuxeo document count: 2,999
- Fetch log count: `[2024-05-10, 15:14:25 UTC] {{logging_mixin.py:150}} INFO - 27809 : success,  3010 pages,  20340 items,   2998 solr items,     1 new items, solr count last updated: May 02, 2023 15:26:49.412028`
- Run ID: manual__2024-05-10T14:58:06+00:00
- [Airflow Gridview](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-05-10T14%3A58%3A06%2B00%3A00&base_date=2024-05-10T14%3A58%3A06%2B00%3A00)
- 48 (out of 50) map index failures during the content harvesting task
- [Permalink to map index 1 error log only](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-05-10T14%3A58%3A06%2B00%3A00&map_index=1)

## UCR Sherman Indian Museum 27124
- Registry: `/asset-library/UCR/SpecialProjects/SIM/`
- Nuxeo permalink: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/11fdd588-641c-4f7b-a311-afdddba42951/view_documents
- Nuxeo document count: 13,726
- Fetch log count: `[2024-05-14, 01:33:44 UTC] {{logging_mixin.py:150}} INFO - 27124 : success,  2640 pages,  45930 items,  13726 solr items,   0 same extent, solr count last updated: May 02, 2023 15:26:48.940802`
- Run ID: manual__2024-05-14T00:56:07+00:00
- [Airflow Gridview](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-05-14T00%3A56%3A07%2B00%3A00&base_date=2024-05-14T00%3A56%3A07%2B00%3A00)
- 44 (out of 50) map index failures during the content harvesting task
- [Permalink to map index 5 error log only](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-05-14T00%3A56%3A07%2B00%3A00&map_index=5)

**Comment by barbarahui** [comment]
Ohh, we're running into an issue with these collections being so huge that the payload to ECS exceeds the size limit. I think we'll have to do what @amywieliczka proposed and re-architect things so that we pass a prefix and then the filepaths (?) so that the payload is smaller.

**Comment by barbarahui** [comment]
@christinklez Can you try re-running?

**Comment by christinklez** [comment]
@barbarahui kicked off a harvest job! The map index pages didn't insta-fail once we got to the `content-harvest` task, so things are looking good! Will update tomorrow once the job churns through. Thanks!

**Comment by christinklez** [comment]
All three of these collections are now through to -stage!
