### ISSUE TITLE
[bug] image `type` icon not always coming through (when an image does not get thumbnailed) - these are type `image`

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#940]
Examples:
- https://calisphere-stage.cdlib.org/item/d888f373753328521381e59eb1bd9ec0/
- https://calisphere-stage.cdlib.org/item/39d28ffa90c196277ed3b0c345739656/

Oddly, this one does have an image icon! https://calisphere-stage.cdlib.org/collections/194/?q=&sort=a&rq=ark%3A%2F81235%2Fd80n8h

**Comment by barbarahui** [comment]
@christinklez this should be fixed now

**Comment by christinklez** [comment]
This looks great, thank you so much!
