### ISSUE TITLE
[bug?] Nuxeo object (audio complex object) results in a 500 item record page

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#942]
This collection: https://calisphere-stage.cdlib.org/collections/27694

The record with the grey thumbnail tile `ark:/86086/n2668g9r/` results in a 500 page

Here's the Nuxeo object: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/5ba475e3-5cd4-4830-8fa2-dd5eb0f550a8/view_documents 

Here's the object on production: https://calisphere.org/collections/27694/ (grey thumbnail tile in the results)
Item record page: https://calisphere.org/item/ark:/86086/n2668g9r/

***

Run ID: manual__2024-05-14T00:33:44+00:00

**Comment by barbarahui** [comment]
@christinklez this should be fixed now.

**Comment by christinklez** [comment]
This item record page now opens. Thank you so much!
