### ISSUE TITLE
Update by Query script to modify `sort_collection_data` for ETL'd collections

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/rikolti#948]
This work would fix #862, #861, and #947 for collections already in the OpenSearch index, but would not fix re-harvests of ETL'd content - re-harvests of ETL'd content are resolved by PR #946. 

To summarize the issues detailed in #862, #861, and #947, there are two issues with the ETL'd mapper's mapping of the `sort_collection_data` field:

------

Issue 1: (seen in #862, #861, and #947)
For ETL'ed collections, we have `sort_collection_data` values in the index that looks like this: `california revealed from oakland museum of california::California Revealed from Oakland Museum of California::https:://registry.cdlib.org/api/v1/collection/26262/`

For other collections, we have `sort_collection_data` values in the index that look like this: `ctsa digital audio archive::CTSA Digital Audio Archive::26466`

We need to modify all the existing `sort_collection_data` values to remove the `https:://registry.cdlib.org/api/v1/collection/` part (along with the trailing /), or re-harvest all ETL collections.

------

Issue 2: (seen in #861 and #947)
For ETL'ed collections, we have `sort_collection_data` values in the index that look like this: `california of the past alameda::California of the Past:: Alameda::https:://registry.cdlib.org/api/v1/collection/27162/`. Even after resolving Issue 1, we'd still have `california of the past alameda::California of the Past:: Alameda::27162` - note the `::` between "California of the Past" and " Alameda". 

We want to have `california of the past alameda::California of the Past: Alameda::27162`

We need to modify all the existing `sort_collection_data` values to replace the `::` special delimiter character with `:` in the Collection display name, or re-harvest all 44 ETL collections that have a `:` character in their name.

**Comment by amywieliczka** [comment]
I think this is the sort of script we want to write:

For each collection ID that's been ETL'd, verify that `registry.cdlib.org` is in the `sort_collection_data` field, and that the `sort_collection_data` field is an array of length 1: 

GET _search
```json
{
  "query": {"terms": {"collection_url": ["26262"]}}, 
  "aggs": {
    "sort_collection_data": {
      "terms": {
        "field": "sort_collection_data", 
        "size": 10000, 
        "order": {"_key": "asc"}
      }
    }
  }
}
```

check that there is exactly 1 value for the sort_collection_data field across all records of this collection:
`len(response.aggregations.sort_collection_data.buckets) == 1`

(if not, let's fail the script and look at this collection manually?)

check that the number of records with this 1 sort_collection_data value is the same as the number of records with this collection ID: 
`response.aggregations.sort_collection_data.buckets[0].doc_count == response.hits.total.value`

(if not, let's fail the script and look at this collection manually?)

check that the sort_collection_data field value (incorrectly) has the full collection URL instead of the collection ID:
`"registry.cdlib.org" in response.aggregations.sort_collection_data.buckets[0].key`

(if not, let's fail the script, presumably this collection has a good value for `sort_collection_data`, but maybe we want to double check that manually?)

check if the sort_collection_data field value (incorrectly) has a double colon in the collection name:
len(response.aggregations.sort_collection_data.buckets[0].key.split("::")) > 4 (we check against 4 because, even though sort_collection_data should only have 3 parts, we've already ascertained that `registry.cdlib.org` exists in the value, so presumably `http:://registry.cdlib.org` exists in the value, resulting in 4 parts: `<sortable collection name>`, `<collection name>`, `http`, `//registry.cdlib.org...`, and if a colon exists in the collection name, then we'll have more than 4 parts) 

If the value only has the first problem (the full URL problem), we can compose a new value by:

sort_collection_data_parts = response.aggregations.sort_collection_data.buckets[0].key.split("::")
new_value = [f"{sort_collection_data_parts[0]}::{sort_collection_data_parts[1]::{collection_id}"]

If the value has both problems (the full URL problem and a colon in the collection name), we can compose a new value by:

if len(sort_collection_data_parts) > 5
    # this is some sort of collection name with multiple colons in the name, and we should fail the script and look at this manually
new_value = [f"{sort_collection_data_parts[0]}::{sort_collection_data_parts[1]}:{sort_collection_data_parts[2]::{collection_id}"]

then we can update: 

POST _update_by_query
```json
{
  "query": {"terms": {"collection_url": ["26262"]}},
  "script": {
    "source": "ctx._source.sort_collection_data = params.data",
    "lang": "painless",
    "params": {
      "data": <new_value>
    }
  }
}
```

**Comment by barbarahui** [comment]
This looks good to me. It looks similar to the approach I've taken before and wrote some notes on here: https://github.com/ucldc/rikolti/tree/main/record_indexer#opensearch-index-record-updates

The only tweak I might make is to use a `term` rather than `terms` query in the case(s) where you're searching for records with a given collection ID, i.e.:

```
{
  "query": {"term": {"collection_url": "26262"}}
}
```

I was wondering if we could write a reusable script for updating by query, but I feel like every case is going to be slightly different so not sure that we can generalize it...

**Comment by amywieliczka** [comment]
@barbarahui ohhh, hrm, I tried running this in the OpenSearch UI's Dev Tools Console as your docs describe, but I encountered a permissions issue.

**Comment by barbarahui** [comment]
@amywieliczka Hrm, which user were you logged in as? I think it'd have to be the master user (credentials are stored in AWS Secrets Manager).

**Comment by bibliotechy** [comment]
@amywieliczka Agree, this approach seems like the right one to me.
