### ISSUE TITLE
[to do] A way to delete collections from -stage (collections that won't get published when we cutover)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#957]
To do: Barbara will write up a script to delete these two collections.

Currently have two collections that need to be deleted:

- [x] 27633: Sequoia & Kings Canyon, Civilian Conservation Corps Collection. This was not published in production, and is not marked as "ready for publication" in Registry -- I accidentally harvested this.
- [x] 26684: Pepperdine University, Historic Sound Recordings. Pepperdine switched platforms and the item record URLS pointing to their old system point to a ContentDM login page.

Some options to consider:
- Delete from -stage?
- Delete from -prod?
- Block a collection on -stage from getting promoted to -prod?
- Should it work with the Registry "ready for publication" checkbox?

Some ideas discussed for cutover purposes (short term):
- A dag or script that deletes a collection by registry ID? 
- At this point, should be independent of the Registry.

Long term:
- We need to strategize post-mvp. See #960 (post-mvp board).

***

Side notes:
- Deleting one-off item records: That sounds like a dag. This is a different issue. Would be great if harvest operators can do this.
   - To create a new issue for post-mvp. See #961 in the post-mvp board.
- One-off metadata updates: Also post-mvp, see #962

**Comment by barbarahui** [comment]
@christinklez These 2 collections have been deleted from stage

**Comment by christinklez** [comment]
Thank you! Looked at both collections and they have no records. Thanks so much!
