### ISSUE TITLE
[to do] finalize labels for empty "type" and "date" values - `date information not supplied` & `type information not supplied`

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#959]
Sitewide empty search: https://calisphere-stage.cdlib.org/search/?q=

Current labels:
- `date value not supplied`
- `type value not supplied`

Let's discuss and finalize labels!

Other ideas:
- `no date information`
- `no type information`
- `no date information provided`
- `no type information provided`
- `not supplied by contributor`

**Comment by christinklez** [comment]
Hi @amywieliczka ! When you have a moment, would you be able to update these to:

`date information not supplied`
`type information not supplied`

Thank you!

**Comment by amywieliczka** [comment]
Deploying to -stage and -test now!
