### ISSUE TITLE
[chore] delete collections from the -prod index

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#970]
## Remove from -stage & -prod candidate - 6 collections
- Chula Vista Public Library [5 collections: `is_shown_at` URLs do not resolve to the contributor platform
   - [ ] 26482
   - [ ] 26481
   - [ ] 26480
   - [ ] 26477
   - [ ] 18598
- My experimental collection [1 collection]
   - [ ]  28281

## Remove from -prod candidate (privacy takedown issue) - NA
- NA

## New collections not yet approved for publication; remove from -prod candidate only - 39 collections
- UCB EDA [6 collections]
   - [ ] 28197
   - [ ] 28198
   - [ ] 28199
   - [ ] 28200
   - [ ] 28201
   - [ ] 28196
- UCB ESL [1 collection]
   - [ ] 28234
- UCI [1 collection]
   - [ ] 28043
- UCSF [4 collections]
   - [ ] 28012
   - [ ] 28203
   - [ ] 28204 
   - [ ] 28205
- UCLA [27 collections]
   - [ ] 28227
   - [ ] 28228
   - [ ] 28229
   - [ ] 28230
   - [ ] 28231
   - [ ] 28232
   - [ ] 28233
   - [ ] 28254
   - [ ] 28255
   - [ ] 156
   - [ ] 26899
   - [ ] 28183
   - [ ] 28184
   - [ ] 28185
   - [ ] 28186
   - [ ] 28187
   - [ ] 28188
   - [ ] 28189
   - [ ] 28190
   - [ ] 28193
   - [ ] 28194
   - [ ] 28256
   - [ ] 28257
   - [ ] 28258
   - [ ] 28192
   - [ ] 28277
   - [ ] 28278

**Comment by christinklez** [comment]
@amywieliczka this list has been updated. Please remove from the production candidate. Thank you!

**Comment by amywieliczka** [comment]
This is done!
