### ISSUE TITLE
Calisphere contributor update/messaging: cutover timelining

### ISSUE THREAD

**Issue by aturner** [ucldc/rikolti#974]
Cutover plan notes: https://docs.google.com/document/d/1vE7yY-fgr0lu7FmTjbxJWCrh9Tm3oZhRSh1ad35EeGA/edit

**Comment by aturner** [comment]
Supported harvest methods and platforms (Freshdesk - DRAFT): https://help.oac.cdlib.org/support/solutions/articles/9000081695-supported-harvest-methods-and-platforms/preview#Digital-collections-platforms-that-Calisphere-currently-harvests-from

CSphere harvesting system upgrade (Freshdesk - DRAFT): https://docs.google.com/document/d/1bexVEcCkD_3xfwod4c-8ZDUU1f9Sz4JAeBArdAg30qo/edit?usp=sharing

**Comment by christinklez** [comment]
DRAFT emails: https://docs.google.com/document/d/1kP1cL1E7KpcKBuXKkWkqJXqW8MDjI1CaU78LXRTNs6g/edit#heading=h.544gvu2wuqf9

- first new index publication (pre-cutover)
- first new index publication (immediate post-cutover)
