### ISSUE TITLE
Facilitate harvesting & QA/preview of harvest requests (new collections & reharvests)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#976]
Spreadsheet to track incoming harvest requests: https://docs.google.com/spreadsheets/d/1srdWgX4NxAFEgYlhpPxXvZCqVQTwV2dga1wh2-wlAGs/edit#gid=0

When we begin to request QA / share preview links, let's also start building out the "preview collections on -stage" section in the harvesting operations doc: https://docs.google.com/document/d/1grOS3ifpi03Kj3CMd4sGtXbqf_ylkTqrNbkT6ZyRl6Q/edit#heading=h.ueda5ryn1b7c

## Nuxeo
| Contributor | # of NEW collections | # Completed | # Approved | - | # of Reharvests | # Completed | # Approved |
| --- | --- | --- | --- | --- | --- | --- | --- |
| UCB EDA | 6 | 6 | tbd | - | 0 | NA | NA |
| UCB ESL | 1 | 1 | tbd | - | 0 | NA | NA |
| UCI | 2 | 2 | 1 of 2 | - | 0 | NA | NA |
| UCSF | 4 | 4 | tbd | - | 3 | 3 | tbd |
| UCM | 0 | NA | NA | - | 1 | 1 | tbd |

## Non-Nuxeo
| Contributor | # of NEW collections | # Completed | # Approved | - | # of Reharvests | # Completed | # Approved |
| --- | --- | --- | --- | --- | --- | --- | --- |
| UCSD | 57 | 57 | 57 | - | 2 | 2 | 2 |
| UCLA | 30 | 28 | tbd | - | 4 | 3 | tbd |

## FD threads
- UCB EDA: https://help.oac.cdlib.org/a/tickets/132766
- UCB ESL: https://help.oac.cdlib.org/a/tickets/136394
- UCI: https://help.oac.cdlib.org/a/tickets/138991
- UCSF: https://help.oac.cdlib.org/a/tickets/138992
- UCM: https://help.oac.cdlib.org/a/tickets/136869
- UCLA: https://help.oac.cdlib.org/a/tickets/138997
- UCSD: 
   - Gabriela has reviewed & approved!
   - Cristela: https://help.oac.cdlib.org/a/tickets/135346

**Comment by aturner** [comment]
Draft messaging: https://docs.google.com/document/d/1b1IsAhHxbK3O0OMLCjI_27uYKka3CiYG8Ed78KMWs6g/edit?usp=sharing

**Comment by christinklez** [comment]
We emailed out requests to review/QA collections on -stage. We will be responsive to any updates or inquiries. Closing this as done for the MVP index.
