### ISSUE TITLE
[chore] Load testing, including thumbnail server speed, IIIF,etc.

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#984]
See comparison times for top keywords searched in Calisphere: https://docs.google.com/spreadsheets/d/12oailNshmaaSabXwaMupniZreR-VCZUmwSpaDEZlFsg/edit#gid=502686028

**Comment by bibliotechy** [comment]
Crop / Clip server is super robust. 
Threw 200 simultaneous users at it, ~100 req/sec and it didn't even blink. Avg response time under heavy load  was ~125ms. 

|Type|Name|# Requests|# Fails|Median (ms)|95%ile (ms)|99%ile (ms)|Average (ms)|Min (ms)|Max (ms)|Average size (bytes)|Current RPS|Current Failures/s|
|--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |
|GET|/clip500x500|14916|4|51|230|460|82.08|11|1519|49031.11|39.2|0|
|GET|/crop120x120|7405|1|52|220|430|87.51|12|1747|6829.34|18.7|0|
|GET|/crop210x210|7550|4|59|230|420|91.89|12|1485|17903.42|19.4|0.1|
||Aggregated|29871|9|53|230|440|85.91|11|1747|30701.69|77.3|0.1|
