### ISSUE TITLE
[bug?] Nuxeo component object ordering is not retained in Calisphere complex object viewer

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#985]
Expect to see the Nuxeo component object sort order being retained in the Calisphere item viewer.

Nuxeo fetcher code: https://github.com/ucldc/rikolti/blob/main/metadata_fetcher/fetchers/nuxeo_fetcher.py#L91

## Nuxeo

Nuxeo object:
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/06e49f86-fd49-43d6-82b9-14f07094eada/view_documents

Expected ordering of component objects:
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/62dd76d9-c6da-44e7-9cdf-06e20f771812/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/12eb8ea7-dd7e-462a-89d4-bfe734ccc53f/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/9bc7e6c4-b8ff-403a-b1b5-a3208bd70cd3/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/778247cf-7523-4764-bea3-fc7452117827/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/64474fe1-7b72-4305-a63c-f72329a40eff/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/5b92c2e6-2531-41b9-ad58-bbde8b8c3574/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/c38a3ebc-bb11-4d39-8ed6-b66271c7a11a/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/9e878848-6ee5-474d-b267-1ad2a6a630cb/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/5a3c40f2-fec4-4490-a4e8-f482046b03e7/view_documents
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/e2b98cdf-329f-412b-87a0-dbc8efdc139f/view_documents

## Calisphere-stage

Calisphere-stage object:
https://calisphere-stage.cdlib.org/item/06e49f86-fd49-43d6-82b9-14f07094eada/?order=0

Order of records in the vernacular metadata:
- "uid":"5a3c40f2-fec4-4490-a4e8-f482046b03e7"
- "uid":"778247cf-7523-4764-bea3-fc7452117827"
- "uid":"e2b98cdf-329f-412b-87a0-dbc8efdc139f"
- "uid":"12eb8ea7-dd7e-462a-89d4-bfe734ccc53f"
- "uid":"9e878848-6ee5-474d-b267-1ad2a6a630cb"
- "uid":"c38a3ebc-bb11-4d39-8ed6-b66271c7a11a"
- "uid":"9bc7e6c4-b8ff-403a-b1b5-a3208bd70cd3"
- "uid":"5b92c2e6-2531-41b9-ad58-bbde8b8c3574"
- "uid":"62dd76d9-c6da-44e7-9cdf-06e20f771812"

**Comment by christinklez** [comment]
I recreated 3 UCB EDA objects, all of which are complex objects that are not displaying in the intended Nuxeo order. (Stage has a different order.)

## Experiment 1: Blake Estate: Long Range Development Plan - Manually uploaded each component in order
- Original record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/06e49f86-fd49-43d6-82b9-14f07094eada/view_documents
- Test record:
   - Note: This was created via manually upload through the Nuxeo UI. Each component object was uploaded in the current order displaying in Nuxeo. 

## Experiment 2: Cole, Fraser - manual upload (order of how they are listed in stage), then reorder (to how they are listed in Nuxeo)
- Original record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/cf56d5e9-b688-42f7-981e-32c551783183/view_documents
- Test record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/6add5380-ede2-4f43-9bf3-176da9d7510e/view_documents
   - Note: This was created via manually upload through the Nuxeo UI. I uploaded the component objects **in the order they appear on -stage**; once uploaded, I then reordered the objects to the intended Nuxeo sequence (to match the original).

Initial upload sequence:
![Image](https://github.com/ucldc/rikolti/assets/32110172/8e0e07ba-39a4-48c7-af48-6d2b08d5863d)

"Fixed" (to match original Nuxeo record) sequence:
![Image](https://github.com/ucldc/rikolti/assets/32110172/363f5ea2-9f2c-4cd1-a7fe-223e932b5679)

## Experiment 3: Eckbo, Garrett (ALCOA Forecast) - file uploader, then reorder in the UI
- Original record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/17eef353-3469-45a3-a64d-973e982dda87/view_documents
- Test record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/2b276827-f506-4fdc-91b7-d6b451021bbe/view_documents
   - Note: The parent object was created in the Nuxeo UI first. Then, I used the File Uploader client to upload all 14 objects (which I had locally saved). I then went into the Nuxeo UI to name and reorder these objects, to the intended Nuxeo order.
  
**Note that my hunch is UCB EDA created these objects by uploading via the File Uploader client. I'm pretty certain of this given that the component objects filepath all have the original filenames (set by the very initial document title).**
Initial upload sequence:
![Image](https://github.com/ucldc/rikolti/assets/32110172/7b77c055-a6e5-42f4-b57d-2a9a4d336cc7)

Renamed the component objects (still in uploaded sequence):
![Image](https://github.com/ucldc/rikolti/assets/32110172/5c3a1e76-2123-4f71-a4c8-726ec840cbe1)

"Fixed" (to match original Nuxeo record) sequence:
![Image](https://github.com/ucldc/rikolti/assets/32110172/822398eb-de26-410b-b7b0-76412cd84911)

**Comment by barbarahui** [comment]
I tried fetching the metadata for the Eckbo object, and the children are in order!!

@amywieliczka noticed that the order of the child components in the left sidebar in nuxeo doesn't match the order on the main page for the parent object, by the way. As we know, there are issues with ordering in Nuxeo...I'm not sure what method in particular is causing the problem.

**Comment by barbarahui** [comment]
It turns out that the `@search` nuxeo API endpoint returns component objects in the wrong order sometimes. The `search/lang/NXQL/execute` endpoint described here returns them in the correct order: https://doc.nuxeo.com/nxdoc/search-endpoints/#searching-by-query

This PR updates the API endpoint for the query that gets the child component objects: https://github.com/ucldc/rikolti/pull/994

**Comment by barbarahui** [comment]
Once it's deployed, we'll need to reharvest Nuxeo collections with the component ordering issue. @christinklez I don't suppose you have an exhaustive list of which collections are affected? I'm sure it's really hard to figure out just by looking at the website. I could write a script to compare the ordering for all collections...

**Comment by barbarahui** [comment]
OpenSearch query for Nuxeo collections with complex objects:
```
GET rikolti-stg/_search
{
  "query": {
    "nested": {
      "path": "children",
      "query": {
        "match_all": {}
      }
    }
  },
  "aggs": {
    "collection_ids": {
      "terms": {
        "field": "collection_url",
        "size": 10000
      }
    }
  },
  "size": 0
}
```

**Comment by christinklez** [comment]
28197 reharvest results: The ordering is significantly better! But there were two objects that were not in the correct sequence.

Expect (according to Nuxeo): 
![Image](https://github.com/ucldc/rikolti/assets/32110172/e4dfeac1-c395-4dc4-97a7-d98b32b90c5a)

Actual (on -stage):
Items 7 & 8 ordering (on -stage) is swapped: https://calisphere-stage.cdlib.org/item/06e49f86-fd49-43d6-82b9-14f07094eada/?order=6
- 7 of 10: Intermediate Deveolpment Plan - should be 8 of 10
- 8 of 10: [site plan - rose garden area] - should be 7 of 10

**Comment by christinklez** [comment]
28199 reharvest results:

Cole, Fraser record sequence matches Nuxeo: https://calisphere-stage.cdlib.org/item/cf56d5e9-b688-42f7-981e-32c551783183/

Eckbo, Garrett (ALCOA Forecast) record sequence matches Nuxeo: https://calisphere-stage.cdlib.org/item/17eef353-3469-45a3-a64d-973e982dda87/

**Comment by christinklez** [comment]
I sample QA'd three more UCB EDA collections:
- 28198
- 28201
- 28196

Each of these collections have at least one record with component objects that do not match the Nuxeo sequence. I reharvested all three collections (with the updated Nuxeo endpoint) and the Nuxeo sequence now matches the -stage sequence.

These are screen captures from *before* the reharvest (i.e., before the Nuxeo endpoint update), which show that the Nuxeo sequence did not match the -stage sequence:


![Image](https://github.com/ucldc/rikolti/assets/32110172/93836330-863e-41f8-b298-0100ab1c77f5)

![Image](https://github.com/ucldc/rikolti/assets/32110172/0761e83e-e781-48f5-bc05-0fb5e7242d00)

![Image](https://github.com/ucldc/rikolti/assets/32110172/3273998f-8032-4a4e-aa0c-9b762ab399f3)

**Comment by barbarahui** [comment]
I filed a Nuxeo JIRA ticket for this: https://jira.nuxeo.com/browse/SUPNXP-51504

**Comment by barbarahui** [comment]
JSON report containing information on the 187 items (across 25 collections) where we think the order of the complex object components in Calisphere doesn't match what is in the Nuxeo UI: https://drive.google.com/drive/folders/1IMknt9UxHxZRduDJ6ILrIJUCh2H5fKwz

**Comment by barbarahui** [comment]
```
Collection ID  Count of complex objs with ordering problem
27809          1
27124          13
26883          45
26466          2
26887          1
26771          5
65             5
26864          1
27569          16
26713          54
26147          1
27598          16
28203          2
26677          1
26945          5
1324           1
26895          4
27594          2
28040          3
15586          3
18409          1
25889          2
28197          1
472            1
4908           1
```

**Comment by barbarahui** [comment]
I did some more digging, and not all of the problematic objects are missing `pos` (position) in the database. A couple of different examples I found when spot checking:

### 1987_0222_UCI_Choir : California and UCI Chamber Singers
Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/8610b0c8-f3f7-4978-b264-f10b5dddd112/view_documents 
Calisphere stage: https://calisphere-stage.cdlib.org/item/8610b0c8-f3f7-4978-b264-f10b5dddd112

The issue with this object is that there are grandchildren nested inside a couple of the children. Child `1987_0222_UCI_Choir_1of2` has an object nested inside of it. Child `1987_0222_UCI_Choir_2of2` does as well. The old fetcher was picking up these nested grandchildren and displaying them mixed in with the children. Since I modified the fetcher to fix https://github.com/ucldc/rikolti/issues/1000 it will no longer fetch grandchildren, only direct children of the parent object. Is this correct?

### A system of ethicks. /By the Reverend Mr. Henry Grove. [Vol. 2]
Nuxeo: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/097c0984-4e1f-43b5-b39b-101558ae3921/view_documents
Calisphere stage: https://calisphere-stage.cdlib.org/item/ark:/21198/n1j60r/

Pages 240 and 241 are reversed in Nuxeo:

![Image](https://github.com/ucldc/rikolti/assets/296041/e16ca461-3621-4803-a8a3-a0281c4eade6)

The are *not* reversed in the UI. These objects have `pos` values in the database, so I'm not sure what's going on here.

**Comment by barbarahui** [comment]
I did some testing to see if I could fill in `pos` values for objects missing them via the UI. I was able to get the values populated, but not in the order that I would have expected. It might be easier to demonstrate on zoom, but here are the steps I followed:

1. Copy and paste a problematic object into my personal folder on nuxeo (UCOP/barbaratest)
2. Select the first component object by clicking the box on the left
3. Click the "move up" button that appears below the component objects
4. Logout of nuxeo and log back in
5. The component objects in the main page and in the left sidebar now both have the same order, and the order remains consistent. The database also now has `pos` filled in. The fetcher now retrieves the objects in this order consistently.

HOWEVER, the order is nothing like what was displayed in the UI before this. So I think that the best we can do to fix the objects with missing `pos` is to programmatically order them alphabetically by title or by filename. Then users will have to manually reorder them if this is incorrect.

This would just be a fix for existing records that are missing `pos`. We still need to replicate the workflow that results in complex object components to be created without `pos` and fix it so that we don't get new objects with this problem going forward.

**Comment by barbarahui** [comment]
The secondary issue we discovered, where more than one child object has the same `pos` value, is thankfully not that widespread. Here's the info on the 4 complex objects with the problem:

### 097c0984-4e1f-43b5-b39b-101558ae3921
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/097c0984-4e1f-43b5-b39b-101558ae3921/view_documents
329 components total
2 components have pos 430

### 63edf544-4746-4211-adc7-1bf05edec202
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/63edf544-4746-4211-adc7-1bf05edec202/view_documents
2 components total
2 components have pos = 0

### f026c534-b844-46a3-ab70-e3637cf71e12
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/f026c534-b844-46a3-ab70-e3637cf71e12/view_documents
160 components total
2 components have pos 54
2 components have pos 98

### 0e45044b-c08a-45ef-bf38-76f065878dd5
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/0e45044b-c08a-45ef-bf38-76f065878dd5/view_documents
706 components total
305 pairs
pos 1-305 are doubled

**Comment by barbarahui** [comment]
A list of complex objects (by path) in Nuxeo whose children have no `pos` in the database:

[complex_obj_null_pos_paths.txt](https://github.com/user-attachments/files/16072525/complex_obj_null_pos_paths.txt)

This includes objects that aren't published to Calisphere.

**Comment by barbarahui** [comment]
A file with more complete info (uid, path, title) on the 1227 complex objects whose children have no `pos` in the db:

[parent_obj_no_pos.json](https://github.com/user-attachments/files/16072550/parent_obj_no_pos.json)

**Comment by aturner** [comment]
@barbarahui sample object #13, with components that have metadata from nuxeo_spreadsheet import (following UCB EDA's method):

/asset-library/UCOP/aturner/orderingtest/Example 12.5962533403185838
https://nuxeo.cdlib.org/nuxeo/nxdoc/default/db065b59-8ef8-44e1-a902-1f1e58e988ad/view_documents

**Comment by aturner** [comment]
Next steps -- confer with Nuxeo campuses, sharing list of complex objects with mis-ordered components; would they like us to programmatically sort based on filename??

**Comment by aturner** [comment]
Summary of next steps:

- Communicating with campuses
  - Provide list of objects w/ Nuxeo campuses
  - Ask them if they’d like to re-order via UI -or- let us programmatically order components
  - Caveat that UI may not immediately reflect ordering
- Updating FD documentation: caveat re: uploading to Project Folder and moving stuff from there as components
- Looking ahead: create a DAG to run component ordering script on objects with components that lack position markers; to scope at what frequency, if we’d want a report
-

**Comment by barbarahui** [comment]
Updated list of paths for complex objects that have the null `pos` problem. Objects with only one component have been filtered out.

[complex_obj_null_pos_paths.txt](https://github.com/user-attachments/files/16274468/complex_obj_null_pos_paths.txt)

**Comment by christinklez** [comment]
Tracking emails to campuses:
- UCB EDA: https://help.oac.cdlib.org/a/tickets/141288
- UCI: https://help.oac.cdlib.org/a/tickets/141289
- UCLA: https://help.oac.cdlib.org/a/tickets/141290
- UCM: https://help.oac.cdlib.org/a/tickets/141291
- UCR: https://help.oac.cdlib.org/a/tickets/141292
- UCSF: https://help.oac.cdlib.org/a/tickets/141293

**Comment by christinklez** [comment]
@barbarahui @aturner -- an update that we've received confirmation from all campus units that it's okay to run the positioning script for all Nuxeo complex objects currently missing position numbers.

@aturner -- the spreadsheet also includes indicators on which collections need to be reharvested. We can touch base on that later, after the positioning script has been run.

Thanks!!

**Comment by christinklez** [comment]
@barbarahui -- before running the positioning script, would you be able to do one more run to identify documents that have component objects with missing positions?

Jason at UCB EDA went ahead and touched all of the objects and is currently happy with the current position order of their collections, and provided approval to publish these to Calisphere. I let him know that we'll do a double check on these collections to check if he missed any. Since he's currently happy with the component object ordering, he doesn't want them to be arranged by filename (if they don't have positions) and would prefer to use the "move" functions to trigger the numbering.

Thank you!

cc: @aturner

**Comment by barbarahui** [comment]
@christinklez I'm attaching a list of all of the documents with missing positions. They're ordered alphabetically, so UCB's are at the top.

[complex_obj_no_order_paths_2024-09-16T18:21:24.PDT.txt](https://github.com/user-attachments/files/17032352/complex_obj_no_order_paths_2024-09-16T18.21.24.PDT.txt)

**Comment by christinklez** [comment]
New tab in this spreadsheet: https://docs.google.com/spreadsheets/d/1Pej1YCP6tB8nERkZx3vX1CbbpzaADivV2GQKE7hBvyw/edit?gid=1496331430#gid=1496331430 -- for UCB EDA documents only.

There were 12 objects (from their newest most recently harvested/published collections) that would be impacted by the positioning script. I've messaged Jason about those 12 objects. 
https://help.oac.cdlib.org/a/tickets/142259

**Comment by christinklez** [comment]
Got the okay from UCB EDA to go ahead and run the position number script on their objects as well! Please feel free to run the position numbering script. Thank you!

**Comment by barbarahui** [comment]
I ran the script to assign an order value to all of the complex object components in Nuxeo that were missing them.

Summary: Updated 36459 children of 1196 objects

PR: https://github.com/ucldc/nuxeo-component-ordering/pull/1

I'm attaching a json file containing data on the updates, just in case we need to refer back to it at any point.[null_order_fix_report_2024-09-27T16_21_02.PDT.json](https://github.com/user-attachments/files/17171661/null_order_fix_report_2024-09-27T16_21_02.PDT.json)
